openvscode-server 1.62 blog post
gitpod-io/website pull request #1206
Opened 2021-11-03 23:06 UTC by jeanp413

Blog post for openvscode-server 1.62

Header image still needs to be updated

2021-11-03 23:12 UTC, mikenikles commented
The Netlify deployment will fail until there's a `static/images/blog/openvscode-server-1.62/teaser2.jpg` file available that is referenced from within the blog post.

Once that file exists, Netlify will complete the deployment and we can preview the blog post.

2021-11-03 23:28 UTC, jeanp413 commented
@mikenikles Thanks for pointing that out. I've added a placeholder image for now

2021-11-03 23:34 UTC, mikenikles commented
You're welcome, the blog preview is now available at https://deploy-preview-1206--gitpod-kumquat.netlify.app/blog/openvscode-server-1.62.

2021-11-04 05:10 UTC, akosyakov commented on src/routes/blog/openvscode-server-1.62.md
> +author: jeanp413, akosyakov
It should be Jean Pierre and Lou

2021-11-04 05:12 UTC, akosyakov commented on src/routes/blog/openvscode-server-1.62.md
> +As you may know, we provide insiders builds for openvscode-server and Gitpod VS Code. This is thanks to a couple of github actions we’ve set up. We noticed these upstream changes immediately and star
We should have links here to gitpod preferences to switch to insiders. Also link to GitHub actions.

2021-11-04 07:15 UTC, akosyakov commented on src/routes/blog/openvscode-server-1.62.md
> +You can also quickly explore the latest version of VSCode from within Gitpod, all you have to do is prefix a GitHub URL with `gitpod.io/#https://github.com/example-org/your-repo` (or install the [bro
VS Code with space

2021-11-04 13:16 UTC, JohannesLandgraf commented on src/routes/blog/openvscode-server-1.62.md
> +author: jeanp413, akosyakov
It is quite important to have you as a project lead in here @akosyakov

2021-11-04 13:45 UTC, jeanp413 commented on src/routes/blog/openvscode-server-1.62.md
> +author: jeanp413, akosyakov
@loujaybee please add yourself in the `src/contents/authors.ts` file

2021-11-05 07:40 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +When we launched our [history of the last four years of Cloud IDEs](https://www.gitpod.io/blog/cloud-ide-history) on Oct 20, we spoke about the road ahead and wrote:
```suggestion
When we launched our [history of the last four years of Cloud IDEs](https://www.gitpod.io/blog/cloud-ide-history) on Oct 20, we spoke about the road ahead:
```

2021-11-05 07:43 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +As you may know, we provide Insiders builds for Gitpod VS Code and OpenVSCode Server. This is thanks to a couple of GitHub actions we’ve set up. We noticed the VS Code Server changes immediately and
In case the reader doesn't know, can we share a link? It would be good if we have proper docs for this in future, I think because it's a nice feature, where's the best place to current link? Just ot the release repo? 

```suggestion
As you may know, [we provide Insiders builds](https://github.com/gitpod-io/openvscode-releases) for Gitpod VS Code and OpenVSCode Server. This is thanks to a couple of GitHub actions we’ve set up. We noticed the VS Code Server changes immediately and started working on integrating them. By now, we have been running them in production for more than a week and today we are releasing them for everybody.
```

2021-11-05 07:44 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +A month after [we released OpenVSCode Server](https://www.gitpod.io/blog/openvscode-server-launch), we are excited to see that Microsoft indeed open-sourced their [server implementation](https://gith
```suggestion
A month after [we released OpenVSCode Server](https://www.gitpod.io/blog/openvscode-server-launch), we are excited to see that Microsoft open-sourced their [server implementation](https://github.com/microsoft/vscode/commit/822f995357f725216cdee6e05f1f1552ccbbd882) for running VS Code in the browser 🚀. This happened faster than we anticipated - first and foremost we want to say **thank you to the excellent VS Code team**. The community deserves that the most popular developer tool of the planet keeps its open nature.
```

2021-11-05 07:46 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +In September we announced [OpenVSCode Server](https://github.com/gitpod-io/openvscode-server), an open-source project that runs upstream VS Code on a remote machine accessed through a modern web brow
I'm still, not a massive fan of the wording "backed" because of the ambiguity, but I don't have a suggestion at the moment though, so let's not let it block the publishing of the post, I'll try and find out if we have a better option for the phrasing...

2021-11-05 07:48 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +So OpenVSCode Server just adds our own set of minimal changes on top of it to:
Suggestion to remove "just" to make the statement stronger 🙏 

```suggestion
So OpenVSCode Server is still useful, and adds some minimal changes on top of VS Code to:
```

2021-11-05 07:50 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +Unfortunately, there’s not a standalone product for VS Code Server yet and while the source code is open-sourced now and you can build it yourself, you cannot use the marketplace as it is restricted
```suggestion
Unfortunately, even with this release from Microsoft, there's still no standalone product for VS Code Server yet and while the source code is open-sourced now and you can build it yourself, you cannot use the marketplace as it is restricted to only be used by Microsoft products.
```

2021-11-05 07:53 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +author: jeanp413, akosyakov, loujaybee
@filiptronicek / @JohannesLandgraf - what's the protocol, because you also helped out here, want to join us on the authors list?

2021-11-05 07:59 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +Try the new 1.62 OpenVSCode Server today or it’s Insiders version and don’t forget to leave feedback and file any issues you encounter.
```suggestion
Try the new 1.62 OpenVSCode Server or the insiders version and don’t forget to [leave feedback and file any GitHub issues](https://github.com/gitpod-io/openvscode-server) if you need!
```

2021-11-05 08:00 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +You can also quickly explore the latest version of VS Code from within Gitpod, all you have to do is prefix a GitHub URL with `gitpod.io/#https://github.com/example-org/your-repo` (or install the [br
```suggestion
You can also quickly explore the latest version of VS Code from within Gitpod, all you have to do is prefix a GitHub URL with `gitpod.io/#https://github.com/example-org/your-repo` (or install the [browser extension](https://www.gitpod.io/docs/browser-extension#browser-extension)) to get started. 

And why not, because [Gitpod is free for up to 50 hours a month](https://www.gitpod.io/pricing).
```

2021-11-05 08:02 UTC, loujaybee approved these changes
Left a few comments, with suggestions (so we can just hit "add" if needed) however the post looks great @jeanp413 !! Thanks so much for helping put it together 🙏 🙏 🙏

2021-11-05 08:18 UTC, JohannesLandgraf commented on src/routes/blog/vscode-server.md
> +So OpenVSCode Server just adds our own set of minimal changes on top of it to:
Agree to make the statement stronger. However, 'still' also does not really convey strength. How about: 'OpenVSCode Server adds some minimal changes on top of VS Code to: ..'

2021-11-05 08:20 UTC, JohannesLandgraf commented on src/routes/blog/vscode-server.md
> +Try the new 1.62 OpenVSCode Server today or it’s Insiders version and don’t forget to leave feedback and file any issues you encounter.
Do we write insiders or Insiders?

2021-11-05 08:43 UTC, filiptronicek requested changes
Left a couple of comments 😊

2021-11-05 08:43 UTC, filiptronicek commented on src/routes/blog/vscode-server.md
> +Publishing OpenVSCode Server was motivated by the fact that Microsoft hadn’t at the time published any source code for their own implementation of a server that was able to run Visual Studio Code, wh
Nit(non-blocking): would be great to split this into 3 or more sentences, I got lost whilst reading them 😕.

2021-11-05 08:43 UTC, filiptronicek commented on src/routes/blog/vscode-server.md
> +These [GitHub actions](https://github.com/gitpod-io/openvscode-releases) run daily to update OpenVSCode Server with the latest upstream changes, run integration, smoke tests, and make a github pre-re
```suggestion
These [GitHub actions](https://github.com/gitpod-io/openvscode-releases) run daily to update OpenVSCode Server with the latest upstream changes, run integration and smoke tests, and make a github pre-release along with publishing the updated [docker image](https://hub.docker.com/r/gitpod/openvscode-server) to Docker Hub under the Insiders tag.
```

2021-11-05 09:04 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +So OpenVSCode Server just adds our own set of minimal changes on top of it to:
Agree, I've updated to be: "OpenVSCode Server adds some much-needed, yet minimal changes on top of VS Code to". I'll commit the change, but any further suggestions, feel free to add on top! 🙏

2021-11-05 09:06 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +Publishing OpenVSCode Server was motivated by the fact that Microsoft hadn’t at the time published any source code for their own implementation of a server that was able to run Visual Studio Code, wh
@filiptronicek thanks for the feedback 🙏  Could you leave suggestions with the feature where possible for small stuff, as it's easier to accept them and less chance that we misinterpret your suggestion 🙏 

We can split on this sentence, does that make sense? 

```
Publishing OpenVSCode Server was motivated by the fact that Microsoft hadn’t at the time published any source code for their own implementation of a server that was able to run Visual Studio Code, which Microsoft uses to power GitHub Codespaces and their remote extensions. 

Since many developers and organisations wanted to run VS Code as a full web application in their daily workflows with the same low-footprint technique used by Gitpod and Codespaces, we decided to [share our own server implementation](https://www.gitpod.io/blog/openvscode-server-launch) with everyone.

2021-11-05 09:08 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +Try the new 1.62 OpenVSCode Server today or it’s Insiders version and don’t forget to leave feedback and file any issues you encounter.
Good question @JohannesLandgraf 🤔  Let me revert that part of the suggestion, I'm not sure if we're referring to it as a proper noun. Also kinda confusing as we have an "insiders" and VSCode have an "insiders" 🤔

2021-11-05 09:08 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +author: jeanp413, akosyakov, loujaybee
Good to know, thanks ! I thought similar but wanted to double-check!

2021-11-05 09:09 UTC, loujaybee commented on src/routes/blog/vscode-server.md
> +Publishing OpenVSCode Server was motivated by the fact that Microsoft hadn’t at the time published any source code for their own implementation of a server that was able to run Visual Studio Code, wh
I'll commit, but if you've got other suggestions, stick them back on the diff 🙏

2021-11-05 10:30 UTC, bigint commented on src/routes/blog/vscode-server.md
> +> As VS Code and cloud-based, remote development continue to grow in popularity, we hope to see the server-side implementation powering GitHub Codespaces being open-sourced in the upstream repository
```suggestion
> As VS Code and cloud-based, remote development continues to grow in popularity, we hope to see the server-side implementation powering GitHub Codespaces being open-sourced in the upstream repository by Microsoft.
```

2021-11-05 10:30 UTC, bigint commented on src/routes/blog/vscode-server.md
> +These [GitHub actions](https://github.com/gitpod-io/openvscode-releases) run daily to update OpenVSCode Server with the latest upstream changes, run integration and smoke tests, and make a github pre
```suggestion
These [GitHub actions](https://github.com/gitpod-io/openvscode-releases) run daily to update OpenVSCode Server with the latest upstream changes, run integration and smoke tests, and make a GitHub pre-release along with publishing the updated [docker image](https://hub.docker.com/r/gitpod/openvscode-server) to Docker Hub under the Insiders tag.
```

2021-11-05 14:32 UTC, merged