update email address for the sales request.
gitpod-io/website pull request #1318
Opened 2021-12-04 21:06 UTC by nisarhassan12

Fixes #1167

2021-12-04 21:11 UTC, nisarhassan12 commented on src/functions/submit-form.ts
> +      : process.env.SENDGRID_TO_EMAIL || "contact-test@gitpod.io",
@mikenikles I'm unable to understand why do we have `contact-test@gitpod.io` here the address won't work, right ? Should I remove it ?

2021-12-06 04:45 UTC, mikenikles requested changes

2021-12-06 04:45 UTC, mikenikles commented on src/functions/submit-form.ts
> +      : process.env.SENDGRID_TO_EMAIL || "contact-test@gitpod.io",
It looks like a fallback in the old code to make sure `email.to` always had a value, likely because the Sendgrid client will throw an exception if it's empty.

The email itself doesn't exist, so that's anyway not an ideal solution. See my comment above, we need to refactor this code.

2021-12-06 04:45 UTC, mikenikles commented on src/functions/submit-form.ts
>    const email: Email = JSON.parse(event.body!) as Email;
❗ This is a security issue. We can't accept `to` email addresses from an untrusted HTTP request ❗

Please check your emails to see what kind of damage a malicious person can cause. Also, please revert this code asap so we no longer expose this security risk.

2021-12-17 01:35 UTC, mikenikles commented
@nisarhassan12 Let me know if you'd like to discuss an alternative solution. The key factor is to make sure we do not expose the `from` email field via an API.

2021-12-18 03:17 UTC, mikenikles commented
I'll work on that.

2021-12-18 03:45 UTC, mikenikles commented
I don't know what causes it, but `npm run validate` fails in this PR.

Replaced with #1374.

2021-12-18 03:45 UTC, closed without merging