update /pricing & /self-hosted.
gitpod-io/website pull request #1329
Opened 2021-12-07 13:41 UTC by nisarhassan12

Fixes #1284

2021-12-09 21:26 UTC, nisarhassan12 commented on src/routes/pricing.svelte
> +<UsedBy title="Used by 400k+ developers" />
This needs to be changed to 500k+

2021-12-22 02:27 UTC, nisarhassan12 commented
The Self-hosted page is ready to be reviewed there is still some work remaining for the pricing page though.

2021-12-22 04:24 UTC, metcalfc requested changes
Two of the FAQ entries also need updating.

```Can I create a team plan?

Of course! You can use Gitpod Self-Hosted Community on your own infrastructure for free for unlimited users. If you'd like to try additional features like unlimited prebuilds, shared workspaces, snapshots and an admin dashboard, the Free tier is available without a license for the first 10 users. You can upgrade to to the Professional Plan at any time. Simply update your existing instance with a license key. Currently, Self-hosted Gitpod licenses can currently only be purchased through contacting sales . Please [request a license ](/enterprise-license)key or get in touch if you have any questions.
```

```How can I install Self-Hosted?


You can either install Gitpod Self-Hosted on [Google GKE](/docs/self-hosted/latest/installation/on-gke), [Amazon EKS](/docs/self-hosted/latest/installation/on-eks), [Azure AKS](/docs/self-hosted/latest/installation/on-aks) or [K3s](/docs/self-hosted/latest/installation/on-k3s). 
```

2021-12-22 04:24 UTC, metcalfc commented on src/contents/self-hosted.ts
> +  title: "Basic",
Free

2021-12-22 04:24 UTC, metcalfc commented on src/contents/pricing.ts
>      title: "Basic",
Basic has been renamed to Free.

2021-12-22 04:24 UTC, metcalfc commented on src/contents/self-hosted.ts
> +    text: "Contact Sales",
Contact Sales should be "Register and Install Now"

2021-12-22 05:24 UTC, nisarhassan12 commented
Thanks, Chad. I have made the requested changes in https://github.com/gitpod-io/website/pull/1329/commits/ce0e4aa805bf476ea743e104249c9516a30f0089. 

The Pricing page is now also ready to be reviewed.

2021-12-22 05:31 UTC, nisarhassan12 commented on src/components/self-hosted/faqs.svelte
>          <a href="/docs/self-hosted/latest">Self-Hosted Docs</a> for more information.
@metcalfc Should I remove lines 64 and 65 ? Thanks

2021-12-22 05:37 UTC, metcalfc commented
I can't find it here but one of the saas pages has 0$ instead of $0 once that's fixed I think we are good to go

2021-12-23 00:21 UTC, mikenikles requested changes
## `/pricing`

### Used by logos

The logos have various sizes, with Amazon being super large. Looking at the design spec, they should all be more aligned.

<details>
  <summary>Click to view screenshot</summary>
  <img src="https://user-images.githubusercontent.com/788827/147168840-cff20ce8-45e2-4e51-b0ec-91dec413a0c5.png"/>
</details>

### Get started

The design shows "Get started for free" whereas this PR only has "Get Started". It'd be good to match the marketing wording from the design.

## `/self-hosted`

### Used by logos

This section is missing.

2021-12-23 01:20 UTC, nisarhassan12 commented
> The logos have various sizes, with Amazon being super large. Looking at the design spec, they should all be more aligned.

Thanks, @mikenikles they follow the specs see the below screenshot Not sure why that is the case for you maybe for some reason some CSS didn't load for you. I have tested on Firefox, Chrome, Brave and Safari on Desktop and on  Firefox, Chrome, Brave on my phone and was not able to reproduce this.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/46004116/147172546-ed663de0-2a8c-49e9-87ee-ea358ea8a616.png"  />
</details>

> This section is missing.

This Pr initially had that I removed it in https://github.com/gitpod-io/website/pull/1329/commits/adfde91f7346d79b1cd65761e01bb7d928f9d8b0 the reason why I did this can be found in this Slack [thread](https://gitpod.slack.com/archives/C01KGM9ETU6/p1640159139253300?thread_ts=1640140350.251400&cid=C01KGM9ETU6) Sorry I should have mentioned that in the PR. 

> The design shows "Get started for free" whereas this PR only has "Get Started". It'd be good to match the marketing wording from the design.

✅ Done. Sorry I completely missed that.

2021-12-23 01:34 UTC, mikenikles approved these changes
Thanks Nisar for the explanations. LGTM :+1:

2021-12-23 01:34 UTC, merged