[Analytics] Website Tracking 2.0
gitpod-io/website pull request #1337
Opened 2021-12-08 14:19 UTC by jakobhero

2021-12-10 23:04 UTC, mikenikles requested changes
I see this PR is in draft, but had a moment to review and leave some notes that need to be addressed.

2021-12-12 12:12 UTC, jakobhero commented on src/components/banners/announcement.svelte
> +  data-analytics="&lcub&quotposition&quot:&quotannouncement&quot&rcub"
hi mike, thanks for swinging by proactively, your suggestion is super helpful! I am expecting a JSON string in `segment.svelte` and in order to make make it fit within svelte syntax, i escaped curly braces with `&lcub` and `&rcub` and quotes with `&quot`. your suggestion makes it much easier to read and works like a charm, i will modify all `data-analytics` props!🙏🏼

2021-12-12 12:25 UTC, jakobhero commented on src/components/segment.svelte
> +  const implicitPositions = ["nav", "footer", "main"];
no, what's happening with `implicitPositions` is that the event targets lineage is iterated to set a value for the analytics props `position`, which allows us to better understand where users made clicks, i.e. any click on the second `<nav>` element will fire an analytics event with a `"position": "nav"` property. the implicit `position` can be overwritten with any value value by passing the `data-analytics` prop to the button or any of its ancestors (e.g. see the [current menu in docs](https://github.com/gitpod-io/website/blob/7d8e7aa6b5fa169c528a7acc9312f4676c7bfcb2/src/components/docs/menu-section.svelte#L24), which is something we might want to do in #1296. i will swing by over there and check it out!👀

2021-12-12 12:34 UTC, jakobhero commented on src/components/segment.svelte
> +    //assign style of button to variant (e.g. if class contains "btn-primary", "btn-primary" will be passed)
part of the motivation of this PR is to reduce the number of analytics props that are passed explicitly so that analytics events are as standardised as possible and _normal_ modifications of components on the website will not require any addition of analytics code. If the result of the migration to Tailwind CSS is that the button type can be read from the classname prop in a similarly easy fashion as it is now and we will maintain that naming scheme for the foreseeable future, i would prefer to keep the implicit-when-possible approach for capturing the `variant` analytics prop. happy to discuss!

2021-12-12 14:43 UTC, mikenikles commented on src/components/segment.svelte
> +    //assign style of button to variant (e.g. if class contains "btn-primary", "btn-primary" will be passed)
Thanks for that info. I agree, let me give that some more thought in terms of how we can abstract the analytics code and make it easy to use.

It'd be nice to come up with an elegant and possibly reusable solution.

cc: FYI @Cahllagerfeld in case you want to join the discussion.

2021-12-12 17:13 UTC, mikenikles commented on src/components/segment.svelte
> +    //assign style of button to variant (e.g. if class contains "btn-primary", "btn-primary" will be passed)
Alright, I have an idea worth exploring. At a high-level, we'll use a Svelte action ([docs](https://svelte.dev/docs#use_action)) called `segment` and replace most of the analytics click listener logic with the action.

Where we currently use `btn-*` CSS classes, we replace them with corresponding Svelte components. This is needed as part of the Tailwind migration anyway, so we may as well introduce it as part of this PR.

Within these new button Svelte components, we use the `segment` action for tracking instead of relying on the class names.

I will push some updates to this PR later today with examples.

2021-12-14 08:48 UTC, mikenikles approved these changes
Thanks for the catch-up @jakobhero, this is good to go from my side.

2021-12-16 04:50 UTC, mikenikles commented on src/components/segment.svelte
> +            page: page,
❓ @jakobhero I'm curious to better understand why this is needed in the `context` when it is already passed as an object in the first argument for `page()`.

I suspect it's to do with how we process the data downstream, but would love your insight so I can make sure the NPM package I'm working on doesn't miss a feature we need.

2021-12-16 09:42 UTC, jakobhero commented on src/components/segment.svelte
> +            page: page,
you're spot on, this is how Segment processes the data by default (i.e. when an empty `page()` is sent), so i'm maintaining that structure in order to not jeopardise the acceptance of the event downstream. it's a bit of a waste of bandwidth though...

2021-12-16 18:59 UTC, mikenikles commented on src/components/segment.svelte
> +            page: page,
Excellent, thanks for the info.

2021-12-16 19:00 UTC, mikenikles commented
This is ready from my point of view, @jakobhero I'll let you do the honours of merging it 🎉

2021-12-16 22:00 UTC, jakobhero commented
> This is ready from my point of view, @jakobhero I'll let you do the honours of merging it 🎉

thanks @mikenikles !🔥 i committed two more minor changes - if you don't see a problem with those either, i will merge tomorrow morning so that i can monitor the data

2021-12-16 22:44 UTC, mikenikles commented
Looks good to me, nice work cleaning up the `ip` situation :). Let's get this merged.

2021-12-17 08:07 UTC, merged