docs(prebuilds): clarify example about user variables
gitpod-io/website pull request #1526
Opened 2022-01-25 11:42 UTC by trumbitta

## Description
I wasn't sure if user specific environment variables were available in `before` scripts (which are the suggested scripts where to globally install npm packages from), so I did my tests and found out.

I also found out that `gp` is an alias for `git pull` in the `git` plugin for `oh-my-zsh` so I had to specify the full path.
Given how popular `oh-my-zsh` is, and that the `git` plugin is enabled by default, I thought it'd be safer to also propose this change to the provided example.

## Release Notes

```release-note
updated example on how to use user specific environment variables in prebuilds
```

2022-01-25 12:00 UTC, axonasif requested changes

2022-01-25 13:05 UTC, trumbitta commented on gitpod/docs/prebuilds.md
> +      eval $(/usr/bin/gp env -e)
I chose `command` because it reminded me something I knew from the old times 🧓

2022-01-25 15:12 UTC, axonasif approved these changes
Thank you very much for contributing @trumbitta 🎉

2022-01-25 15:18 UTC, axonasif requested changes

2022-01-25 15:18 UTC, axonasif commented on gitpod/docs/prebuilds.md
> +      echo "Hello ${MY_VAR}
It's missing a closing double-quote `"`
Also I think that putting an example here might not be on point because the user is looking for this as they already find that some env var is empty or not working.

2022-01-25 15:33 UTC, trumbitta commented on gitpod/docs/prebuilds.md
> +      echo "Hello ${MY_VAR}
Oof copy-pasting from my terminal on lunch break with a ham sandwich being wolfed down. It's fixed now 🙏 

About the example in there, I just thing obvious always wins. It's for giving context and to anticipate and reinforce the closing sentence: "After that, the available environment variables will be installed into the rest of you shell script and can be accessed normally."

You know, like the same thing having a picture near paragraph of text does.

But if I didn't convince you, just say the word and I'll delete it.

2022-01-25 15:43 UTC, axonasif commented on gitpod/docs/prebuilds.md
> +      echo "Hello ${MY_VAR}
Fair enough, it's just something that I had thought 😄

2022-01-25 15:44 UTC, axonasif approved these changes

2022-01-25 15:54 UTC, shaal commented
@trumbitta @axonasif AFAIK, User environment variables that you want to use during prebuild, are only available in prebuild that were triggered manually.
There are prebuilds that happen automatically (new commits, Gitpod update, etc) - that will run Prebuild and it will not have access to your user environment variables.

2022-01-25 15:56 UTC, trumbitta commented
> @trumbitta @axonasif AFAIK, User environment variables that you want to use during prebuild, are only available in prebuild that were triggered manually. There are prebuilds that happen automatically (new commits, Gitpod update, etc) - that will run Prebuild and it will not have access to your user environment variables.

@shaal I worked on this today, and I have prebuilds accessing my vars like this that are generated by commits on a MR in GitLab

2022-01-25 16:36 UTC, trumbitta commented
> I know this because I added IFTTT hook, to send me an email every time a prebuild runs. https://github.com/shaal/DrupalPod/blob/main/.gitpod.yml#L7
> 
> And I can see that whenever it's something I generated (commit I made) - env vars are loaded, but whenever it's generated by someone else commits, or Gitpod update - env vars are not accessible during prebuilds.

Ok this is already slightly different from what you said above, and something I didn't try :) but this PR is just a refactor of instructions that were already there. Do you think a different PR is worth it? What you are describing sounds more like a bug.

2022-01-25 16:41 UTC, shaal commented
@trumbitta it might be a bug? 
Currently, users without write access to a repo, can trigger manual prebuild, and when depending on env vars, it can become an issue.
I didn't test it yet, but it's possible that **_project_** env vars would solve this problem.

2022-01-31 08:45 UTC, merged

2022-01-31 09:04 UTC, trumbitta commented
❤️