e2e for the contact forms.
gitpod-io/website pull request #1722
Opened 2022-03-07 19:20 UTC by nisarhassan12

2022-03-07 20:14 UTC, nisarhassan12 commented on .gitpod.Dockerfile
> +FROM gitpod/workspace-node:latest
@mikenikles I didn't knew/was not able to figure out how to use multiple Docker images within a `.gitpod.yml` so moved it here from the config file. Does it look good?

2022-03-07 20:15 UTC, nisarhassan12 commented on .gitpod.Dockerfile
> +FROM gitpod/workspace-node:latest
Also, it took quite a long time for the workspace to start and the pre-build to finish maybe it's the 2 FROM that are having an impact here?

2022-03-08 14:41 UTC, nisarhassan12 commented on cypress/integration/sales_spec.js
> +    cy.visit("localhost:3000/contact/sales");
@mikenikles Currently the specs work locally. I don't know How can I get the URL for a workspace to be used here. Any suggestions? Thanks

2022-03-08 23:48 UTC, mikenikles requested changes

2022-03-08 23:48 UTC, mikenikles commented on .gitpod.Dockerfile
> +FROM gitpod/workspace-node:latest
We can remove this line. The `gitpod/workspace-full-vnc` image we use below is based on `gitpod/workspace-full` which contains Node.js [[1](https://github.com/gitpod-io/workspace-images/blob/main/legacy/full/Dockerfile#L120)]

2022-03-08 23:48 UTC, mikenikles commented on cypress/integration/sales_spec.js
> +    cy.visit("localhost:3000/contact/sales");
Have a look at the `baseUrl` configuration (see [docs](https://docs.cypress.io/guides/references/configuration#Global))

2022-03-08 23:48 UTC, mikenikles commented on cypress/integration/sales_spec.js
> +    cy.wait(100);
We shouldn't use `cy.wait(time)`. Please read the docs [[1](https://docs.cypress.io/api/commands/wait#Time)] and follow the best practices linked there.

2022-03-08 23:48 UTC, mikenikles commented on cypress/integration/sales_spec.js
> +    cy.get('[data-test-id="Self-hosting"]').click();
What do you think about using https://testing-library.com/docs/cypress-testing-library/intro/ instead of `data-test-*` attributes?

Please [see this chapter](https://testing-library.com/docs/) for an introduction to the testing library.

If you look at this PR, you had to manually add `data-test-*` attributes. With the testing library, we query for elements the way users query for elements, i.e. by looking for buttons with certain text.

2022-03-08 23:48 UTC, mikenikles commented on package.json
> +    "cypress:open": "cypress open --browser firefox"
Leaving this here as a reminder: We'll also need a `test:e2e` script that runs Cypress in the command line.

2022-03-09 11:35 UTC, nisarhassan12 commented on cypress/integration/sales_spec.js
> +    cy.wait(100);
@mikenikles I had a look at the docs Best Practices and the following is what it says:

![image](https://user-images.githubusercontent.com/46004116/157430692-e177da7f-c665-4738-89fc-a2fb41838c7e.png)

but when I run the spec without adding `cy.wait(100)` it fails to select the radio button label with a click. I have no idea why that might be see the below video:

https://user-images.githubusercontent.com/46004116/157433028-42847d72-d251-4f57-8036-0bc4fd501ac0.mov

If I do it with `cy.wait(100)` then the 'Self-hosting' option is selected as expected see the below video:

https://user-images.githubusercontent.com/46004116/157434061-e8012950-db8b-4369-b163-044c275dc089.mov

2022-03-10 06:55 UTC, nisarhassan12 commented on cypress/integration/sales_spec.js
> +    cy.get('[data-test-id="Self-hosting"]').click();
Thanks, Mike for sharing this I didn't know about this. I just migrated the existing specs to use it + also wrote the spec for the [Enterprise License](https://www.gitpod.io/enterprise-license) page using it.

2022-03-10 07:00 UTC, nisarhassan12 commented on cypress/integration/support_spec.js
> +    cy.findByTestId("consent").click();
@mikenikles I have gotten rid of all the other `data-test-id` attributes apart from the ones used for the checkboxes as I was not able to figure out how to target them with the testing library.

2022-03-10 07:02 UTC, nisarhassan12 commented on cypress/integration/support_spec.js
> +    cy.findByTestId("consent").click();
@mikenikles I have gotten rid of all the other `data-test-id` attributes apart from the ones used for the checkboxes as I was not able to figure out how to target them with the testing library.

2022-03-10 07:03 UTC, nisarhassan12 commented on cypress/integration/support_spec.js
> +    cy.findByTestId("consent").click();
@mikenikles I have gotten rid of all the other `data-test-id` attributes apart from the ones used for the checkboxes as I was not able to figure out how to target them with the testing library.

2022-03-10 10:31 UTC, nisarhassan12 commented on package.json
> +    "cypress:open": "cypress open --browser firefox"
Thanks, Mike I did that in https://github.com/gitpod-io/website/pull/1722/commits/37455beb136c01664c4b0375d949ef68450dbead.

2022-03-10 10:52 UTC, nisarhassan12 commented
@mikenikles Also not sure why but today the specs seem to be failing in Gitpod while they work reliably locally. The following is what I'm getting:
![Screenshot 2022-03-10 at 15-40-32 gitpodio-website-ffbg6o8sh14 0 - noVNC](https://user-images.githubusercontent.com/46004116/157645022-8eb5613f-2c64-4eda-b134-ad7becd21620.png)

2022-04-08 01:13 UTC, mikenikles approved these changes
That's a good starting point. It doesn't fix #1182 yet though (see [this comment](https://github.com/gitpod-io/website/issues/1182#issuecomment-1047919611)).

The tests in this PR don't actually test that the email is sent and received, neither do the tests validate the email content is correct.

In the interest of unblocking this, let's merge but keep #1182 open.

2022-04-08 01:13 UTC, mikenikles commented on cypress/integration/sales_spec.js
> +    cy.wait(100);
Some race condition or what not that happens there. I couldn't find a solution without refactoring the form input listeners (`on:change` and `bind:checked`).

Let's keep the wait in there as it's an isolated case with no quick fix.

2022-04-08 19:41 UTC, merged