Add the March 10, 2022 changelog
gitpod-io/website pull request #1749
Opened 2022-03-10 01:11 UTC by mikenikles

Close #1747.

2022-03-10 09:28 UTC, Cahllagerfeld requested changes

2022-03-10 09:28 UTC, Cahllagerfeld commented on src/lib/contents/changelog/2022-03-10.md
> +title: TODO
`title` & `excerpt` are still on TODO, just as a side-note before merging :D

2022-03-24 19:16 UTC, mikenikles commented
Waiting for @jankeromnes to provide a header image ([internal conversation](https://gitpod.slack.com/archives/C022HAT0H5Z/p1646904979770979?thread_ts=1646875681.535049&cid=C022HAT0H5Z)).

Once available, this PR is ready to be merged.

2022-04-13 13:55 UTC, Cahllagerfeld commented
@jankeromnes Could you please add the header image, so we can publish this delayed Changelog 😬

2022-04-15 13:34 UTC, Cahllagerfeld approved these changes
Thanks for adding the image @jldec

2022-04-15 13:35 UTC, merged