fix: refactor some of the VS Code settings sync
gitpod-io/website pull request #1976
Opened 2022-04-29 11:33 UTC by loujaybee

2022-04-29 11:38 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> -VS Code is so beloved hugely because of its endless possibilities for customization. A problem arises when there are multiple machines or VS Code instances you'd like to have with the same extensions
> VS Code is so beloved hugely

=> 

> VS Code is beloved

Would suggest being sparing with adverbs (i.e only use when really wanting to emphasize) 🙏

2022-04-29 11:41 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> -## How does it work?
Small thing to watch out for is referencing "it" or "this" without a subject. As it can leave the reader guessing the context. Can cause the same confusion as the `this` keyword in JS / programming 😆 

> "How does it work"

=> 

> "How does VS Code Settings Sync work"

Another example from further down the page:

> By default, every extension you install on Gitpod or, if set up, on your local VS Code instance gets synced. **This** comes with a few exceptions, though.

=> 

> By default, every extension you install on Gitpod or, if set up, on your local VS Code instance gets synced. **VS Code extension installation** comes with a few exceptions, though.

2022-04-29 11:42 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +- [Global State](https://code.visualstudio.com/docs/editor/settings-sync#_sync-user-global-state-between-machines)
1. Added links for all items here, extensions and global extensions were missing
2. Moved links to directly anchor from the text, rather than with the added `[docs]`

2022-04-29 11:44 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> -### About synced extensions
Would be good if we have an explicit section that discusses the difference between the two types of syncing that we have, and why Gitpod is not compatible with Microsoft.

2022-04-29 11:44 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +## Gitpod vs Microsoft Settings Sync
I think it's best if we have an explicit section that discusses the difference between the two types of syncing that we have, and why Gitpod is not compatible with Microsoft.

2022-04-29 11:45 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> -## On the web
Currently we're using "VS Code Browser" language elsewhere. I do agree that web would standardise with VS Code language use, maybe we should implement a separate item to update docs and the product to use web language.

2022-04-29 11:46 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> -## Locally
Elsewhere we are using "VS Code Desktop" to refer to VS Code running locally, I think it makes sense to use that language here, also.

2022-04-29 11:53 UTC, loujaybee commented on gitpod/docs/ides-and-editors/faqs.md
> +Verify settings sync is enabled by opening the Account menu in VS Code. The last line should show `Settings Sync is On`.
Would be nice to have a GIF here to show this.

2022-04-29 11:57 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> -4. Yay, it's done 🎉! Extensions and other preferences should start syncing right away. For troubleshooting you can take a look at `OUTPUT` > `Log (Settings Sync)`.
It's certainly part of Gitpod branding to be informal and friendly. However, I think we should be careful with informality direclty in documentation (as opposed to blog posts) when readers/users might be stressed / trying to fix something. I'd suggest we be careful with language like: "just follow the steps" (as it might be perceived as condescending / oversimplifying), and stick with direct language where we can (with the few exceptions to add 
some informality!). 

Example...

> 1. Make sure the [Gitpod extension](https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-desktop) is installed and enabled.

=> 

> 1. Install and enable the [Gitpod extension](https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-desktop)

2022-04-29 12:04 UTC, loujaybee commented on gitpod/docs/ides-and-editors/faqs.md
> +## Does Gitpod VS Code Settings Sync work with other products (e.g. Codespaces)?
Moved some of this content to the FAQ's to keep the main docs page about enabling / setting up, and FAQ's here more about edge-cases or additional information. We might want to consider adding backlinks to FAQ's or troubleshooting on each of the IDE pages 🤔

2022-04-29 19:45 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +By default, most desktop VS Code installations are configured to sync settings via a GitHub or a Microsoft account. These settings are synced to Microsoft's servers and are inaccessible to third-part
> Gitpod uses a custom settings sync to sync with the Gitpod servers

Not sure about the wording here, maybe change it to something like Gitpod implements it's own VS Code settings sync server

2022-04-29 19:51 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/faqs.md
> +3. Extensions manually installed from a `vsix` file
I think moving to troubleshooting would make more sense, if we could really make it the default place people go to for any VSC-related problems. We could link to the troubleshooting doc from both of the VS Code product pages and also the FAQ.

2022-04-29 19:51 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +**Note:** VS Code Browser in Gitpod settings are synced with Gitpod servers, not Microsoft.
Same here wording is odd :thinking: 
```suggestion
**Note:** For VS Code Browser in Gitpod, settings are synced with Gitpod servers, not Microsoft.
```

2022-04-29 19:51 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/faqs.md
> +Verify settings sync is enabled by opening the Account menu in VS Code. The last line should show `Settings Sync is On`.
💯

2022-04-29 19:53 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +<img class="shadow-medium w-full rounded-xl max-w-3xl mt-x-small" alt="Prompt to restart VS Code Desktop" src="/images/editors/restart-vscode.png">
`static/images/editors/restart-vscode.png` will probably change after Victor feedback

2022-04-29 19:54 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +You must authenticate with GitHub to enable settings sync.
```suggestion
You must authenticate with Gitpod to enable settings sync.
```

2022-04-29 19:54 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +You will be prompted which settings to sync, and to authenticate via GitHub.
```suggestion
You will be prompted which settings to sync, and to authenticate via Gitpod.
```

2022-04-29 19:55 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +<img class="shadow-medium w-full rounded-xl max-w-3xl mt-x-small" alt="Sign into GitHub to enable VS Code Settings Sync" src="/images/editors/signin-and-turnon.png">
```suggestion
<img class="shadow-medium w-full rounded-xl max-w-3xl mt-x-small" alt="Sign into Gitpod to enable VS Code Settings Sync" src="/images/editors/signin-and-turnon.png">
```

2022-04-29 19:56 UTC, jeanp413 commented on gitpod/docs/ides-and-editors/settings-sync.md
> +    <figcaption>Sign into GitHub to enable VS Code Settings Sync</figcaption>
```suggestion
    <figcaption>Sign into Gitpod to enable VS Code Settings Sync</figcaption>
```

2022-04-29 20:04 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> +You must authenticate with GitHub to enable settings sync.
I found this as well, it seems that @loujaybee is secretly working for GitHub and making us all use their Settings Sync 🤔.

2022-05-02 07:44 UTC, akosyakov commented on gitpod/docs/ides-and-editors/faqs.md
> +## Does Gitpod VS Code Settings Sync work with other products (e.g. Codespaces)?
I wonder whether we should have FAQ in each product page instead, or some kind of mix. I would think it is rather hard to find this page if you are a user of some editor, i.e. I will go to VS Code Web page instead.

Or at least FAQs and troubleshooting pages from each IDE page.

2022-05-02 07:49 UTC, akosyakov commented on gitpod/docs/ides-and-editors/settings-sync.md
> +However, you may come across the challenge of having many multiple VS Code instances needing to share the same extensions, themes and settings. Since every start of a [Gitpod workspace](https://www.g
```
Since every start of a [Gitpod workspace](https://www.gitpod.io/docs/workspaces) is a new instance of VS Code, using [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) helps you avoid re-setting your environment for each new workspace and embrace ephemeral Gitpod workspaces
```

I'm not sure about rephrasing it. The value of Settings Sync is sharing between VS Code in Gitpod and local VS Code **for anything**. For instance, I work on some local projects outside of Gitpod, then can move to Gitpod and preserve my settings/extensions and back. The ephemeral nature of workspaces in Gitpod is a more remark to highlight why this is important in Gitpod itself.

A new introduction is too much about Gitpod not about value of Setting Sync.

2022-05-02 07:51 UTC, akosyakov commented on gitpod/docs/ides-and-editors/settings-sync.md
> +Settings sync in the browser is enabled by default. You can enable and disable Settings Sync from the Manage gear menu at the bottom of the Activity Bar.
`You can enable and disable Settings Sync from the Manage gear menu at the bottom of the Activity Bar.`

We should not recommend it and users cannot really. In next workspace it will enabled again.

2022-05-02 07:54 UTC, akosyakov commented on gitpod/docs/ides-and-editors/settings-sync.md
> +**Please note:** Any VS Code instances configured for Microsoft VS Code settings sync are not compatible with Gitpod settings sync.
I'm not sure what it means?

Our data format is compatible.

2022-05-02 18:20 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> +**Note:** VS Code Browser in Gitpod settings are synced with Gitpod servers, not Microsoft.
I'd even add an `'s` to the server owners - `Gitpod's` and `Microsoft's`

2022-05-02 18:25 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> +**Please note:** Any VS Code instances configured for Microsoft VS Code settings sync are not compatible with Gitpod settings sync.
I guess this was meant to point out that data isn't automatically migrated from MS sync? I agree this should be at least re-worded though, AFAIK the compatibility is all there :)

2022-05-09 09:09 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +However, you may come across the challenge of having many multiple VS Code instances needing to share the same extensions, themes and settings. Since every start of a [Gitpod workspace](https://www.g
The content is quite similar before/after, but mostly re-worded/re-ordered.

| Before      | After |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/5528307/167377721-cf99b79c-947f-4813-b547-001bda9066af.png) | ![image](https://user-images.githubusercontent.com/5528307/167377691-b539c416-29ff-4d75-af29-7360c3507656.png) |

I can remove "and embrace ephemeral Gitpod workspaces" if that helps?

2022-05-09 09:16 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +By default, most desktop VS Code installations are configured to sync settings via a GitHub or a Microsoft account. These settings are synced to Microsoft's servers and are inaccessible to third-part
Updated: 3c0a1c4fa3c93640c9d9838191c16793f01d9f17

2022-05-09 09:16 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +You must authenticate with GitHub to enable settings sync.
Updated: de40498e88c1052c5899b1e844b7d71e5e77bf29

2022-05-09 09:17 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +You must authenticate with GitHub to enable settings sync.
Also, lol.

2022-05-09 09:20 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +You will be prompted which settings to sync, and to authenticate via GitHub.
Fixed: de40498e88c1052c5899b1e844b7d71e5e77bf29

2022-05-09 09:20 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +<img class="shadow-medium w-full rounded-xl max-w-3xl mt-x-small" alt="Sign into GitHub to enable VS Code Settings Sync" src="/images/editors/signin-and-turnon.png">
Fixed: de40498e88c1052c5899b1e844b7d71e5e77bf29

2022-05-09 09:20 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +**Please note:** Any VS Code instances configured for Microsoft VS Code settings sync are not compatible with Gitpod settings sync.
Removed: de40498e88c1052c5899b1e844b7d71e5e77bf29

2022-05-09 09:25 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +**Note:** VS Code Browser in Gitpod settings are synced with Gitpod servers, not Microsoft.
Updated to in d709bcadbe33f8bdc00d8f5b592b5bcf39182323

> **Note:** When using VS Code in the Browser within Gitpod, user settings are synced with Gitpod's servers, not Microsoft's.

Hopefully that helps 😁

2022-05-09 09:26 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +    <figcaption>Sign into GitHub to enable VS Code Settings Sync</figcaption>
Fixed: https://github.com/gitpod-io/website/commit/de40498e88c1052c5899b1e844b7d71e5e77bf29

2022-05-09 09:34 UTC, loujaybee commented on gitpod/docs/ides-and-editors/settings-sync.md
> +<img class="shadow-medium w-full rounded-xl max-w-3xl mt-x-small" alt="Prompt to restart VS Code Desktop" src="/images/editors/restart-vscode.png">
I'm not sure what feedback you're referring to, @jeanp413 ?

2022-05-09 09:39 UTC, loujaybee commented on gitpod/docs/ides-and-editors/faqs.md
> +Verify settings sync is enabled by opening the Account menu in VS Code. The last line should show `Settings Sync is On`.
Will remove section because of: https://github.com/gitpod-io/website/pull/1976#discussion_r862652666

Removed: 5ee1213d671b9a355638be61af22d1bde8a64b30

2022-05-09 14:23 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> +<img class="shadow-medium w-full rounded-xl max-w-3xl mt-x-small" alt="Prompt to restart VS Code Desktop" src="/images/editors/restart-vscode.png">
@loujaybee I think @jeanp413 is referring to the fact that this is now not a prompt to close, but just a notification:
![image](https://user-images.githubusercontent.com/29888641/167430666-e98937ae-cfb1-429b-b543-32d29603801b.png)

where this was before: 
![image](https://user-images.githubusercontent.com/29888641/167430999-9a60a814-4941-4b4a-bda2-6541ca4135fe.png)

2022-05-09 16:29 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> +- [Global State](https://code.visualstudio.com/docs/editor/settings-sync#_sync-user-global-state-between-machines)
I like this 👍

2022-05-09 16:33 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> -## On the web
May be relevant to link our internal discussion about this: https://gitpod.slack.com/archives/C01KGM9BH54/p1651514833164129.

2022-05-09 17:37 UTC, filiptronicek reviewed
I had an idea about screenshots - should we do them in dark mode, when docs are in light mode? Maybe we could have two versions of every screenshot and make them adaptive like GitHub enables us to do it [[1](https://github.com/stefanjudis/github-light-dark-image-example)] (after https://github.com/gitpod-io/website/pull/1865 gets merged)?

cc @nisarhassan12

2022-05-09 17:47 UTC, filiptronicek reviewed
Maybe we can change `static/images/editors/enable-settings-sync.png` to make it obvious which option to pick (as there's quite a lot of them)? 

![image](https://user-images.githubusercontent.com/29888641/167467485-67688108-ae23-4bad-8226-ac2dd3fe7013.png)

2022-05-09 18:36 UTC, filiptronicek requested changes
Some minor things I found, really liking the changes so far!

2022-05-09 18:36 UTC, filiptronicek commented on gitpod/docs/ides-and-editors/settings-sync.md
> +By default, most desktop VS Code installations are configured to sync settings via a GitHub or a Microsoft account. These settings are synced to Microsoft's servers and are inaccessible to third-part
Is there a reason to exclude Gitpod from the bold text, @loujaybee?

```suggestion
By default, most desktop VS Code installations are configured to sync settings via a GitHub or a Microsoft account. These settings are synced to Microsoft's servers and are inaccessible to third-parties, including Gitpod. Due to this limitation of access to settings stored in Microsoft servers, Gitpod implements its own VS Code Settings Sync server. **Gitpod Settings Sync is enabled by default for VS Code in the browser, but must be configured for desktop**.
```

2022-05-10 08:55 UTC, akosyakov approved these changes
LGTM 🚀

2022-05-11 11:19 UTC, loujaybee commented
@filiptronicek - will address your fixes subsequently, but will merge this change now as I want to highlight the feature in the most recently changelog (https://github.com/gitpod-io/website/pull/2000/files)

2022-05-11 11:20 UTC, merged