06.06 Changelog
gitpod-io/website pull request #2184
Opened 2022-06-07 06:15 UTC by Cahllagerfeld

Adds a new Changelog

2022-06-08 09:01 UTC, atduarte requested changes
Suggestions made in line with https://gitpod.slack.com/archives/C01KGM9AW4W/p1654677957766019

2022-06-08 09:01 UTC, atduarte commented on src/lib/contents/changelog/2022-06-06.md
> +- [#10354](https://github.com/gitpod-io/gitpod/pull/10354) - [kots]: correctly escape params in installation configmap <Contributors usernames="MrSimonEmms,corneliusludmann" />
Remove

2022-06-08 09:01 UTC, atduarte commented on src/lib/contents/changelog/2022-06-06.md
> +- [#10339](https://github.com/gitpod-io/gitpod/pull/10339) - [ws-daemon] Use a metric for backup waiting time instead of logs <Contributors usernames="aledbf,csweichel" />
Remove

2022-06-08 11:54 UTC, loujaybee commented on src/lib/contents/changelog/2022-06-06.md
> +
**Dotfiles** - Roadmap issue: [#5198](https://github.com/gitpod-io/gitpod/issues/5198) <Badge text="alpha" variant="pink" class="ml-1.5 bg-salmon" />

- [#10398](https://github.com/gitpod-io/gitpod/pull/10398) - Support for dotfiles is now generally available <Contributors usernames="easyCZ,gtsiolis,loujaybee" />

2022-06-08 11:54 UTC, loujaybee commented on src/lib/contents/changelog/2022-06-06.md
> +- [#10398](https://github.com/gitpod-io/gitpod/pull/10398) - Support for dotfiles has moved out of beta and is now generally available <Contributors usernames="easyCZ,gtsiolis,loujaybee" />
Moved to feature

2022-06-08 11:58 UTC, loujaybee commented on src/lib/contents/changelog/2022-06-06.md
> +- [#10388](https://github.com/gitpod-io/gitpod/pull/10388) - Gitpod CLI has a new command to list the ports from the workspace: gp ports list <Contributors usernames="andreafalzetti,felladrin,mustard
Added above. 

```suggestion
```

2022-06-08 12:01 UTC, loujaybee commented on src/lib/contents/changelog/2022-06-06.md
> +- [#10107](https://github.com/gitpod-io/gitpod/pull/10107) - [JetBrains] Show notification when port becomes available <Contributors usernames="akosyakov,andreafalzetti,mustard-mh" />
Mentioned above 

```suggestion
```

2022-06-08 12:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-06-06.md
> +- [#10291](https://github.com/gitpod-io/gitpod/pull/10291) - SSH Gateway support remote port forward <Contributors usernames="akosyakov,iQQBot,mustard-mh,sagor999" />
Moved above. 

```suggestion
```

2022-06-09 15:19 UTC, gtsiolis commented
@Cahllagerfeld I've updated the header image per [relevant discussion](https://gitpod.slack.com/archives/C022HAT0H5Z/p1654705726700599?thread_ts=1654582691.284399&cid=C022HAT0H5Z) (internal).

| BEFORE | AFTER |
|-|-|
| ![3000-gitpodio-website-s5j1f8zvej0 ws-eu47 gitpod io_changelog](https://user-images.githubusercontent.com/120486/172883182-f098fd21-dd01-4b5b-a64d-ac1d281713e3.png) | ![3000-gitpodio-website-5u7tmxjumst ws-eu47 gitpod io_changelog](https://user-images.githubusercontent.com/120486/172883187-05334012-bf3a-45e3-ad76-3a86531cc6be.png) |

2022-06-09 15:26 UTC, merged