blog: devxconf 2022 wrap
gitpod-io/website pull request #2236
Opened 2022-06-14 05:20 UTC by ghuntley

## Description

A blog post that wraps up the DevX Conf and shares updates on how funding is being distributed.

## Release Notes

```release-note
NONE
```

2022-06-14 05:20 UTC, ghuntley commented on src/routes/blog/devxconf-2022-wrap.md
> +[Last year](https://www.gitpod.io/blog/devxconf-wrap) was the first year of the DevX Conference, and we saw <b>TBA: attendees</b>. Over $10,000 USD was donated to unpaid volunteers and the maintainer
🎗 correct this line before merging `<b>TBA: attendees</b>`

2022-06-14 07:59 UTC, Cahllagerfeld approved these changes
From the techincal side it looks good to me 🚀

2022-06-14 20:52 UTC, MichaelAring commented
**Title**
Current: 

- "DevX Conf wrap and distributing USD $22,600 to Open-source projects"

Ideas:

- "Gitpod raises $22,600 at DevX Conf to give to Open-source maintainers"
- "We raised $22,600 at DevX Conf to give to Open-source projects you voted for"
- "Why we are giving all of the sponsor money from DevX Conf to Open-source projects"
- "Giving all of the sponsor money from DevX Conf to Open-source projects"
- "Giving $22,600 raised from DevX Conf sponsors to Open-source projects"
- "Based on your votes, we are distributing over $22,000 to Open-source projects"

2022-06-14 21:09 UTC, MichaelAring requested changes
Comments and changes

See also my comment in Slack on potentially splitting the article

2022-06-14 21:09 UTC, MichaelAring commented on src/routes/blog/devxconf-2022-wrap.md
> +At Gitpod, we often wonder what the future would look like if these high achievers that our digital society is built upon were empowered to become independent artists. If just one of those people can
Our way of speaking should be more solution-oriented, a bit less problem-oriented :)

I suggest this narrative:

- We acknowledge the importance of these projects
- We are aware they are underfunded and there is a lack of suitable reward mechanisms in the industry
- Therefore, we want to contribute by raising money at DevX Conf and giving it back to the community
- We know it is just a small step
- We will continue to this (and more of it) in the future

2022-06-15 05:39 UTC, Siddhant-K-code approved these changes

2022-06-15 05:39 UTC, Siddhant-K-code commented on src/routes/blog/devxconf-2022-wrap.md
> +title: Gitpod raises $22,600 at DevX Conf to give to Open-source maintainers
This title looks good 🎉

2022-06-15 05:41 UTC, Siddhant-K-code requested changes

2022-06-15 05:41 UTC, Siddhant-K-code commented on src/routes/blog/devxconf-2022-wrap.md
> +  export const prerender = true;x
```suggestion
  export const prerender = true;
```

nit fix ReferenceError

2022-06-15 15:45 UTC, MichaelAring commented
With these latest changes reviewed and approved, I think we are ready to merge @ghuntley 👍

2022-06-15 16:35 UTC, Siddhant-K-code commented on src/routes/blog/devxconf-2022-wrap.md
> +author: ghuntley
@MichaelAring i think it should be this: 

```suggestion
author: ghuntley, MichaelAring
```

2022-06-16 02:05 UTC, merged