add contact form for self-hosted community license.
gitpod-io/website pull request #2237
Opened 2022-06-14 07:21 UTC by nisarhassan12

Fixes #2192

2022-06-14 12:33 UTC, chrifro commented
Thanks @nisarhassan12 

Some comments:

- [ ] remove the country field from the form as Philipp suggested

- [ ] show automatically to the top of the confirmation page after sending the form. Currently I need to scroll up to see it
<img width="1493" alt="Bildschirmfoto 2022-06-14 um 14 27 41" src="https://user-images.githubusercontent.com/46345125/173577159-6f6950fa-a042-46a2-baaa-8e3c94e4392e.png">

- [ ] Can we add "others" to the infrastructure options or alternatively have it as an optional field? cc @phimae 

Otherwise it LGTM ✨

Where is the email currently sent to?

2022-06-15 02:38 UTC, nisarhassan12 commented
@chrifro The email is currently sent to `sales@gitpod.io`

2022-06-15 08:24 UTC, chrifro approved these changes
LGTM

Let's hand it over to @lucasvaltl and @phimae to follow up on the email logic and to hit the merge button. 🙌

2022-06-15 09:06 UTC, lucasvaltl requested changes
Just have a small wording change that I think would make it more clear what happens next and also what to do if you would like to install in an air gapped environment.

2022-06-15 13:56 UTC, phimae commented on src/routes/community-license.svelte
> +    <p>Fill out the form and receive the free self-hosted community license.</p>
That makes sense @lucasvaltl. To reduce salesyness and shorten we could do this wording:

H1: Receive the free community license via email
H2: Fill out the form and immediately receive the free self-hosted community license via email. If you require support for air gapped environments, please [request an enterprise license](https://www.gitpod.io/enterprise-license) to get a free trial. (like Lucas suggested)

2022-06-15 16:09 UTC, nisarhassan12 commented on src/routes/community-license.svelte
> +    <p>Fill out the form and receive the free self-hosted community license.</p>
I have updated the text.

2022-06-15 21:22 UTC, phimae commented
@nisarhassan12 thanks for the quick PR! A few comments: 

- [ ] can you make it so that when the form is submitted, it creates a row with the response in [this sheet](https://docs.google.com/spreadsheets/d/1FDeP3Y1Fg__SqDOUzedmC4SzM1qg0o7YLuTI3kkaHrc/edit#gid=0)? The email can still be sent to the alias like it does atm.
- [ ] copying over from Lucas's thread: can you change the wording in the header and sub header to:
- H1: Receive the free community license via email
- H2: Fill out the form and immediately receive the free self-hosted community license via email. If you require support for air gapped environments, please [request an enterprise license](https://www.gitpod.io/enterprise-license) to get a free trial.

- Regarding Christin's suggestion for adding other infradtructures: @lucasvaltl do you think that is helpful given that we currently don't support others? Maybe to gauge appetite?

2022-06-16 09:29 UTC, phimae approved these changes

2022-06-16 09:29 UTC, phimae commented on src/routes/community-license.svelte
> +      an air gapped environment, please request an
@nisarhassan12 this is doubled - can you pls remove the second part here?

2022-06-16 09:29 UTC, phimae commented on src/routes/community-license.svelte
> +            label="I consent to having this website store my submitted information so that the sales team can respond to my inquiry."
can you pls replace "the sales team" with "the Gitpod team"?

2022-06-18 10:48 UTC, merged