[kots]: add documentation on how to customize annotation, labels, envvars
gitpod-io/website pull request #2316
Opened 2022-06-27 15:35 UTC by MrSimonEmms

## Description

Document the customization process

## Related Issue(s)

Fixes https://github.com/gitpod-io/gitpod/issues/10941

## How to test

Follow documentation

## Release Notes

```release-note
[kots]: add documentation on how to customize annotation, labels, envvars
```

## Documentation

2022-06-27 16:50 UTC, lucasvaltl requested changes
Overall LGTM, just a couple smaller things to note.

2022-06-28 12:45 UTC, MrSimonEmms commented on gitpod/docs/self-hosted/latest/advanced/customization.md
> +> **NOTE:** Your Gitpod installation may be inaccessible and unstable whilst this process takes place.
Yeah, it's a bit unclear. I'm going to rewrite this section

2022-07-01 07:43 UTC, Siddhant-K-code commented on gitpod/docs/self-hosted/latest/advanced/customization.md
> +section: self-hosted/latest
will there be any `subsection` for this?

2022-07-01 08:11 UTC, MrSimonEmms commented on gitpod/docs/self-hosted/latest/advanced/customization.md
> +section: self-hosted/latest
I don't think so. I based it upon the [Air Gap](https://github.com/gitpod-io/website/blob/main/gitpod/docs/self-hosted/latest/advanced/air-gap.md) page in the advanced section

2022-07-06 12:05 UTC, lucasvaltl approved these changes
LGTM!

2022-07-06 12:07 UTC, merged