[Dummy PR] AWS  reference architecture prod - netlify preview
gitpod-io/website pull request #2324
Opened 2022-06-28 15:03 UTC by lucasvaltl

## Description
This is just a pull request to force a netlify preview to be created

## Related Issue(s)

Fixes #

## How to test

Open netilfy preview below, then go to Docs > Self-Hosted > Reference Architecture > Single-Cluster Production-Ready Reference Architecture.

## Release Notes

```release-note
NONE
```

2022-07-01 15:31 UTC, corneliusludmann commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/networking.md
> +      name: letsencrypt
@mrzarquon: To what secret does this value refer? Has this been created somewhere or will this be created automatically?

2022-07-04 15:19 UTC, meysholdt commented
I went through the PR and in general, it LGTM, but somebody with more in-depth AWS knowledge should confirm this, too. 
This I noticed:
* the "install Gitpod" section is missing for AWS.
* https://github.com/gitpod-io/website/pull/2298 adds a headless node pool to GCP. Not sure which PR should be merged first, but it would be nice if the AWS guide would get the headless node pool, too.

2022-07-11 10:07 UTC, atduarte commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
>      instanceTypes: ["m6i.xlarge"]
According to AWS, the nodes that are most similar to n2d-standard are m5a, not m6i.

2022-07-12 21:56 UTC, mikenikles commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
>      instanceTypes: ["m6i.xlarge"]
@lucasvaltl If this is a blocking change, could you please update the PR and merge it? If it's non-blocking, please merge the PR. Thanks

2022-07-14 07:59 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
>      instanceTypes: ["m6i.xlarge"]
This PR is still being reviewed, hence we should not merge it yet. Will add a `do-not-merge` label.

2022-07-14 11:05 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
>      instanceTypes: ["m6i.xlarge"]
Fwiw, according to this page m6i instances are superior to m5(d): https://aws.amazon.com/ec2/instance-types/m6i/

2022-07-14 11:11 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
>      instanceTypes: ["m6i.xlarge"]
Separate question - is there a reason that for AWS we are not recommending the same size of nodes? On GCP; its 8 vCPU for services and 16 vCPU for workspaces. On AWS it is currently only 4 vCPU for services and 8 vCPU for workspaces.

2022-07-15 23:20 UTC, adrienthebo requested changes
I typically leave longer review comments rolling up individual file level comments but I'd like to get this surfaced sooner rather than later. In short, the website generation process is stripping out backslashes and escaped newlines; this is a minor hassle because it makes it harder to view and copy commands out, but it also results in a malformed gitpod-cluster.yaml configuration. Users will be directly consuming this malformed configuration so we need to fix that before merging.

Slightly related, the current resource tags aren't consistent (`team` vs `department`), this could trip up end users because of the inconsistency. We also run the risk of tripping up ourselves because we'll create resources that look like they're owned by a different team.

I have more comments in terms of organization and snippet layout, but I'll bring them up at a later date and we can address them in a followup PR.

2022-07-15 23:20 UTC, adrienthebo commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/networking.md
> +By default Gitpod's installation in EKS will result in a classic load balancer being provisioned that you can point your DNS entries at.
Do we require that these DNS records be created manually? Our acceptance tests (see the [terraform module](https://github.com/gitpod-io/gitpod/blob/main/install/infra/terraform/tools/external-dns/main.tf) and [installer job phases](https://github.com/gitpod-io/gitpod/blob/main/.werft/installer-tests.ts#L86)) indicate that this might be useful but I don't see any references to external-dns in the EKS documentation.

2022-07-17 23:06 UTC, aledbf commented
Why don't we include dimensions about the number of workspaces per node? Or limits per node with the recommended sizes?

2022-07-17 23:06 UTC, aledbf commented
Is there a reason why we are not recommending setting limits for the workspaces?

2022-07-18 14:09 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
> +**Note on AMI Usage**
I see your point. I don't think that a lot of users will perform this customization - however I fear that if we move it below the eksctl config file, it might get missed by those that do. Let's leave it here for now and discuss moving it later :)

2022-07-18 14:23 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
> +eksctl create cluster --without-nodegroup --config-file gitpod-cluster.yaml
I agree that this is not great UX trying to fix this in the  latest commit that I am working on.

2022-07-18 15:19 UTC, mrzarquon commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/networking.md
> +By default Gitpod's installation in EKS will result in a classic load balancer being provisioned that you can point your DNS entries at.
No, it's not required, you can use external DNS if you set it up properly (eksctl can do the the service account for you). Just wasn't included because was focusing on the rest of the stack.

2022-07-18 15:47 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/database.md
> +aws ec2 authorize-security-group-ingress \
To be honest, I still could not find an example of where the backslashes or new lines are stripped away. I looked at the example you gave me in the cal we just had, and even there it is just a [very long line already in the raw file](https://github.com/gitpod-io/website/blob/origin/aws-reference-architecture-prod/gitpod/docs/self-hosted/latest/reference-architecture/_chunks/database.md?plain=1#L145). 

I do agree that we should align how we escape new lines throughout the document though - I'm happy to make that change and align things, but what should we go for? Single backslash or double? Is there a difference between Windows and Mac? I don't know what is best practice hence why I am asking - if it were up to me, I'd go for a single backslash as per [this](https://askubuntu.com/questions/1199854/why-are-there-backslash-line-breaks-on-this-apt-install-command) article.

2022-07-18 16:50 UTC, mrzarquon commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/networking.md
> +By default Gitpod's installation in EKS will result in a classic load balancer being provisioned that you can point your DNS entries at.
Let's not include external-dns in this release. This wasn't an omission, there's no written howto on setting it up specific for EKS + Calico + Gitpod, there's CDK code in the EKS guide and automation, but adding external dns feels like adding a new chapter when we can just ship it as is for now and add it in v2.

2022-07-18 16:54 UTC, mrzarquon commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/networking.md
> +      name: letsencrypt
@corneliusludmann it's the private key autogenerated by letsencrypt - you give it a name when you create the issues per their docs - https://cert-manager.io/docs/configuration/acme/

2022-07-18 18:40 UTC, adrienthebo commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/registry.md
> +ECR is currently not supported, so configuring the registry will require using an S3 bucket. You can reuse the same S3 bucket used for object storage or a separate one. The steps would be identical i
The full bucket setup instructions are provided in the object storage settings but we only briefly mention that here. We should either move the bucket setup instructions here, move the object storage setup instructions before the registry instructions, or link to the object store setup instructions directly.

2022-07-18 19:22 UTC, adrienthebo commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/storage.md
> +export AWS_ACCESS_KEY_ID=----------
Leaving these environment variables set will break further calls to AWS. We should clear these env vars out with the following:

```
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
```

2022-07-19 12:36 UTC, lucasvaltl commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/registry.md
> +ECR is currently not supported, so configuring the registry will require using an S3 bucket. You can reuse the same S3 bucket used for object storage or a separate one. The steps would be identical i
Added a link in the newest commit. Also moved the object storage section before the registry section for this purpose.

2022-07-20 03:12 UTC, adrienthebo commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/database.md
> +aws ec2 authorize-security-group-ingress \
I've seen inconsistent behavior with the escaping; everything in this PR looks well behaved and I don't want to pick on it too hard. Ideally we'll only need a single backslash; that's the convention and expected behavior. Since it's not a show stopper let's worry about this in a future PR and get this one merged. 😄

2022-07-20 03:45 UTC, adrienthebo commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
> +      - sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
I found something extremely surprising - the website produces different behavior if you copy/paste example text vs using the `copy` function. Copying and pasting the text outputs a single backslash, but using the `copy` function produces two backslashes, as expected. This is very surprising behavior but out of scope for this PR. Thanks for humoring me on this one. 🤦 

✅  ship it

2022-07-20 03:45 UTC, adrienthebo commented on gitpod/docs/self-hosted/latest/reference-architecture/_chunks/cluster.md
> +      - sed -i '/^set -o errexit/a\\nsource /etc/profile.d/bootstrap.sh' /etc/eks/bootstrap.sh
As mentioned above this appears to be a website bug but let's deal with that issue later. This is fine as-is.

2022-07-20 03:46 UTC, adrienthebo approved these changes
Rollling up the comments in the review:

Our website does surprising things with backslashes in examples that's inconsistent between copy/pasting example text, and using the `copy` function. I'm happy with this as-is, let's merge it and iterate. 🚢

2022-07-21 20:23 UTC, adrienthebo commented
I've resolved the merge conflicts against main, and since main brought in the code block backslash fixes, I've removed all of the double backslashes. I've also run through this guide in detail several times, so I'm confident that this is ready to release. We can break out smaller pull requests to address outstanding issues such as instance sizes, headless workspace node groups, external-dns, and other topics.

2022-07-22 11:32 UTC, merged