[WIP] Changelog - August
gitpod-io/website pull request #2578
Opened 2022-08-15 13:37 UTC by loujaybee

2022-08-19 08:57 UTC, akosyakov commented on src/lib/contents/changelog/2022-08.md
> +## JetBrains performance metrics
Maybe have one section `JetBrains` with `Performance metrics` and `Task terminals` subsections.

2022-08-30 08:15 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12116](https://github.com/gitpod-io/gitpod/pull/12116) - Gitpod CLI: New command `gp tasks stop <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,mustard-mh" />
@andreafalzetti what is preventing to merge https://github.com/gitpod-io/website/pull/2639?

@loujaybee this one with gp top [[1](https://github.com/gitpod-io/gitpod/pull/12338#issuecomment-1230304284)][[2](https://github.com/gitpod-io/website/pull/2653)] can be `GP Cli` section

2022-08-30 08:16 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12288](https://github.com/gitpod-io/gitpod/pull/12288) - [ssh-gateway] support rsa sha256/sha512 algorithm <Contributors usernames="MrSimonEmms,akosyakov,iQQBot,jeanp413,sagor999" />
@loujaybee this one should be `SSH` section, mentioning that we support know lates Open SSH clients

cc @iQQBot it is version 9.x?

2022-08-30 08:17 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12163](https://github.com/gitpod-io/gitpod/pull/12163) - JetBrains IDEs will use the default Java SDK version when there's no explicit configuration for it yet. <Contributors usernames="akosyakov
It can go under `JetBrains` section explain what we correctly detect and configure default JDK now

2022-08-30 08:18 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12159](https://github.com/gitpod-io/gitpod/pull/12159) - JetBrains: Display Workspace CPU/Memory usage in Backend Control Center.JetBrains: Workspaces created from repositories with tasks defined
It should go under `JetBrains` section too. I would explain that users should have a look at it, and then use the last tab to change Xmx and if it works then persist settings into `jetbrains.[product].vmoptions`

2022-08-30 08:18 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12082](https://github.com/gitpod-io/gitpod/pull/12082) - Enable allowing redirect to Desktop IDEs for all workspaces. <Contributors usernames="akosyakov,felladrin,loujaybee" />
It is VS Code Desktop improved opening flow

2022-08-30 08:19 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12159](https://github.com/gitpod-io/gitpod/pull/12159) - JetBrains: Display Workspace CPU/Memory usage in Backend Control Center.JetBrains: Workspaces created from repositories with tasks defined
Also that we know show all terminals.

2022-08-30 08:20 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12053](https://github.com/gitpod-io/gitpod/pull/12053) - JetBrains: Display Workspace CPU/Memory usage in Backend Control Center <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
it is `JetBrains performance metrics`

2022-08-30 08:20 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12052](https://github.com/gitpod-io/gitpod/pull/12052) - Gitpod CLI: Highlight current task in gp tasks list <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,jeanp413" />
Also should go under `GP cli`

2022-08-30 08:20 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11081](https://github.com/gitpod-io/gitpod/pull/11081) - All open ports from the workspace are automatically forwarded when using Latest JetBrains IDEs. <Contributors usernames="akosyakov,aledbf,
It should be removed, it is only in latest. cc @felladrin please mark next time

2022-08-30 08:21 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11900](https://github.com/gitpod-io/gitpod/pull/11900) - [code] update stable VSCode Browser to 1.70.0 <Contributors usernames="corneliusludmann,iQQBot,mustard-mh" />
I think we can remove it.

2022-08-30 08:21 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11877](https://github.com/gitpod-io/gitpod/pull/11877) - Fix in-product changelog relative URLs not working problem <Contributors usernames="MrSimonEmms,akosyakov,mustard-mh" />
We can also remove it.

2022-08-30 18:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11900](https://github.com/gitpod-io/gitpod/pull/11900) - [code] update stable VSCode Browser to 1.70.0 <Contributors usernames="corneliusludmann,iQQBot,mustard-mh" />
```suggestion
```

2022-08-30 18:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11877](https://github.com/gitpod-io/gitpod/pull/11877) - Fix in-product changelog relative URLs not working problem <Contributors usernames="MrSimonEmms,akosyakov,mustard-mh" />
```suggestion
```

2022-08-30 18:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11081](https://github.com/gitpod-io/gitpod/pull/11081) - All open ports from the workspace are automatically forwarded when using Latest JetBrains IDEs. <Contributors usernames="akosyakov,aledbf,
```suggestion
```

2022-08-30 18:58 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12116](https://github.com/gitpod-io/gitpod/pull/12116) - Gitpod CLI: New command `gp tasks stop <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,mustard-mh" />
It seems `gp top --json` is not yet deployed and documentation still pending: 

- https://github.com/gitpod-io/website/pull/2653/files

2022-08-30 19:01 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
>  - [What should I do if JetBrains Gateway and Gitpod aren’t working?](/docs/troubleshooting#what-should-i-do-if-jetbrains-gateway-and-gitpod-arent-working)
@Cahllagerfeld - Pushed this change to this PR since it'd be good to have docs as well as changelog, however if a problem I can extract to a separate PR, however the content is pretty much the same here and in the changelog.

2022-08-30 19:02 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Configuring JetBrains Gateway Networking
Dropping a level in the headers since not all these need to be children of "getting started". 

![image](https://user-images.githubusercontent.com/5528307/187520708-6e3cfefb-3d5a-4b88-a0c0-2c24588b357d.png)

2022-08-30 19:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12082](https://github.com/gitpod-io/gitpod/pull/12082) - Enable allowing redirect to Desktop IDEs for all workspaces. <Contributors usernames="akosyakov,felladrin,loujaybee" />
Added!

2022-08-30 19:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12053](https://github.com/gitpod-io/gitpod/pull/12053) - JetBrains: Display Workspace CPU/Memory usage in Backend Control Center <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
Added!

2022-08-30 19:03 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12052](https://github.com/gitpod-io/gitpod/pull/12052) - Gitpod CLI: Highlight current task in gp tasks list <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,jeanp413" />
Added!

2022-08-31 06:55 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +title: August Gitpod Release
I think we shoud put an year, there was some concern about duplicate titles cc @gtsiolis

2022-08-31 06:59 UTC, akosyakov commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Debugging Performance issues on JetBrains Gateway
I would mention that if metrics are alright, but they still experience slowness then:
- they should go to `Settings` tab and increase max heap size for JB backend
- if it helps then they can configure default max heap size in https://www.gitpod.io/docs/references/gitpod-yml#jetbrainsproductvmoptions that it is applied for each worksapce
- if their plan does not allow require increase in max heap size i.e. it goes over top of Workspace Memory limit or there too little memory left for the project itself then they should update the plan

2022-08-31 07:00 UTC, akosyakov commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Debugging Performance issues on JetBrains Gateway
fyi it is not about `JetBrains Gateway` but IDE itself, i.e. it is JetBrains Client, maybe we should put instead of each IDE page

2022-08-31 07:00 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +We've now extended the JetBrains Gatweay [Backend Control Center](https://www.jetbrains.com/help/idea/work-inside-remote-project.html#control_center) with two additional bits of information about you
we extended JetBrains backend not JetBrains Gatweay

2022-08-31 07:02 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +## gp tasks list shows your current terminal
there is also `gp tasks stop` it is already deployed, but https://github.com/gitpod-io/website/pull/2639 should be merged

2022-08-31 15:10 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +We've now extended the JetBrains Gatweay [Backend Control Center](https://www.jetbrains.com/help/idea/work-inside-remote-project.html#control_center) with two additional bits of information about you
Thoughts on just removing "Gateway", adding "client" etc seems like it might be confusing. 

```suggestion
We've now extended the JetBrains [Backend Control Center](https://www.jetbrains.com/help/idea/work-inside-remote-project.html#control_center) with two additional bits of information about your workspace: `Workspace CPU` and `Workspace Memory`. The additional performance information shown in the control center is for the node that your workspace is running on, and not the workspace itself. This information is also the same that can be found from running the command `gp top` in your workspace.
```

2022-08-31 15:36 UTC, axonasif commented
Hey @loujaybee, can PRs from `workspace-images` be added on the changelog?

2022-08-31 16:06 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Debugging Performance issues on JetBrains Gateway
This is really useful feedback, Anton 🙏 That said, I am somewhat bending some PR rules here including this docs change within the changelog PR (for simplicity). 

Would you be okay for me to push this feedback to a follow up issue? We've got an existing issue for resolving general performance issues, it's something we could incorporate within that issue: 

- https://github.com/gitpod-io/website/issues/2246#issuecomment-1233134359

2022-08-31 16:30 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +title: August Gitpod Release
Added in b5a2fc34f3a4b1fa165375f160d92be3f5b84077

2022-08-31 16:30 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +## gp tasks list shows your current terminal
Added in: b5a2fc34f3a4b1fa165375f160d92be3f5b84077, also approved related PR, indeed let's make sure that's merged before shipping this.

2022-08-31 16:31 UTC, loujaybee commented
Noting dependency on: 

- https://github.com/gitpod-io/website/pull/2639

Let's ensure that PR is merged prior.

2022-08-31 16:57 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12163](https://github.com/gitpod-io/gitpod/pull/12163) - JetBrains IDEs will use the default Java SDK version when there's no explicit configuration for it yet. <Contributors usernames="akosyakov
Added in: 8c50c1f2375363f3f79e8509670ac83343e54916

But I have some questions ([asking internally](https://gitpod.slack.com/archives/C01KGM9BH54/p1661965022653209))

2022-08-31 16:59 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +Previously, when opening a Java Workspace with JetBrains, the Gitpod IDE would select the latest SDK version as the default. This was problematic when we recently updated the Gitpod `workspace-full`
**Suggestion:** Would be good to add a note here about workspace-image versioning.

2022-08-31 18:21 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Debugging Performance issues on JetBrains Gateway
Change of plan, I'm moving this content to a separate PR to address: 

- https://github.com/gitpod-io/website/pull/2672

2022-08-31 18:24 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Debugging Performance issues on JetBrains Gateway
Updated in: f3dae4cafef7d2892d7527c15f80eef989013048

2022-08-31 18:25 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
>  - [What should I do if JetBrains Gateway and Gitpod aren’t working?](/docs/troubleshooting#what-should-i-do-if-jetbrains-gateway-and-gitpod-arent-working)
Removed in: f3dae4cafef7d2892d7527c15f80eef989013048

Content now in separate PR: 

- https://github.com/gitpod-io/website/pull/2672/files

2022-08-31 18:25 UTC, loujaybee commented on gitpod/docs/ides-and-editors/jetbrains-gateway.md
> +## Configuring JetBrains Gateway Networking
Removed in: f3dae4cafef7d2892d7527c15f80eef989013048

Content now in separate PR: 

- https://github.com/gitpod-io/website/pull/2672/files

2022-08-31 18:58 UTC, loujaybee commented
> @loujaybee For VS Code Desktop i think it also makes sense to highlight that SSH Gateway is now new default on gitpod.io If someone has issues with it then you need to reach out to us. We noticed that some users are struggling with firewalls and going to work on unblocking them next month. [[1](https://gitpod.slack.com/archives/C01KGM9BH54/p1661766230942389)] Before shifting SH installations to SSH Gateway as well.

I think this is covered now, could you double-check if needed, Anton and leave any direct comments for update?

![image](https://user-images.githubusercontent.com/5528307/187760534-bf72a4bf-2547-47ff-b6d4-72156c071948.png)

2022-08-31 18:59 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +## gp tasks list shows your current terminal
Added note on main PR body: https://github.com/gitpod-io/website/pull/2578#issuecomment-1233164333

2022-08-31 19:04 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12159](https://github.com/gitpod-io/gitpod/pull/12159) - JetBrains: Display Workspace CPU/Memory usage in Backend Control Center.JetBrains: Workspaces created from repositories with tasks defined
Should be covered in: 

- https://github.com/gitpod-io/website/pull/2672/files

2022-08-31 19:35 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12288](https://github.com/gitpod-io/gitpod/pull/12288) - [ssh-gateway] support rsa sha256/sha512 algorithm <Contributors usernames="MrSimonEmms,akosyakov,iQQBot,jeanp413,sagor999" />
Added in: c12d21d6030d6336156aebfc6b6e7956a68e78a1

2022-08-31 19:40 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +## VS Code Desktop
@jeanp413 / @filiptronicek please can you review this section?

2022-08-31 19:40 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +## JetBrains
@andreafalzetti, @felladrin can you review this section?

2022-08-31 19:40 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +## The Gitpod CLI (`gp`)
@andreafalzetti - can you review this section? 🙏

2022-08-31 19:41 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +### Improved OpenSSH compatibility and support for sha256/sha512
@iQQBot - Can you review this section? 🙏

2022-08-31 21:01 UTC, andreafalzetti commented on src/lib/contents/changelog/2022-09-01.md
> +You can now run `gp tasks stop` to stop running tasks that have been defined in your `.gitpod.yml`. You can either stop a single task with `gp tasks stop <id`, or terminate all tasks by running `gp t
```suggestion
You can now run `gp tasks stop` to stop running tasks that have been defined in your `.gitpod.yml`. You can either stop a single task with `gp tasks stop <id>`, or terminate all tasks by running `gp tasks stop --all`.
```

2022-08-31 21:01 UTC, andreafalzetti commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12116](https://github.com/gitpod-io/gitpod/pull/12116) - Gitpod CLI: New command `gp tasks stop <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,mustard-mh" />
I was just waiting for at least one approval, it has now been merged. Thanks @loujaybee :)

2022-08-31 21:06 UTC, andreafalzetti commented on src/lib/contents/changelog/2022-09-01.md
> +## JetBrains
[Changes](https://gitpod.slack.com/archives/C01KGM9BH54/p1661965500447129?thread_ts=1661965022.653209&cid=C01KGM9BH54) needed for the Java version detection, but otherwise this section LGTM

2022-08-31 21:07 UTC, andreafalzetti commented on src/lib/contents/changelog/2022-09-01.md
> +## The Gitpod CLI (`gp`)
Magnificent write-up, as always!

2022-08-31 22:43 UTC, filiptronicek commented on src/lib/contents/changelog/2022-09-01.md
> +We have been continuing to invest in our desktop editor experiences, including VS Code #[7184](https://github.com/gitpod-io/gitpod/issues/7184), with an emphasis on removing any barriers or friction
> restarting a timed out workspace

I think I missed this one, @loujaybee can you link anything about this? 

The rest summarizes well what we are trying to achieve here: stability

2022-09-01 03:13 UTC, jeanp413 commented on src/lib/contents/changelog/2022-09-01.md
> +## VS Code Desktop
LGTM

2022-09-01 06:18 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +Previously, when opening a Java Workspace with JetBrains, the Gitpod IDE would select the latest SDK version as the default. This was problematic when we recently updated the Gitpod `workspace-full`
- I would replace `.idea/misc.xml` with something like if a project does not have yet configured JDK.
- We look not only at JAVA_HOME but generally at user environments to detect properly default JDK, i.e. PATH variable and so on.

2022-09-01 06:19 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +Previously, when opening a Java Workspace with JetBrains, the Gitpod IDE would select the latest SDK version as the default. This was problematic when we recently updated the Gitpod `workspace-full`
👍 for mentioning that we ship both Java versions is workspace-full and java 11 as default

2022-09-01 06:23 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +<script>
@loujaybee can we have highlights at the top and call out to latest releases as last time 🙏 We can use highlights this time as a shortcuts for different users to find relevant sections.

<img width="902" alt="Screenshot 2022-09-01 at 08 22 21" src="https://user-images.githubusercontent.com/3082655/187845742-00356348-4406-4fca-b09f-ca892078025c.png">

2022-09-01 06:24 UTC, akosyakov commented
@loujaybee let's remove IDE commits from  `Fixes and improvements`.  We have a great write up on everything now 🙏

2022-09-01 07:58 UTC, felladrin commented on src/lib/contents/changelog/2022-09-01.md
> +Previously, when opening a Java Workspace with JetBrains, the Gitpod IDE would select the latest SDK version as the default. This was problematic when we recently updated the Gitpod `workspace-full`
**Suggestion:** replace "SDK" by "Java SDK (JDK)" because this change doesn't affect any other language SDK other than Java.

2022-09-01 08:44 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12116](https://github.com/gitpod-io/gitpod/pull/12116) - Gitpod CLI: New command `gp tasks stop <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,mustard-mh" />
Will resolve, we can put the `--json` fix into the next changelog 🙏

2022-09-01 08:55 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +<script>
Will have a go, a couple points to clarify: 

> can we have highlights at the top

To clarify, so we're on the same page: essentially a table of contents with tl;dr; for each item listed in this changelog with an anchor link to read more?

> call out to latest releases as last time 

I don't think we have any latest features mentioned directly in this changelog, do we? 

Would you like to carry through from last week e.g. the ports view in Desktop? Or are there additional "latest" features we wanted to highlight?

2022-09-01 09:24 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +<script>
VS Code added a table of contents (markdown plugin?) automatically, so I've left that in. Not sure how to configure header levels, ideally we'd just have H3's, H2's are quite verbose. Added a separate section for latest, linked ports view content from previous changelog, not sure if there's anything else we want to add here. 

![image](https://user-images.githubusercontent.com/5528307/187880032-456bedb6-cffd-47a0-a1a6-aeaa2429b9b9.png)

Let me know if you have thoughts on anything else to add (or updates), will resolve for now.  🙏

2022-09-01 09:30 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +We have been continuing to invest in our desktop editor experiences, including VS Code #[7184](https://github.com/gitpod-io/gitpod/issues/7184), with an emphasis on removing any barriers or friction
There were some issues due to the host name being dynamic (e.g. when using the access token approach for SSH) where you lost some VS Code workspace layouts, due to them being tied to the host name. 

But also when your workspace times out the access token would rotate and you'd have to re-authenticate. I think in most cases that was forcing users to go back to the dashboard and re-open the workspace rather than simply re-connecting. We now have a [section in the docs on VS Code Desktop re-connecting](https://www.gitpod.io/docs/ides-and-editors/vscode#reconnect-to-vs-code-desktop), not sure if it's worth 
documenting too much the old behaviours, but more opportunities to improve here e.g. 

- https://github.com/gitpod-io/gitpod/issues/11701
- https://github.com/gitpod-io/gitpod/issues/11263
- https://github.com/gitpod-io/gitpod/issues/7685

2022-09-01 09:31 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +title: August Gitpod Release 2022
August, or September 🤔 💭

2022-09-01 09:34 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +Previously, when opening a Java Workspace with JetBrains, the Gitpod IDE would select the latest SDK version as the default. This was problematic when we recently updated the Gitpod `workspace-full`
yes, it is only specifically for IntelliJ IDEA

2022-09-01 09:34 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +title: August Gitpod Release 2022
I think it should be August

2022-09-01 09:39 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +Previously, when opening a Java Workspace with JetBrains, the Gitpod IDE would select the latest SDK version as the default. This was problematic when we recently updated the Gitpod `workspace-full`
Ah, yes that's a great point, thank you! Updated in: d846465203ef72271153ce2cf4b43fc2d14d4227

2022-09-01 09:41 UTC, loujaybee commented
> @loujaybee let's remove IDE commits from Fixes and improvements. We have a great write up on everything now 🙏

I do think those links are still useful as a user can at least then link through and read the longer, more technical, but less user-friendly descriptions/discussions on the PR. The PR list at the bottom then acts as a "read more" if you're interested to dive deeper area? 🤔 However, I don't feel _very strongly_ about this, so if you do let me know and I'll just update.

2022-09-01 09:43 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +This was problematic when we recently updated the Gitpod `workspace-full` image, to include both Java 11 and 17, which many users rely upon. When having multiple Java SDK (JDK) versions, JetBrains wo
```suggestion
This was problematic when we recently updated the Gitpod `workspace-full` image, to include both Java 11 and 17, which many users rely upon. When having multiple Java SDK (JDK) versions, JetBrains would default to using the latest Java SDK (JDK) version, which in the case of the `workspace-full` image was 17, and not 11, causing a minor regression. Now, Gitpod respects configured Java SDK (JDK) versions in locations such as the `PATH` and `JAVA_HOME`.
```

2022-09-01 09:59 UTC, felladrin commented on src/lib/contents/changelog/2022-09-01.md
> +This was problematic when we recently updated the Gitpod `workspace-full` image, to include both Java 11 and 17, which many users rely upon. When having multiple Java SDK (JDK) versions, JetBrains wo
Thanks for the update, @loujaybee!

I think on this second paragraph we can refer to "JDK" directly, since it's been defined is on the previous one.
```suggestion
This was problematic when we recently updated the Gitpod `workspace-full` image, to include both Java 11 and 17, which many users rely upon. When having multiple JDK versions, JetBrains would default to using the latest JDK version, which in the case of the `workspace-full` image was 17, and not 11, causing a minor regression. Now, Gitpod respects configured JDK versions in locations such as the `PATH` and `JAVA_HOME`.
```

2022-09-01 13:50 UTC, atduarte requested changes

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12116](https://github.com/gitpod-io/gitpod/pull/12116) - Gitpod CLI: New command `gp tasks stop <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,mustard-mh" />
```suggestion
- [#12116](https://github.com/gitpod-io/gitpod/pull/12116) - Gitpod CLI: New command `gp tasks stop` <Contributors usernames="akosyakov,andreafalzetti,felladrin,filiptronicek,mustard-mh" />
```

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12422](https://github.com/gitpod-io/gitpod/pull/12422) - experimental: enable the feature flag PVC, the files/folders under .git/ folder user:group permission is incorrect <Contributors usernames
```suggestion
```

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#11255](https://github.com/gitpod-io/gitpod/pull/11255) - Limit the rate at which network connections can be made by a workspace <Contributors usernames="Furisto,MrSimonEmms,aledbf,geropl,jenting,
```suggestion
- [#11255](https://github.com/gitpod-io/gitpod/pull/11255) - Prevent abuse by limiting rate at which network connections can be made by a workspace <Contributors usernames="Furisto,MrSimonEmms,aledbf,geropl,jenting,kylos101,sagor999,utam0k" />
```

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12398](https://github.com/gitpod-io/gitpod/pull/12398) - [kots] load dockerConfigJson reigstry names into `privateBaseImageAllowList <Contributors usernames="MrSimonEmms,Pothulapati,lucasvaltl,na
Should this be removed and only be part of the self-hosted changelog? I don't remember what's the guideline right now.

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12417](https://github.com/gitpod-io/gitpod/pull/12417) - Upgrade runc to 1.1.4 <Contributors usernames="aledbf,utam0k" />
```suggestion
```

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12367](https://github.com/gitpod-io/gitpod/pull/12367) - More reliably connect to buildkit during image builds <Contributors usernames="jenting,utam0k" />
```suggestion
- [#12367](https://github.com/gitpod-io/gitpod/pull/12367) - Improve reliability of image build starts<Contributors usernames="jenting,utam0k" />
```

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12315](https://github.com/gitpod-io/gitpod/pull/12315) - Prevent divide by zero error in workspace info service <Contributors usernames="Furisto,jenting,kylos101,utam0k" />
Not yet deployed 😬 

How can we improve the automation to take into consideration the "deployed" label? Also how can we avoid forgetting this entry in the next changelog?

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12028](https://github.com/gitpod-io/gitpod/pull/12028) - Fixed a rare case in which prebuild was terminating successfully but failing <Contributors usernames="jenting,sagor999,utam0k" />
```suggestion
- [#12028](https://github.com/gitpod-io/gitpod/pull/12028) - Fixed a rare case in which prebuilds terminated successfully but were shown as failed <Contributors usernames="jenting,sagor999,utam0k" />
```

2022-09-01 13:50 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12280](https://github.com/gitpod-io/gitpod/pull/12280) - Update docker compose to v2.10.0 <Contributors usernames="aledbf,sagor999" />
Maybe this should be in higher evidence. More to the top of the list.

```suggestion
- [#12280](https://github.com/gitpod-io/gitpod/pull/12280) - Update docker compose from v2.8.0 to v2.10.0 <Contributors usernames="aledbf,sagor999" />
```

2022-09-01 14:21 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12398](https://github.com/gitpod-io/gitpod/pull/12398) - [kots] load dockerConfigJson reigstry names into `privateBaseImageAllowList <Contributors usernames="MrSimonEmms,Pothulapati,lucasvaltl,na
CC: @lucasvaltl

2022-09-01 14:24 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12315](https://github.com/gitpod-io/gitpod/pull/12315) - Prevent divide by zero error in workspace info service <Contributors usernames="Furisto,jenting,kylos101,utam0k" />
[This is the current script](https://github.com/gitpod-io/website/blob/main/scripts/generate-changelog.js), would need to be extended or updated, possibly. I think we should [open an issue](https://github.com/gitpod-io/website/issues/new), seems we already have a tag for changelog issues (`section: changelog`). Could be something @Cahllagerfeld and website team could help with, but until then we'll have to stick with manual verification.

2022-09-01 14:33 UTC, Siddhant-K-code commented on src/lib/contents/changelog/2022-09-01.md
> +image: 2022-09-01.jpg
What is the location of this file? I think, this is causing problem: [netlify logs](https://app.netlify.com/sites/gitpod-kumquat/deploys/6310bfee6a46420009fec569#L2401)

2022-09-01 14:39 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-01.md
> +<script>
ah, ok let's drop latest 👍

2022-09-01 14:46 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +image: 2022-09-01.jpg
Pushing a temp commit with a valid path ee738189718874a2ef280d9f3b57b73bc4f8ff69 builds for me in a workspace, should start passing 🙏 🤞

2022-09-01 14:52 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +image: 2022-08-26.jpg
**Note:** This needs updating with a new header image for this changelog.

2022-09-01 15:09 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12313](https://github.com/gitpod-io/gitpod/pull/12313) - Revert "[installer]: remove all podsecuritypolicies" #12313 <Contributors usernames="MrSimonEmms,adrienthebo,sagor999" />
Do we want to include reverts in the changelog? 🤔

2022-09-01 15:30 UTC, lucasvaltl commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12313](https://github.com/gitpod-io/gitpod/pull/12313) - Revert "[installer]: remove all podsecuritypolicies" #12313 <Contributors usernames="MrSimonEmms,adrienthebo,sagor999" />
eeeh probably not. I think you can remove the two above (#12173 and #12313), and only keep #12340 which seems to be how we solved it in the end. Context: The events seem to have been: remove, revert, add deprecation warning. Based on that I'd just keep the last one.

2022-09-01 15:49 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12315](https://github.com/gitpod-io/gitpod/pull/12315) - Prevent divide by zero error in workspace info service <Contributors usernames="Furisto,jenting,kylos101,utam0k" />
Let's remove it for now

```suggestion
```

2022-09-01 16:00 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12398](https://github.com/gitpod-io/gitpod/pull/12398) - [kots] load dockerConfigJson reigstry names into `privateBaseImageAllowList <Contributors usernames="MrSimonEmms,Pothulapati,lucasvaltl,na
Removed 🙏

2022-09-01 16:01 UTC, atduarte approved these changes

2022-09-01 16:01 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +image: 2022-08-26.jpg
Added in: abdfb46d965f52147388c592f11008e285a4c71a

2022-09-01 16:02 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12313](https://github.com/gitpod-io/gitpod/pull/12313) - Revert "[installer]: remove all podsecuritypolicies" #12313 <Contributors usernames="MrSimonEmms,adrienthebo,sagor999" />
@atduarte has got it, looks like: 71e8eadb57be815e9ab0ff060ce1f52ffa7ee7a6 😄

2022-09-01 16:04 UTC, atduarte commented on src/lib/contents/changelog/2022-09-01.md
> +- [#12313](https://github.com/gitpod-io/gitpod/pull/12313) - Revert "[installer]: remove all podsecuritypolicies" #12313 <Contributors usernames="MrSimonEmms,adrienthebo,sagor999" />
It was also about the installer so :P

2022-09-01 17:11 UTC, merged