create vs coder page.
gitpod-io/website pull request #2601
Opened 2022-08-19 18:27 UTC by nisarhassan12

Fixes #2540

2022-08-20 06:49 UTC, Siddhant-K-code commented on src/routes/vs/coder.svelte
> +    href="/#try-now"
Is it intentional? that, First Button of `Try Now` redirects to `/#try-now`(on the homepage) while the other button (below) redirects to `/workspaces`

2022-08-22 17:25 UTC, nisarhassan12 commented on src/routes/vs/coder.svelte
> +    href="/#try-now"
Great catch Siddhant. Thanks for bringing this up :+1:

2022-08-23 12:12 UTC, nisarhassan12 commented
@Siddhant-K-code I have not implemented the grouping of rows within this Pr yet because that will make the Pr huge so I have opened a follow-up issue for that https://github.com/gitpod-io/website/issues/2614

2022-08-23 12:20 UTC, Siddhant-K-code commented
Yeah sure. I'll review this by EOD

2022-08-23 17:29 UTC, Siddhant-K-code requested changes

2022-08-23 17:29 UTC, Siddhant-K-code commented on src/lib/contents/coder.ts
> +      text: "Pricing Saas",
```suggestion
      text: "Pricing (SaaS)",
```

2022-08-23 17:29 UTC, Siddhant-K-code commented on src/lib/contents/coder.ts
> +          term: "Pricing Saas",
```suggestion
          term: "Pricing (SaaS)",
```

2022-08-23 17:29 UTC, Siddhant-K-code commented on src/lib/contents/coder.ts
> +          term: "Pricing Saas",
I know, it won't be visible to the user. But, it should be consistent across the site.

```suggestion
          term: "Pricing (SaaS)",
```

2022-08-23 17:29 UTC, Siddhant-K-code commented on src/lib/contents/coder.ts
> +      text: "Pricing Self-hosted",
```suggestion
      text: "Pricing (Self-hosted)",
```

2022-08-23 17:29 UTC, Siddhant-K-code commented on src/lib/contents/coder.ts
> +        },
Extra Pair of ✔️ ❌

![image](https://user-images.githubusercontent.com/55068936/186225175-668d8aab-9bc7-49e2-9eae-90c5a4e03bda.png)

2022-08-23 20:26 UTC, Siddhant-K-code approved these changes
LGTM ✨ 
Thanks 🧡

2022-08-23 20:28 UTC, merged