September Changelog
gitpod-io/website pull request #2760
Opened 2022-09-20 09:54 UTC by loujaybee

> **Note** Only make changes to this PR to add ad-hoc changelog content, the automated list will be re-generated. To update the changelog list of items, update the release notes section on your PR directly. To omit, simply add `NONE` to the release notes field. 

Script for re-generating: `node scripts/generate-changelog.js 2022-09-30 2022-09-01 2022-09-30`

2022-09-26 15:36 UTC, filiptronicek commented on src/lib/contents/changelog/2022-09-30.md
> +- [#12621](https://github.com/gitpod-io/gitpod/pull/12621) - JetBrains IDEs now have actions related to Gitpod, which can be accessed via Control Center and via the Search Menu. <Contributors usernam
```suggestion
- [#13186](https://github.com/gitpod-io/gitpod/pull/13186) - Restrict reuse of phone numbers for verification <Contributors usernames="atduarte,easyCZ,svenefftinge" />
- [#13203](https://github.com/gitpod-io/gitpod/pull/13203) - [server]: Add a liveness probe which fails when the nodejs event loop lag exceeds a certain threshold <Contributors usernames="andrew-farries,easyCZ" />
- [#13080](https://github.com/gitpod-io/gitpod/pull/13080) - JetBrains Gateway: Avoid 30 seconds delay when connecting to a workspace using an expired token <Contributors usernames="andreafalzetti,felladrin" />
- [#13161](https://github.com/gitpod-io/gitpod/pull/13161) - Admin dashboard now has pagination <Contributors usernames="easyCZ,geropl,svenefftinge" />
- [#13108](https://github.com/gitpod-io/gitpod/pull/13108) - Fix reading .gitpod.yml for self-managed GHE instances. <Contributors usernames="AlexTugarev,geropl" />
- [#13065](https://github.com/gitpod-io/gitpod/pull/13065) - Added a usage view that displays past workspace sessions on individual and team accounts. <Contributors usernames="easyCZ,jldec,svenefftinge" />
- [#13084](https://github.com/gitpod-io/gitpod/pull/13084) - Update GoLand IDE image to version 222.4167.25. <Contributors usernames="felladrin" />
- [#13057](https://github.com/gitpod-io/gitpod/pull/13057) - improved automated code configuration service for `go` <Contributors usernames="Siddhant-K-code,svenefftinge" />
- [#13001](https://github.com/gitpod-io/gitpod/pull/13001) - Update GitLab API library, which fixes paginated API requests. <Contributors usernames="AlexTugarev,gtsiolis,metcalfc,svenefftinge" />
- [#13033](https://github.com/gitpod-io/gitpod/pull/13033) - Update PhpStorm IDE image to version 222.4167.33. <Contributors usernames="felladrin" />
- [#13032](https://github.com/gitpod-io/gitpod/pull/13032) - Update PyCharm IDE image to version 222.4167.33. <Contributors usernames="felladrin" />
- [#12670](https://github.com/gitpod-io/gitpod/pull/12670) - Dismiss Usage Limit notifications automatically. <Contributors usernames="AlexTugarev,geropl,jldec,svenefftinge" />
- [#12994](https://github.com/gitpod-io/gitpod/pull/12994) - Update IntelliJ IDEA IDE image to version 222.4167.29. <Contributors usernames="felladrin" />
- [#12412](https://github.com/gitpod-io/gitpod/pull/12412) - Add beta notice and label on usage <Contributors usernames="easyCZ,filiptronicek,gtsiolis,laushinka" />
- [#12852](https://github.com/gitpod-io/gitpod/pull/12852) - Add link to support on phone verification <Contributors usernames="gtsiolis,svenefftinge" />
- [#12833](https://github.com/gitpod-io/gitpod/pull/12833) - Improve fetching repositories loading state <Contributors usernames="gtsiolis,svenefftinge" />
- [#12771](https://github.com/gitpod-io/gitpod/pull/12771) - Show personal Usage page. <Contributors usernames="AlexTugarev,andrew-farries" />
- [#12621](https://github.com/gitpod-io/gitpod/pull/12621) - JetBrains IDEs now have actions related to Gitpod, which can be accessed via Control Center and via the Search Menu. <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
- [#12669](https://github.com/gitpod-io/gitpod/pull/12669) - Reword "Spending Limit" to "Usage Limit" <Contributors usernames="AlexTugarev,andrew-farries,jldec" />
- [#12568](https://github.com/gitpod-io/gitpod/pull/12568) - JetBrains: Provide workspace class info in Backend Control Center <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
- [#12232](https://github.com/gitpod-io/gitpod/pull/12232) - Fixed JetBrains connection loop when connecting twice to the same workspace <Contributors usernames="akosyakov,andreafalzetti,felladrin" />

```

2022-09-26 15:56 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-30.md
> +- [#12621](https://github.com/gitpod-io/gitpod/pull/12621) - JetBrains IDEs now have actions related to Gitpod, which can be accessed via Control Center and via the Search Menu. <Contributors usernam
Update based on: https://github.com/gitpod-io/website/pull/2759/files adjusted script

2022-09-27 07:48 UTC, akosyakov commented
#### JetBrains:
  - displaying information about workspace classes in the backend control center, separating infor about workpace from node
    - we could highlight what is the difference
  - standard actions in the backend control center, like extend timeout, stop workspace, docs, and so on

#### VS Code:
  - New ports panel now is default in VS Code Browser
  - VS Code Desktop is approaching GA, support of installing local extensions, fixed port auto detection and expose ports view aligned with new ports panel in VS Code Browser
    - it depends on landing https://github.com/gitpod-io/openvscode-server/pull/440 before Changelog, but after SH release cc @jeanp413 
    - should be highlight usability study?
  - SSH Gateway is default now for all users in VS Code Desktop, ping SH installations to enable SSH Gateway

2022-09-27 21:32 UTC, loujaybee commented
😍 - Thanks so much @akosyakov, I've updated the PR description with your suggestions (to track)

> displaying information about workspace classes in the backend control center, separating infor about workpace from node - @akosyakov 

Added information here. Also mentioned the workspace classes work, and would be good to get @atduarte's feedback on it. 

> VS Code Desktop is approaching GA, support of installing local extensions, fixed port auto detection and expose ports view aligned with new ports panel in VS Code Browser it depends on landing https://github.com/gitpod-io/openvscode-server/pull/440 - @akosyakov 

Let's see how @jeanp413 gets on, we've got a lot for this changelog. We could do a push on VS Code Desktop GA next month? 

> should be highlight usability study? - @akosyakov 

🤔 - Not sure, I'm err'ing to no, but I'll think it! 

> SSH Gateway is default now for all users in VS Code Desktop, ping SH installations to enable SSH Gateway - @akosyakov 

Hrm, this might make more sense in the Self-Hosted release, I'll ask @lucasvaltl about this 🙏

2022-09-28 09:58 UTC, akosyakov commented on src/lib/contents/changelog/2022-09-30.md
> +### JetBrains Backend Control Center - Common Actions
I wonder whether we could find better name than `Common`? Maybe `Gitpod Workspace Actions`?

2022-09-28 10:02 UTC, akosyakov approved these changes
LGTM from IDE side

There seem to be some improvements from webapp side in commits section at the bottom. Maybe we could collaborate to help adding them as well?

2022-09-28 10:42 UTC, atduarte commented on src/lib/contents/changelog/2022-09-30.md
> +Did you know that when you're working with JetBrains IDEs in Gitpod you can [see real-time the performance of your workspace](/docs/ides-and-editors/intellij#workspace-performance) via the JetBrains
```suggestion
Did you know that when you're working with JetBrains IDEs in Gitpod you can [monitor the performance of your workspace in real-time](/docs/ides-and-editors/intellij#workspace-performance) via the JetBrains Backend Control Center? This feature is useful when your workspace isn't performing as you'd expect and you want to gather more information. In addition to our recent additions of `Workspace CPU` and `Workspace Memory` we've now added the actual workspace class to the information shown in the control center.
```

2022-09-28 10:42 UTC, atduarte commented on src/lib/contents/changelog/2022-09-30.md
> +... but why? When you work in a cloud developer environment, you should have the flexibility to choose the right performance profile for your project. Recently we've been working to bring to Gitpod a
```suggestion
... but why? When you work in a cloud developer environment, you should have the flexibility to choose the right performance profile for your project. Recently we've been working to bring to Gitpod a feature we call "Workspaces Classes" [#8261](https://github.com/gitpod-io/gitpod/issues/8261). With Workspaces Classes you'll be able to select workspace specifications that better match your use case. For example, you will be able to get more powerful workspaces to run larger Java projects and IntelliJ.
```

2022-09-28 10:42 UTC, atduarte commented on src/lib/contents/changelog/2022-09-30.md
> +- [#13186](https://github.com/gitpod-io/gitpod/pull/13186) - Restrict reuse of phone numbers for verification <Contributors usernames="atduarte,easyCZ,svenefftinge" />
@loujaybee order of contributors seems borked 🤔 Not problematic, but something to note

2022-09-28 18:07 UTC, filiptronicek commented on src/lib/contents/changelog/2022-09-30.md
> +- [#13186](https://github.com/gitpod-io/gitpod/pull/13186) - Restrict reuse of phone numbers for verification <Contributors usernames="atduarte,easyCZ,svenefftinge" />
@atduarte from what I saw it's just ordered alphabetically, I think this is fine as long as the actual PR author is the first one unrelated to their alphabetical order in the list, will incorporate that into https://github.com/gitpod-io/website/pull/2763 🧡.

2022-09-28 20:23 UTC, filiptronicek commented on src/lib/contents/changelog/2022-09-30.md
> +- [#12232](https://github.com/gitpod-io/gitpod/pull/12232) - Fixed JetBrains connection loop when connecting twice to the same workspace <Contributors usernames="akosyakov,andreafalzetti,felladrin" /
Here are the latest updates (cc @loujaybee):
```suggestion
- [#13322](https://github.com/gitpod-io/gitpod/pull/13322) - Fix issue that sporadically prevented workspaces to be opened from a GitHub issue <Contributors usernames="aledbf,atduarte,jenting,utam0k" />
- [#13144](https://github.com/gitpod-io/gitpod/pull/13144) - Enable configuration of core dump behavior in a workspace <Contributors usernames="Furisto,aledbf,csweichel,david-bakin,svenefftinge,utam0k" />
- [#13053](https://github.com/gitpod-io/gitpod/pull/13053) - Do not check all existing git branches during the initial checkout <Contributors usernames="aledbf,jenting,kylos101,sagor999,utam0k" />
- [#13205](https://github.com/gitpod-io/gitpod/pull/13205) - JetBrains: VM options to install plugins <Contributors usernames="akosyakov,andreafalzetti,filiptronicek,subinamathew" />
- [#12445](https://github.com/gitpod-io/gitpod/pull/12445) - Support for storing VS Code edit sessions in sync server <Contributors usernames="akosyakov,andrew-farries,filiptronicek,jeanp413,mustard-mh" />
- [#13295](https://github.com/gitpod-io/gitpod/pull/13295) - Avoid second prebuild been triggered on same commit. <Contributors usernames="AlexTugarev,geropl" />
- [#13296](https://github.com/gitpod-io/gitpod/pull/13296) - Fail prebuild if image build fails. <Contributors usernames="AlexTugarev,easyCZ" />
- [#13186](https://github.com/gitpod-io/gitpod/pull/13186) - Restrict reuse of phone numbers for verification <Contributors usernames="atduarte,easyCZ,svenefftinge" />
- [#13203](https://github.com/gitpod-io/gitpod/pull/13203) - [server]: Add a liveness probe which fails when the nodejs event loop lag exceeds a certain threshold <Contributors usernames="andrew-farries,easyCZ" />
- [#13080](https://github.com/gitpod-io/gitpod/pull/13080) - JetBrains Gateway: Avoid 30 seconds delay when connecting to a workspace using an expired token <Contributors usernames="andreafalzetti,felladrin" />
- [#13161](https://github.com/gitpod-io/gitpod/pull/13161) - Admin dashboard now has pagination <Contributors usernames="easyCZ,geropl,svenefftinge" />
- [#13108](https://github.com/gitpod-io/gitpod/pull/13108) - Fix reading .gitpod.yml for self-managed GHE instances. <Contributors usernames="AlexTugarev,geropl" />
- [#13065](https://github.com/gitpod-io/gitpod/pull/13065) - Added a usage view that displays past workspace sessions on individual and team accounts. <Contributors usernames="easyCZ,jldec,svenefftinge" />
- [#13084](https://github.com/gitpod-io/gitpod/pull/13084) - Update GoLand IDE image to version 222.4167.25. <Contributors usernames="felladrin" />
- [#13057](https://github.com/gitpod-io/gitpod/pull/13057) - improved automated code configuration service for `go` <Contributors usernames="Siddhant-K-code,svenefftinge" />
- [#13001](https://github.com/gitpod-io/gitpod/pull/13001) - Update GitLab API library, which fixes paginated API requests. <Contributors usernames="AlexTugarev,gtsiolis,metcalfc,svenefftinge" />
- [#13033](https://github.com/gitpod-io/gitpod/pull/13033) - Update PhpStorm IDE image to version 222.4167.33. <Contributors usernames="felladrin" />
- [#13032](https://github.com/gitpod-io/gitpod/pull/13032) - Update PyCharm IDE image to version 222.4167.33. <Contributors usernames="felladrin" />
- [#12670](https://github.com/gitpod-io/gitpod/pull/12670) - Dismiss Usage Limit notifications automatically. <Contributors usernames="AlexTugarev,geropl,jldec,svenefftinge" />
- [#12994](https://github.com/gitpod-io/gitpod/pull/12994) - Update IntelliJ IDEA IDE image to version 222.4167.29. <Contributors usernames="felladrin" />
- [#12412](https://github.com/gitpod-io/gitpod/pull/12412) - Add beta notice and label on usage <Contributors usernames="easyCZ,filiptronicek,gtsiolis,laushinka" />
- [#12852](https://github.com/gitpod-io/gitpod/pull/12852) - Add link to support on phone verification <Contributors usernames="gtsiolis,svenefftinge" />
- [#12833](https://github.com/gitpod-io/gitpod/pull/12833) - Improve fetching repositories loading state <Contributors usernames="gtsiolis,svenefftinge" />
- [#12771](https://github.com/gitpod-io/gitpod/pull/12771) - Show personal Usage page. <Contributors usernames="AlexTugarev,andrew-farries" />
- [#12621](https://github.com/gitpod-io/gitpod/pull/12621) - JetBrains IDEs now have actions related to Gitpod, which can be accessed via Control Center and via the Search Menu. <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
- [#12669](https://github.com/gitpod-io/gitpod/pull/12669) - Reword "Spending Limit" to "Usage Limit" <Contributors usernames="AlexTugarev,andrew-farries,jldec" />
- [#12568](https://github.com/gitpod-io/gitpod/pull/12568) - JetBrains: Provide workspace class info in Backend Control Center <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
- [#12232](https://github.com/gitpod-io/gitpod/pull/12232) - Fixed JetBrains connection loop when connecting twice to the same workspace <Contributors usernames="akosyakov,andreafalzetti,felladrin" />
```

P.S.: I removed the long release note from https://github.com/gitpod-io/gitpod/pull/13205 - I think before we figure out the multiline changelog entries, we should add these manually to their manually curated subsections.

2022-09-29 19:27 UTC, jldec approved these changes
LGTM thanks. 🙏🏽

2022-09-29 19:45 UTC, atduarte commented
Fixes and improvements list needs to be regenerated. Not sure I can run it myself 🤔

2022-09-29 20:27 UTC, filiptronicek commented
> Fixes and improvements list needs to be regenerated. Not sure I can run it myself 🤔

Just done that, updated the list in my code suggestion from yesterday,.

2022-09-30 07:16 UTC, akosyakov commented
@loujaybee @lucasvaltl for air-gapped SH this one is important: https://github.com/gitpod-io/gitpod/pull/13205 Maybe better for SH changelog.

2022-09-30 09:44 UTC, atduarte requested changes
Image should contain new key highlights introduced yesterday:
- Configurable core dump behavior
- Faster startup times

Also there are a couple of TODOs left.

2022-09-30 12:16 UTC, loujaybee commented
> Image should contain new key highlights introduced yesterday:

Which image are you referring to here, @atduarte ? Not sure I follow. 

> Also there are a couple of TODOs left.

Looking now!

2022-09-30 12:20 UTC, atduarte commented
> Which image are you referring to here, @atduarte ? Not sure I follow.
@loujaybee Oops, forgot to include the reference: `static/images/changelog/2022-09-30/open-graph.jpg`

2022-09-30 12:33 UTC, jacobparis commented
> > Which image are you referring to here, @atduarte ? Not sure I follow.
> > @loujaybee Oops, forgot to include the reference: `static/images/changelog/2022-09-30/open-graph.jpg`

I will take this

2022-09-30 12:42 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-30.md
> +<!-- TODO: Any insiders notes to highlight? -->
```suggestion
```

2022-09-30 12:42 UTC, jacobparis commented
There were some broken links to the docs that were breaking compilation (redirects were set but compile doesn't fix), I've pushed a commit to fix those

2022-09-30 12:43 UTC, Cahllagerfeld commented
There's still a todo for updating the regular image @loujaybee. Is this still relevant? If yes, do you have something particular in mind already?

2022-09-30 12:48 UTC, jacobparis commented
Is this the final list of changes to include in the social share image?

<img width="681" alt="image" src="https://user-images.githubusercontent.com/5633704/193273020-0d70c51b-b2ac-4b92-bf4e-f27f48610745.png">

2022-09-30 12:48 UTC, jacobparis commented
why is CMD+Enter close and comment, that's never what I want

2022-09-30 12:55 UTC, loujaybee commented
- Moved all images in repo
- Updated alt descriptions
- Added image captions

2022-09-30 12:57 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-30.md
> +---
We should delete the old copied image: `static/images/changelog/2022-09-30.png` also. 

This open graph image is not showing for me? @jacobparis 

```suggestion
---
title: September Gitpod Release 2022
excerpt:
date: 2022-09-30
image: 2022-09-30/open-graph.jpg
alt:
---
```

2022-09-30 12:58 UTC, Cahllagerfeld commented on src/lib/contents/changelog/2022-09-30.md
> +---
It's not on gitpod.io yet. There's a bug with sveltest that we can't display it dynamically. I tested it in my preview though.

2022-09-30 12:59 UTC, loujaybee commented
> Is this the final list of changes to include in the social share image? - @jacobparis 

I think needs to be updated, as we updated the title so it's no longer "common actions". 

Can we resync with the table of contents?

2022-09-30 13:02 UTC, Cahllagerfeld commented on src/lib/contents/changelog/2022-09-30.md
> +---
Do we want to put the OpenGraph-Image (or the same style of image) as the header image?

2022-09-30 13:08 UTC, atduarte commented on src/lib/contents/changelog/2022-09-30.md
> +image: 2022-09-30.png
Colors seem muted. Particularly the Gitpod logo. Is this on purpose?

2022-09-30 13:17 UTC, loujaybee commented on src/lib/contents/changelog/2022-09-30.md
> +image: 2022-09-30.png
I'm a little confused, I thought we would swap for [this image](https://github.com/gitpod-io/website/pull/2760#issuecomment-1263531785). The one here is just a placeholder copied from the previous changelog earlier on so the build would pass. 

See also: https://github.com/gitpod-io/website/pull/2760#discussion_r984565307

2022-09-30 13:17 UTC, jacobparis commented on src/lib/contents/changelog/2022-09-30.md
> +---
No the open graph image is distinct from the header image

2022-09-30 13:52 UTC, jacobparis commented on src/lib/contents/changelog/2022-09-30.md
> +---
> There's a bug with Sveltekit that we can't display it dynamically. I tested it in my preview though.

Not a bug, we just can't statically generate pages that include URLs before we know what URL we're going to be deploying it to. Serverside rendering is ideal here

2022-09-30 14:53 UTC, jacobparis approved these changes

2022-09-30 15:32 UTC, atduarte commented
<img width="509" alt="image" src="https://user-images.githubusercontent.com/666176/193305334-9ffee0cb-2e27-47a0-bb29-f9412090df7a.png">

Nit: Where can we add this description, like we had in August?

2022-09-30 15:32 UTC, atduarte approved these changes

2022-09-30 15:34 UTC, Cahllagerfeld commented
Let me check @atduarte

2022-09-30 15:43 UTC, Siddhant-K-code commented on src/lib/contents/changelog/2022-09-30.md
> +excerpt:
Fill `excerpt` to resolve [this](https://github.com/gitpod-io/website/pull/2760#issuecomment-1263723240)

2022-09-30 15:45 UTC, Cahllagerfeld commented on src/lib/contents/changelog/2022-09-30.md
> +excerpt: The latest Gitpod updates for September 2022, including improvements for JetBrains, improving the startup times for large repos and lots of other fixes and improvements.
I added an excerpt here @atduarte, feel free to adjust it!

2022-09-30 16:10 UTC, atduarte commented on src/lib/contents/changelog/2022-09-30.md
> +excerpt: The latest Gitpod updates for September 2022, including improvements for JetBrains, improving the startup times for large repos and lots of other fixes and improvements.
Thank you, @Cahllagerfeld! Looks great

2022-09-30 16:48 UTC, loujaybee commented
If I could approve my own PR, I would ☑️

Good hustle, team! 🚀

2022-09-30 16:49 UTC, merged