Prevent workspace starts during Gitpod update for single cluster ref arch
gitpod-io/website pull request #2777
Opened 2022-09-23 06:52 UTC by kylos101

## Description

If we do not recommend this, and there are running workspaces when Gitpod is updated, users could incur data loss.

## Related Issue(s)

Fixes # n/a

## How to test

* Stop running workspaces
* Scale-down ws-manager to zero
* Try starting a workspace

## Release Notes

```release-note
Prevent workspace starts during Gitpod update for single cluster ref arch
```

## Documentation

2022-09-23 06:53 UTC, kylos101 commented
Will mark ready for review after running a brief test upgrading from 7.1 to 8.0.

2022-09-28 09:13 UTC, Furisto commented on gitpod/docs/self-hosted/latest/prevent-workspace-starts.md
> +This can be done with `kubectl`, after which, users won't be able to start workspaces until the `ws-manager` pod is running again.
```suggestion
This can be done by scaling the ws-manager component down to zero, after which, users won't be able to start workspaces until the `ws-manager` pod is running again.
```

2022-09-29 09:44 UTC, lucasvaltl requested changes
This looks good to me - I've not run the command (kubectl scale --replicas=0 deployment/ws-manager -n <namespace>) to test it in practice though. 

One question - how would a user then get back into a "normal" state post update? Does this happen by default, because the update will overwrite the change to the ws-manager replicas set by the command? It might be worth explaining this if this is not a super obvious thing that I am just unaware of (not a K8s expert) :) 

Other than this, happy for this to be merged without another review.

2022-09-29 09:51 UTC, Furisto commented
You know this better than me but as far as I understand an update deletes the workspace components and then recreates them. In that case nothing would have to be done because the new deployment will have the correct replica count.

2022-09-29 13:15 UTC, Pothulapati commented
>update deletes the workspace components and then recreates them. In that case nothing would have to be done because the new deployment will have the correct replica count.

Yep, A `kots` update does that i.e removing existing install and re-appllying a new version which means the coutn goes back to the default.

> the update will overwrite the change to the ws-manager replicas set by the command? It might be worth explaining this if this is not a super obvious thing that I am just unaware of (not a K8s expert)

A note makes sense! in the lines of "After you do this, please know that an upgrade is a requirement to make the `ws-manger` working again"

2022-09-29 13:41 UTC, lucasvaltl approved these changes

2022-09-29 15:34 UTC, merged