[proposal]: Gitpod public API docs
gitpod-io/website pull request #2939
Opened 2022-10-24 10:56 UTC by Siddhant-K-code

> **Warning:** this work is in progress :construction:

## Description

first Iteration of documentation of Public API

## Related Issue(s)

Related #2911

## How to test

- Open Preview

2022-10-26 15:11 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api/index.md
> +- [Get owner token](/docs/references/gitpod-public-api/get-owner-token-api)
**Suggestion:** I'd consider keeping resources on the same page, for simplicity for now.

2022-10-26 15:12 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api/create-start-workspace-api.md
> +---
Any updates on: 

* Client libraries (e.g. TypeScript library)
* Authentication

2022-10-27 09:01 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +> **⚠️ Warning:** Public API is currently in development and may change frequently before it reaches General Availability.
Some small wording suggestions. 

```suggestion
> **⚠️ Warning:** The Public API is currently in active development. Gitpod may change the API contract **at any time** before the API is finally released as Generally Available. Use the API at your own risk. Also see [Release Cycle](/docs/help/public-roadmap/release-cycle) for the guarantees that Gitpod make for our features at various points in our release cycle. 
```

2022-10-27 11:19 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +It helps you to manage Gitpod Workspaces directly through gRPC APIs. Currently, all of the Authorization is on the server side, but it would be changed in future & will require a `authToken` (_coming
Can we mention the current state of auth and client libraries? Doesn't matter if things are not complete, if they're not complete, let's mention that. This documentation should be a representation of the current truth, no worries if the state is not fully complete, as this first doc is only a draft to get visibility on the current state 🙏 

```suggestion
It helps you to manage Gitpod Workspaces directly through gRPC APIs. Currently, all of the Authorization is on the server side, but it would be changed in future & will require a `authToken` (_coming soon_) to make an request to the APIs.

### Auth

Currently, auth is...

### Client Libraries

Currently, we support... 

We are looking to support...

```

2022-10-27 11:35 UTC, loujaybee commented
Looks good so far, @Siddhant-K-code ! :) 

I'd say let's add: 
1. A snippet of the API request in TypeScript
2. A section on the current state of Auth
3. A section on supported client libraries/languages

And that's all we need for now, we can then keep iterating on the PR as things change and update 🙏

2022-10-27 17:25 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-public-api.md
> +It helps you to manage Gitpod Workspaces directly through gRPC APIs. Currently, all of the Authorization is on the server side, but it would be changed in future & will require a `authToken` (_coming
Resolved in [**`29fece8`**](https://github.com/gitpod-io/website/pull/2939/commits/29fece84b79c20fb8273cdcd79fa59cc5eadfeec)

2022-10-28 17:54 UTC, david-bakin commented on gitpod/docs/references/gitpod-public-api.md
> +| `idempotencyToken` | Token that is used by the server to identify and discard replayed requests | string |   true   |
Is this `idempotencyToken` just some random string the caller provides?

2022-10-28 17:57 UTC, david-bakin reviewed
Examples would be great!  For example, looking at this, I'm wondering if `createAndStartWorkspace` - which can take a prebuild context URL - will actually do a prebuild, and then, if it does, what state is the workspace left in?  (Does it stop or is it still running? And how can you tell when the prebuild is done if it is left still running?)

2022-10-28 18:24 UTC, Siddhant-K-code commented
> Examples would be great! For example, looking at this, I'm wondering if createAndStartWorkspace - which can take a prebuild context URL - will actually do a prebuild, and then, if it does, what state is the workspace left in? (Does it stop or is it still running? And how can you tell when the prebuild is done if it is left still running?)

Thanks for the early feedback 🙏🏼. Currently, it is under 🚧. We will add the example snippets in the future (before merging this PR)

2022-10-28 18:28 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-public-api.md
> +| `idempotencyToken` | Token that is used by the server to identify and discard replayed requests | string |   true   |
yeah, its a UUID used on the server side.

2022-10-31 10:09 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +### Create & start workspace
**Thought/question:** Any reason to merge "create" and "start" nomenclature here? Why not just "workspace start"? Or why not "workspaceStatus" with the property as "start", etc? 

See [related PR on workspace loading process](https://github.com/gitpod-io/website/pull/2858), and [Netlify Preview](https://deploy-preview-2858--gitpod-kumquat.netlify.app/docs/introduction/learn-gitpod/workspace-lifecycle)

2022-10-31 10:12 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +It helps you to manage Gitpod Workspaces directly through gRPC APIs. Currently, all of the Authorization is on the server side, but it would be changed in future & will require a `authToken` (_coming
```suggestion
Gitpod public API automating the management of Gitpod Workspaces directly via gRPC APIs. 
```

2022-10-31 10:13 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +Currently, Authentication is under development and will be coming soon.
```suggestion
Authentication is currently under development. 
```

2022-10-31 10:14 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +Currently, We only support JavaScript/TypeScript (Node). But, we are looking to support for Go.
```suggestion
Public API currently supports JavaScript/TypeScript (Node). Client libraries in Go are currently planned. 
```

2022-10-31 10:16 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +|  `workspaceId`  |                                                       Workspace Id                                                       | string |
**Thought:** Should this be singular? Should we show the response format when there is multiple items returned?

2022-10-31 10:21 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +### Start workspace
**Thought:** Could/should this be `updateWorkspaceStatus` with passed arguments of status, rather than functions for each behaviour?

2022-10-31 10:26 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +# API Reference
**Question:** It looks like these endpoints are all assuming the user point of view, not the team, or installation point of view, is that correct? How extensible will these API's be at the level of team or installation?

2022-10-31 10:29 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +**Response Parameters**:
**Question/suggestion:** What about timestamps for instance when the workspace was last used? This data can be useful for teams who are tracking adoption of the workspaces within an installation / rollout.

2022-10-31 11:02 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-public-api.md
> +# API Reference
[Team APIs](https://deploy-preview-2939--gitpod-kumquat.netlify.app/docs/references/gitpod-public-api#teams-coming-soon) are on the way 🔜

2022-10-31 12:17 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +# API Reference
@Siddhant-K-code those look like mostly CRUD operations on top of the teams object, not operations like: 

- List all users in installation (regardless of team)
- List all workspaces (regardless of the user) as an admin

Which would be useful as an administrator of a Gitpod installation.

2022-10-31 13:20 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +---
Notes from discussion with @easyCZ:

* Parameters are not always camel case (depending on the language you use)
* We might be able to code generate definitions (so we don't have to hand craft the API definitions)
* Current endpoints are not entirely designed
* Start, stop (create and start) have been removed from the API

2022-10-31 13:25 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +- [Teams (_Coming soon_)](#teams-coming-soon)
https://github.com/gitpod-io/gitpod/pull/14212

2022-12-06 13:21 UTC, loujaybee commented
I'm going to open this for review now, given that we have PAT tokens for auth in prod and in our docs (https://github.com/gitpod-io/gitpod/issues/14910) we can now move to get this shipped ASAP. We should put some strong disclaimers around the API contracts and docs, but no reason to wait to communicate this now.

2022-12-15 17:08 UTC, loujaybee commented
@Siddhant-K-code / @easyCZ - I would like to merge this ASAP. 

I've removed the navigation so the page can be accessed only via deep linking at: `/docs/references/gitpod-public-api`

This should be okay to merge, given the alpha disclaimers, and we can make subsequent and smaller PR's 🙏

2022-12-15 17:08 UTC, loujaybee approved these changes

2022-12-15 17:11 UTC, loujaybee commented on src/lib/contents/docs/menu.ts
> +  // M("Gitpod public API", "references/gitpod-public-api", false, [], "alpha"),
Proposing to remove from navigation for now whilst we test in private beta.

2022-12-15 19:59 UTC, burningion requested changes

2022-12-15 19:59 UTC, burningion commented on gitpod/docs/references/gitpod-public-api.md
> +The following is an example of how to use the Go client library with the Public API for retrieving teams data. Replac the environment variable `PERSONAL_PAT` with your own personal access token, for
this pattern is weird. let's make the environment variable we export _just_ the token, and in the code example have the `Bearer ` be prepended in code.

2022-12-15 19:59 UTC, burningion commented on gitpod/docs/references/gitpod-public-api.md
> +                req.Header().Set("Authorization", os.Getenv("PERSONAL_PAT"))
this is where we'd prepend the `Bearer ` in code to the environment variable

2022-12-15 21:35 UTC, burningion commented on gitpod/docs/references/gitpod-public-api.md
> +                req.Header().Set("Authorization", os.Getenv("PERSONAL_PAT"))
```req.Header().Set("Authorization", "Bearer " + os.Getenv("PERSONAL_PAT"))``` should work

2022-12-16 15:56 UTC, loujaybee commented
Going to merge now. 

@burningion - I'll raise your concerns + ideas in a separate issue 🙏

2022-12-16 15:56 UTC, merged