Refine Go Language Page
gitpod-io/website pull request #3060
Opened 2022-11-23 08:31 UTC by Siddhant-K-code

Refine the whole Go Language Page

2022-12-28 20:30 UTC, burningion requested changes
Added some feedback inline.

2022-12-28 20:30 UTC, burningion commented on gitpod/docs/introduction/languages/go.md
> +Gitpod supports Go right out of the box, and This guide walks you through how to fully configure a Go application using Gitpod.
Gitpod includes Go in the default image, but if you need to customize your Go version or IDE setup in Gitpod, this guide will help you.

2022-12-28 20:30 UTC, burningion commented on gitpod/docs/introduction/languages/go.md
> -| Repository                                             | Description                                               |
Let's keep these example repos, they show how more advanced Go configuration works.

2022-12-28 20:30 UTC, burningion commented on gitpod/docs/introduction/languages/go.md
> -## Workspace Configuration
Why are we showing a Node/Typescript application in the Go language page?

2022-12-28 20:30 UTC, burningion commented on gitpod/docs/introduction/languages/go.md
> +If your project uses the [`dep` _(deprecated)_](https://golang.github.io/dep/) dependency manager then you need to add a [.gitpod.Dockerfile](/docs/configure/workspaces/workspace-image) to your proje
if we're going to say something is deprecated, say what version number it was deprecated in the text. it saves every person having to click and look themselves.

2022-12-29 04:05 UTC, Siddhant-K-code commented on gitpod/docs/introduction/languages/go.md
> -## Workspace Configuration
I would fix out the wordings 👍🏽 

Regarding Video Content - We don't have any video content other than JavaScript Applications (in demo).

cc: @Nancy-Chauhan

2022-12-29 17:07 UTC, burningion approved these changes

2022-12-29 17:22 UTC, merged