docs: flexible workspace timeouts
gitpod-io/website pull request #3268
Opened 2023-01-18 16:54 UTC by Siddhant-K-code

## Description

Related https://github.com/gitpod-io/gitpod/pull/15815

**Do Not Merge Until the above PR is deployed** _(ETA: tomorrow)_ 

## Related Issue(s)

Fixes #3267 

## How to test

Open Preview, Read & Verify the following:

- `/pricing`

<img width="383" alt="image" src="https://user-images.githubusercontent.com/55068936/213244313-a0ec883e-cc76-45a7-a1cf-c777f0ffaa2c.png">

- `/docs/introduction/learn-gitpod/the-life-of-a-workspace#timeouts`
- `/docs/references/gitpod-cli#timeout`

## Release Notes

```release-note
docs: Flexible Workspace Timeouts
```

2023-01-18 20:24 UTC, MichaelAring requested changes

2023-01-18 20:24 UTC, MichaelAring commented on src/lib/contents/pricing.ts
> +      tooltip: "Manually extent workspace timeout as long as you want.",
```suggestion
      tooltip: "Manually extend workspace timeout as long as you want.",
```

2023-01-18 20:25 UTC, MichaelAring commented
Tagging @burningion: this is not a meaningful change in the docs, but still letting you know in case you want to improve the content.

2023-01-18 20:38 UTC, burningion requested changes
Added a few comments

2023-01-18 20:38 UTC, burningion commented on gitpod/docs/introduction/learn-gitpod/the-life-of-a-workspace.md
> +Furthermore, _Unleashed_ users can manually boost the timeout of a workspace to as long as you want ([learn more](/docs/references/gitpod-cli#timeout)). This comes in handy, e.g. in case you want to
What is `Unleashed`?  Do we mean paid users? And isn't there a 24 hour limit?

2023-01-18 20:38 UTC, burningion commented on gitpod/docs/references/gitpod-cli.md
> +Extends the current workspace's timeout.
by how much?

2023-01-19 03:54 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-cli.md
> +Extends the current workspace's timeout.
This is an unrelated change through this PR (just re-ordered the sequence). But, I will take a look at this. Thanks

2023-01-19 03:59 UTC, Siddhant-K-code commented on gitpod/docs/introduction/learn-gitpod/the-life-of-a-workspace.md
> +Furthermore, _Unleashed_ users can manually boost the timeout of a workspace to as long as you want ([learn more](/docs/references/gitpod-cli#timeout)). This comes in handy, e.g. in case you want to
Again, It's an unrelated change that should be addressed at https://github.com/gitpod-io/website/pull/2895. I will take care of this.

2023-01-19 04:00 UTC, Siddhant-K-code commented on src/lib/contents/pricing.ts
> +      tooltip: "Manually extent workspace timeout as long as you want.",
This is being discussed internally [[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1674059258956459)], [[2](https://gitpod.slack.com/archives/C046Z4BBP2N/p1674061475535929)]. Let's Hold this PR Until we got the final heads up.

2023-01-19 14:22 UTC, burningion commented on gitpod/docs/introduction/learn-gitpod/the-life-of-a-workspace.md
> +Any running workspace will automatically stop after some time of inactivity. Normally, this timeout is 30 minutes but is extended to **60 minutes if you have an** [**_Paid plan_**](/pricing).
"but is extended to 60 minutes if you have a paid plan."

2023-01-19 14:22 UTC, burningion commented on gitpod/docs/introduction/learn-gitpod/the-life-of-a-workspace.md
> +Furthermore, _Paid_ users can manually boost the timeout of a workspace upto 24 hours ([learn more](/docs/references/gitpod-cli#timeout)). This comes in handy, e.g. in case you want to go out for a l
"up to"

2023-01-19 14:22 UTC, burningion commented on gitpod/docs/introduction/learn-gitpod/the-life-of-a-workspace.md
> +**Note**: If you do not have an _Paid_ plan, this command is not available.
why are we capitalizing Paid?

2023-01-19 14:23 UTC, burningion requested changes

2023-01-19 14:23 UTC, burningion commented on src/lib/contents/pricing.ts
> +      tooltip: "Manually extend workspace timeout upto 24 hours.",
"up to" (missing a space)

2023-01-20 12:16 UTC, Siddhant-K-code commented on gitpod/docs/introduction/learn-gitpod/the-life-of-a-workspace.md
> +**Note**: If you do not have an _Paid_ plan, this command is not available.
for using [this](https://www.gitpod.io/pricing) abbr.:

![image](https://user-images.githubusercontent.com/55068936/213692898-e4d80ab6-2321-47f6-bc54-2c97ebf66a6b.png)

2023-01-23 05:58 UTC, Siddhant-K-code commented
Also, Related Bug Report => https://github.com/gitpod-io/gitpod/issues/15945

2023-01-23 08:08 UTC, jldec approved these changes
LGTM with one change requested.

2023-01-23 08:08 UTC, jldec commented on gitpod/docs/references/gitpod-cli.md
>  The default timeout, and the ability to extend a workspace timeout depends on your [plan](https://gitpod.io/plans) or [team plan](https://gitpod.io/teams).
This line is no longer relevant - please replace with

`The default timeout, and the ability to extend a workspace timeout depends on your [billing configuration](/docs/configure/billing)`

(b.t.w. relative links allow the preview links to stay on site)

2023-01-23 10:45 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-cli.md
>  The default timeout, and the ability to extend a workspace timeout depends on your [plan](https://gitpod.io/plans) or [team plan](https://gitpod.io/teams).
Resolved ✅

2023-01-23 10:45 UTC, merged