docs: Projects API
gitpod-io/website pull request #3288
Opened 2023-01-23 09:02 UTC by Siddhant-K-code

## Description

This PR adds a documentation for Projects API.

- List All Projects
- Get a Project (Only Header, because it is :construction:)
- Create a Project
- Delete a Project

It includes both - HTTP & Go Examples with required paramaters

## How to test

See Preview of `/docs/references/gitpod-public-api#resource-projects`

## Release Notes

```release-note
docs: Projects API in Gitpod Public API _(Alpha)_
```

> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

2023-01-23 09:06 UTC, easyCZ approved these changes
LGTM % nits

/hold if you want to address the comments

2023-01-23 09:06 UTC, easyCZ commented on gitpod/docs/references/gitpod-public-api.md
> +      "settings": {}
Given we don't document the settings property, should we remove it from the examples for now?

2023-01-23 09:06 UTC, easyCZ commented on gitpod/docs/references/gitpod-public-api.md
> +	}
mis-aligned with the above blocked

2023-01-23 10:38 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +### Get a project (Coming soon)
**Thought:** I'm starting to wonder whether we should apply `release status` https://www.gitpod.io/docs/help/public-roadmap/release-cycle cycles to endpoints specifically, rather than the full API, to better define what's alpha, public beta, private beta, etc. It might get too confusing, though.

2023-01-23 10:44 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-public-api.md
> +### Get a project (Coming soon)
Since the whole page is under "Alpha". I don't think, it would make much difference until we tag each spec. with label. 
![image](https://user-images.githubusercontent.com/55068936/214020587-fe5825ec-6366-47b8-a20d-173503cd6a1e.png)

2023-01-24 16:54 UTC, burningion requested changes

2023-01-24 16:54 UTC, burningion commented on gitpod/docs/references/gitpod-public-api.md
> +  --data '{"teamId":"<TEAM_ID>"}'
You have <TEAM_ID> here, but no example of the type expected. (A string? UUID? Integer?) Let people know what the type is, and maybe even where to find it. (Via a link if necessary).

2023-01-24 16:54 UTC, burningion commented on gitpod/docs/references/gitpod-public-api.md
> +| `teamId`  |   Team Id   | String |   true   |
Ah here I see it's a string. What kind of a string is it? Can we give more detail?

2023-01-24 16:54 UTC, burningion commented on gitpod/docs/references/gitpod-public-api.md
> +|      `id`      |                               Proejct Id                               | string |
misspelling here of project

2023-01-24 23:38 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +  --data '{"teamId":"<TEAM_ID>"}'
> Maybe even where to find it. (Via a link if necessary).

Like the idea of linking to where this can be found! Did want to note that these ID's are not (at least to my knowledge) surfaced anywhere in the product (see issue below). I've added the Public API label to the issue, and we should aim to get this fixed + so we can update the docs before the API is publically accessible beta! 

- https://github.com/gitpod-io/gitpod/issues/15654

2023-01-24 23:44 UTC, loujaybee commented on gitpod/docs/references/gitpod-public-api.md
> +### Get a project (Coming soon)
Yeah, it's certainly not-blocking for his PR, more a thought passing through my mind as I see these "coming soon" labels. Let's pick up separately / another time. Until we have a candidate for a public beta, it's not particularly relevant, but is something that I'm thinking about.

2023-01-25 05:52 UTC, Siddhant-K-code commented on gitpod/docs/references/gitpod-public-api.md
> +  --data '{"teamId":"<TEAM_ID>"}'
> (A string? UUID? Integer?) Let people know what the type is

I followed OpenAPI Spec standards while defining these (because that's our [future goal](https://github.com/gitpod-io/gitpod-public-api-roadmap)). As [they Said here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#data-types:~:text=Formats%20such%20as,is%20not%20specified.). UUID is a `format` & Not a `type`. 

The thing we could do is add a separate table for `format` **OR** just `string (uuid)`


wdyt @burningion @loujaybee

2023-01-25 07:27 UTC, easyCZ commented on gitpod/docs/references/gitpod-public-api.md
> +  --data '{"teamId":"<TEAM_ID>"}'
FWIW, any ID we reference should not state what type it is - UUID, or otherwise. The ID should be opaque to the client and we do not expect the client to do any parsing or understanding of the IDs in any way. 
This is pretty standard in APIs as it allows you to change how you represent the IDs without breaking clients in a major way. That's also the reason it's represented as a String, rather than a more specific datatype.

2023-01-27 13:59 UTC, burningion approved these changes

2023-02-01 05:10 UTC, Siddhant-K-code commented
@loujaybee If you got some time this week, can you please review this? So we can :shipit: 🙏🏽

2023-06-16 09:26 UTC, Siddhant-K-code commented
Closing this for now, As we are not actively working on this.

2023-06-16 09:26 UTC, closed without merging