:rocket: New `/solutions/collaboration` page
gitpod-io/website pull request #3448
Opened 2023-02-21 08:34 UTC by Siddhant-K-code

## Description

Review on `/solutions/collaboration`

## Related Issue(s)

Fixes #3437

## How to test

## Release Notes

```release-note
Website: Gitpod Collaboration Solutions page
```

2023-02-21 08:39 UTC, Siddhant-K-code commented on src/routes/solutions/collaboration.svelte
> +/>
@MichaelAring Feel free to suggest some other Meta Descriptions & Title page.

2023-02-21 08:39 UTC, Siddhant-K-code commented on src/routes/solutions/collaboration.svelte
> +      name: "xyz",
@MichaelAring We need a real name to mention here. [_Internal conversastion_](https://www.figma.com/file/K0VV8lc3pmlMVModYM70nj?node-id=9326:21637#370028817)

2023-02-22 12:04 UTC, MichaelAring commented on src/routes/solutions/collaboration.svelte
> +      name: "xyz",
Johannes Schickling

2023-02-22 13:47 UTC, MichaelAring requested changes
editorial changes

2023-02-22 13:47 UTC, MichaelAring commented on src/routes/solutions/collaboration.svelte
> +      name: "xyz",
```suggestion
      name: "Johannes Schickling",
```

2023-02-22 13:47 UTC, MichaelAring commented on src/lib/components/explore.svelte
> +    description = "Spin up fresh, automated dev environments for each task, in the cloud, in seconds - no contracts or banking details required.",
```suggestion
    description = "Spin up fresh, automated dev environments for each task, in the cloud, in seconds - no credit card required.",
```

2023-02-22 13:47 UTC, MichaelAring commented
Please test new Quizlet customer story link before merging.

2023-02-22 13:50 UTC, MichaelAring requested changes
meta tags change

2023-02-22 13:50 UTC, MichaelAring commented on src/routes/solutions/collaboration.svelte
> +      "cloud dev environment, cde, remote development, developer experience, collaboration, solution, solutions",
```suggestion
      "cloud development environment, cde, remote development, developer experience, collaboration, snapshot, workspace sharing",
```

2023-02-22 15:41 UTC, MichaelAring approved these changes
looks good!

2023-02-22 15:41 UTC, merged