Introduce `jammy` as OS for workspace images
gitpod-io/website pull request #3544
Opened 2023-03-27 00:45 UTC by kylos101

## Description

Introduce `jammy` as OS for workspace images

## Related Issue(s)

Fixes # https://github.com/gitpod-io/workspace-images/issues/1061

## How to test

Refer to `Options to consider` in the changelog.

## Release Notes

```release-note
Update OS to Jammy for Gitpod provided workspace images
```

2023-03-27 00:47 UTC, kylos101 commented
@atduarte could I ask for your help in editing/reviewing? :pray:

2023-03-27 00:48 UTC, kylos101 commented on src/lib/contents/changelog/jammy.md
> +ogImage: jammy.webp
@atduarte is there an image you'd like to provide in this changelog entry? :thinking: Or can we do without?

2023-03-27 05:13 UTC, Siddhant-K-code commented
#3533 is merged  deployed now. We need to ship this ASAP to avoid confusions to users. 

:shipit:

2023-03-27 14:24 UTC, kylos101 commented
@atduarte @loujaybee are either of you able to help with a review, sharing an image, and Tweet?

2023-03-28 05:56 UTC, Siddhant-K-code commented
I have updated the image & also added an instruction to file an issue if there are any problems in their workspaces in commit [`c8735f3`](https://github.com/gitpod-io/website/pull/3544/commits/c8735f37679eac7407034a3e2d3af2726a4f0322)

2023-03-28 05:56 UTC, Siddhant-K-code commented on src/lib/contents/changelog/jammy.md
> +ogImage: jammy.webp
resolved in https://github.com/gitpod-io/website/pull/3544#issuecomment-1486260079

2023-03-28 05:58 UTC, Siddhant-K-code approved these changes
Looks good to me ✔️ 

- For User: Instructions to file an issue, if they face any problem with their workspaces. ✅ 
- Alternative solutions to use tagged images. ✅ 
- Image asset ✅

2023-03-28 08:43 UTC, atduarte requested changes
Minor changes requested. Thanks a ton, @kylos101! Looks very good 🙏

2023-03-28 08:43 UTC, atduarte commented on src/lib/contents/changelog/jammy.md
> +Additionally, `gitpod/workspace-node` and `gitpod/workspace-node-lts` workspace images will be upgraded to use Node 19.0.0 and Node 18.13.0, respectively.
I think this is repeated.

```suggestion
```

2023-03-28 11:48 UTC, kylos101 commented on src/lib/contents/changelog/jammy.md
> +If you'd like to continue using the current OS and Node versions, you may pin the workspace image version by changing the tag from `latest` to `2023-01-16-03-31-28` (e.g. `gitpod/workspace-node-lts:2
Great point, @atduarte , thank you.

2023-03-28 13:31 UTC, axonasif approved these changes
Looks perfect!

2023-03-28 14:29 UTC, kylos101 commented
Thanks for the suggestion @axonasif , accepted!

2023-03-28 16:49 UTC, kylos101 commented
@atduarte I could not merge this, it required your explicit approval (even though I accepted your changes). I dismissed your review (so that we can merge), and am sharing here for posterity.

2023-03-28 16:49 UTC, merged

2023-03-28 16:53 UTC, atduarte commented
Sorry missed the above!