(Docs) Update self-hosted deprecation info box Closes #3364.
gitpod-io/website pull request #3671
Opened 2023-05-23 14:35 UTC by Utkarshn10

## Description

Updated the  self-hosted deprecation info box on the following routes:

- https://www.gitpod.io/docs/configure/self-hosted/latest
- https://www.gitpod.io/community-license

## Related Issue(s)

Fixes ##3364

## How to test

To view the changes visit :
- /docs/configure/self-hosted/latest
- /community-license

## Release QA Checklist ✔️

<details>
  <summary>QA Checklist </summary>

## [Priority: High] Functional Testing

- [ ] Test all links to make sure they are working correctly
- [ ] Verify that all forms (sales, support, docs feedback)  are functioning properly and data is being captured correctly
- [ ] Check all buttons and calls-to-action to ensure they are leading to the correct pages
- [ ] Ensure that the website is mobile responsive and functions properly on different devices
- [ ] Ensure that page is optimal for Light/Dark Mode. ⇒ Text/Media Changes
  

## [Priority: High] Content Testing

- [ ] Check all website copies for accuracy and spelling/grammar errors
- [ ] Verify that all images and videos are displaying properly
- [ ] Ensure that all downloadable files are working correctly
- [ ] Check that all external links are functioning properly

## [Priority: Medium] Performance Testing

- [ ] Try to use optimal media assets. ([Decision Record - How To](https://github.com/gitpod-io/website/blob/main/docs/adr/0003-optimal-assets-format.md))
- [ ] Test website load times to ensure that the website is loading quickly
- [ ] Verify that the website can handle high traffic volumes without crashing
- [ ] Check that all website functionality is working properly under heavy load
- [ ] Perform cross-browser testing to ensure that the website works properly on all major browsers (Goolge Chrome, Firefox, Edge)

## [Priority: Medium] Accessibility Testing

- [ ] Ensure that the website meets basic accessibility guidelines.
- [ ] Test that users with disabilities can easily navigate and use the website
- [ ] Verify that all website content can be accessed using assistive technologies

By including these key items in your website release QA checklist, you can ensure that your website is fully functional, user-friendly, and meets your business requirements.

## Security Testing

> **Note**:💡 If we are changing something related to cookies or data storing or analytics side.

- [ ] Verify that the website is HTTPS secure and that there are no security vulnerabilities
- [ ] Ensure that all sensitive data is being stored and transmitted securely

  </details>

2023-05-24 05:23 UTC, Utkarshn10 commented
Hey @Siddhant-K-code, the server run is failing because of the invalid key for configcat. So will I have to create a sdk key of my own to make it run?

2023-05-24 07:02 UTC, Siddhant-K-code commented
> Hey @Siddhant-K-code, the server run is failing because of the invalid key for configcat. So will I have to create a sdk key of my own to run it?

Naah! It's already there now! (See [this](https://github.com/gitpod-io/website/blob/main/.gitpod.yml#L25)). I've updated your branch with the base.

2023-05-24 07:08 UTC, Siddhant-K-code requested changes
Thanks ✨ 

But, there are some [other occurrences of this Docs Notice](https://github.com/search?q=repo%3Agitpod-io%2Fwebsite%20The%20last%20official%20update%20of%20this%20product%20is%20the%20%5BNovember%202022%20self-hosted%20release%5D&type=code), where we need to do the similar changes.

2023-05-24 07:11 UTC, Siddhant-K-code commented on gitpod/docs/configure/self-hosted/latest/index.md
> +> The last update of Gitpod Self-hosted product was [November 2022](https://www.gitpod.io/changelog/november-self-hosted-release). Users can still request our [free community license](https://www.git
**Suggestion**: Use relative URLs. This way, it would redirect to the same tab rather than explicitly open in a new tab.

```suggestion
> The last update of Gitpod Self-hosted product was [November 2022](/changelog/november-self-hosted-release). Users can still request our [free community license](/community-license) however there will be no support or updates to the product. If you are interested in an isolated, private installation of Gitpod, take a look at [Gitpod Dedicated](/dedicated).
```

2023-05-25 05:53 UTC, Siddhant-K-code approved these changes
Thanks @Utkarshn10 🧡

2023-05-25 05:54 UTC, merged