Sc/update getting started
gitpod-io/website pull request #3946
Opened 2023-08-29 20:58 UTC by scarolan

Updates the getting started guide

2023-08-30 14:43 UTC, Siddhant-K-code approved these changes
LGTM 🧡 

**Suggestion (non-blocking)**: It would be good, if we use `webp` images. ([Guide](https://github.com/gitpod-io/website/blob/main/docs/adr/0003-optimal-assets-format.md) to convert `png` to `webp`)

2023-08-30 16:16 UTC, lucasvaltl requested changes
Overall, LGTM - thank you very much for working on this! Feel free to merge it once you have addressed the comments I made - none of them are blocking.

2023-08-31 12:23 UTC, scarolan commented on src/content/docs/gitpod-dedicated/guides/getting-started.md
> +3. If you run into errors during the Cloudformation deployment you should remove all existing resources before trying again. There are a few resources that need to be cleaned up manually before you a
yes, let's move that in the next PR

2023-08-31 12:47 UTC, lucasvaltl approved these changes

2023-08-31 12:47 UTC, merged