docs: Clarify local port forwarding and mention `gp ssh`
gitpod-io/website pull request #3985
Opened 2023-09-22 04:50 UTC by abitrolly

## Description

## Related Issue(s)

Fixes

## How to test

Read new docs?

https://www.gitpod.io/docs/configure/workspaces/ports#port-forwarding

## Release QA Checklist ✔️

<details>
  <summary>QA Checklist </summary>

## [Priority: High] Functional Testing

-   [x] Test all links to make sure they are working correctly
-   [x] Verify that all forms (sales, support, docs feedback) are functioning properly and data is being captured correctly
-   [x] Check all buttons and calls-to-action to ensure they are leading to the correct pages
-   [x] Ensure that the website is mobile responsive and functions appropriately on different devices
-   [x] Please make sure that page is best for Light/Dark Mode. ⇒ Text/Media Changes

## [Priority: High] Content Testing

-   [x] Check all website copies for accuracy and spelling/grammar errors
-   [x] Verify that all images and videos are displaying properly
-   [x] Ensure that all downloadable files are working correctly
-   [x] Check that all external links are functioning properly

## [Priority: Medium] Performance Testing

-   [x] Try to use optimal media assets. ([Decision Record - How To](https://github.com/gitpod-io/website/blob/main/docs/adr/0003-optimal-assets-format.md))
-   [x] Test website load times to ensure that the website is loading quickly
-   [x] Verify that the website can handle high traffic volumes without crashing
-   [x] Check that all website functionality is working properly under heavy load
-   [x] Perform cross-browser testing to ensure that the website works properly on all major browsers (Google Chrome, Firefox, Edge)

## [Priority: Medium] Accessibility Testing

-   [x] Ensure that the website meets basic accessibility guidelines.
-   [x] Test that users with disabilities can easily navigate and use the website
-   [x] Verify that all website content can be accessed using assistive technologies

By including these key items in your website release QA checklist, you can ensure that your website is fully functional, user-friendly, and meets your business requirements.

## Security Testing

> **Note**:💡 If we are changing something related to cookies, data storing, or analytics.

-   [x] Verify that the website is HTTPS secure and that there are no security vulnerabilities
-   [x] Ensure that all sensitive data is being stored and transmitted securely

</details>

2023-09-23 01:56 UTC, ghostdevv requested changes

2023-09-23 01:56 UTC, ghostdevv commented on src/content/docs/configure/workspaces/ports.md
> +**Example:** Forwarding local port `3000` to port `localhost:3000` in the workspace.
```suggestion
**Example:** Forwarding port `3000` in your Gitpod workspace to `localhost:3000`.
```

2023-09-23 01:56 UTC, ghostdevv commented on src/content/docs/configure/workspaces/ports.md
> +Local port forwarding allows you to access a port running in your Gitpod workspace from your localhost hostname. Remote port forwarding exposes a locally running process to use in your workspace. Rem
Not sure this reads the same, maybe it'll be easier if I ask you what specifically you found confusing so we can tweak it together? @abitrolly

2023-09-23 04:42 UTC, abitrolly commented on src/content/docs/configure/workspaces/ports.md
> +Local port forwarding allows you to access a port running in your Gitpod workspace from your localhost hostname. Remote port forwarding exposes a locally running process to use in your workspace. Rem
The confusing part is that before explanation of "what forwarding is" is basically "forwarding is allowing you to forward" and that doesn't explain anything. After explanation is "forwarding is allowing you to access".

2023-09-23 04:53 UTC, abitrolly commented on src/content/docs/configure/workspaces/ports.md
> +**Example:** Forwarding local port `3000` to port `localhost:3000` in the workspace.
No, that's not how it works. The command forwards port 3000 from the local machine, so when you enter `localhost:3000` in browser, the request goes to local port 3000 and then SSH tunnel fetches `localhost:3000` on the Gitpod host.

`-L localhost:3000:google.com:80` will try to fetch Google homepage and will fail because of invalid certificate.

2023-09-23 16:38 UTC, ghostdevv commented on src/content/docs/configure/workspaces/ports.md
> +Local port forwarding allows you to access a port running in your Gitpod workspace from your localhost hostname. Remote port forwarding exposes a locally running process to use in your workspace. Rem
I think I misread that originally, LGTM

2023-09-23 20:31 UTC, ghostdevv commented on src/content/docs/configure/workspaces/ports.md
> +**Example:** Forwarding local port `3000` to port `localhost:3000` in the workspace.
Ah, I missed the context above

2023-09-23 20:31 UTC, ghostdevv approved these changes

2023-09-23 20:32 UTC, merged

2023-09-24 03:53 UTC, abitrolly commented on src/content/docs/configure/workspaces/ports.md
> +**Example:** Forwarding local port `3000` to port `localhost:3000` in the workspace.
That's why this chapter needs more improvements. :D