a super cool announcement
gitpod-io/website pull request #401
Opened 2021-04-24 06:52 UTC by ghuntley

2021-04-24 07:12 UTC, ghuntley commented on src/routes/blog/gitpod-open-source-sustainability-fund.md
> +We recognise that money <a href="https://www.youtube.com/watch?v=Mm_RuObpeGo">isn't the only way to resolve open-source sustainability</a>. Often the problem is access and the initial project setup f
to -> can

2021-04-24 08:06 UTC, ghuntley commented on src/routes/blog/gitpod-open-source-sustainability-fund.md
> +Did you know there are less than 2100 people in the inner GitHub open-source maintainer community?
Whilst the open-source ecosystem is bigger than GitHub.

2021-04-24 09:03 UTC, ghuntley commented on src/routes/blog/gitpod-open-source-sustainability-fund.md
> +2. ⒉ For every registration to our newly created <a href="https://www.gitpod.io/chat">discord channel</a> we’ll donate an additional $1 to open-source projects we depend upon.
During the next month.

2021-04-24 09:16 UTC, ghuntley commented on src/routes/blog/gitpod-open-source-sustainability-fund.md
> +1. ⒈ Gitpod has created an open-source sustainability fund and allocated an _initial_ amount of USD 30,000 has been allocated towards securing our open-source supply chain by paying open-source maint
double allocated

2021-04-25 12:46 UTC, mikenikles requested changes
I notice `<a>` and `<ol>` HTML tags in the blog's Markdown. Let's use Markdown syntax unless there is a good reason to inject raw HTML, e.g. if we have to add a `class` attribute to style something in a particular way.

The `OSS_fund_header.jpg` image needs to be moved to `static/images/blog/gitpod-open-source-sustainability-fund` so that the cover image displays correctly. This will also fix the broken image on the actual blog post itself and in fact, the Netlify deployment.

Please remove `yarn.lock`. I created #405 to ignore that file and to document the use of NPM for this project.

2021-04-25 12:46 UTC, mikenikles commented on src/routes/blog/gitpod-open-source-sustainability-fund.md
> +      <span>1- </span>Generate the bill of materials in your commerical software.
We have ordered lists styled consistently across the website with CSS. Is there a particular reason we want this to look differently here?

If not, this HTML `ol` can be replaced with an ordered list written in Markdown.

2021-04-26 13:46 UTC, merged

2021-04-26 14:13 UTC, JohannesLandgraf commented
@ghuntley looks good some minor things: 

- [ ] Replace the teaser image with a new background. Updated [here](https://www.figma.com/file/Mlo0SjCChzsbSiCWMP4BzP/OSS-Fund-Blog-Post?node-id=1%3A40).
- [ ] tandardized -> standardized
- [ ] There are now 5 not four things :P