add GitHub teacher toolbox page.
gitpod-io/website pull request #425
Opened 2021-05-04 23:33 UTC by nisarhassan12

2021-05-04 23:42 UTC, nisarhassan12 commented on src/components/pricing/pricing-box.svelte
> +      <div class="h-full flex flex-col justify-center items-center">
@mikenikles For some reason these tailwind classes don't get applied on Firefox see the below screenshot
![image](https://user-images.githubusercontent.com/46004116/117082575-0bb5ea80-ad5c-11eb-9cb9-b54d957b0371.png)

2021-05-05 04:41 UTC, mikenikles requested changes
I applied changes in eb0398a759fdf7f13edbeb7341903f19babaadd1 to centre the "Learn more" link in the pricing card in Safari and Firefox as per your request in Slack.

While it centres the link, it is not aligned with the lists in the other cards since the `<ul>` elements are of dynamic height.

I also reviewed the rest of the PR and left comments. Let me know if you'd like to discuss any of them.

2021-05-05 16:12 UTC, nisarhassan12 commented on src/components/github-page/header.svelte
> +    margin-top: var(--small);
Thanks. I looked at the docs. I'm unable to figure out which class is gonna give me `margin-top: var(--small);` mt-4 ? How to figure out the scale ? Thanks

2021-05-05 17:05 UTC, nisarhassan12 commented on src/components/github-page/pricing-offers.svelte
> +</style>
Thanks.  Got it. 

For the header I want some class like `max-w-780` but this does not exist in tailwind. The max-width 780 px is specific to this component and I don't want to add this value to the `tailwind.config.js`.  What should I do here ? Thanks

2021-05-05 17:07 UTC, nisarhassan12 commented on src/components/github-page/pricing-offers.svelte
> +</style>
I saw we can do something like following in tailwind `2.1`: 

![image](https://user-images.githubusercontent.com/46004116/117180933-25077700-adee-11eb-84d2-040310690b26.png)

Should we upgrade to that ? Thanks

2021-05-05 17:13 UTC, nisarhassan12 commented on src/components/pricing/pricing-box.svelte
> +    @apply underline;
Thanks. I already tried that. we have the following in `_reset.scss`

```scss
a[class] {
  text-decoration: none;
}
```

which overrides `underline` class if added directly to the element so that's why I have to go this route.

2021-05-05 17:38 UTC, nisarhassan12 commented on src/components/pricing/pricing-box.svelte
> +    <div class="footnote">{footnote}</div>
Thanks. I have added the following font-sizes to the `fontSize` object:

```js
fontSize: {
        "p-large": "var(--p-large)",
        "p-medium": "var(--p-medium)",
        "p-small": "var(--p-small)",
        "p-xsmall": "var(--p-xsmall)",
        "btn-small": "var(--btn-small)",
        "fine-print": "var(--fine-print)",
},
```

How can I refernce these via tailwind classes ?

2021-05-05 18:40 UTC, mikenikles commented on src/components/github-page/header.svelte
> +    margin-top: var(--small);
The `var(--small);` equivalent in Tailwind is called `small`. You can find that at https://github.com/gitpod-io/website/blob/main/tailwind.config.cjs#L72. The relevant section in the docs I linked to is https://tailwindcss.com/docs/margin#margin-scale. This is where they explain how to customize spacing.

That means, `margin-top: var(--small);` in Tailwind is `mt-small`.

2021-05-05 18:54 UTC, mikenikles commented on src/components/github-page/pricing-offers.svelte
> +</style>
Tailwind provides a wide range of max width values ([docs](https://tailwindcss.com/docs/max-width)). One of the main reasons we use Tailwind is to keep the user interface consistent across the entire website. Using a unique max width for a single component breaks that consistency. Why do we want to use a custom pixel value for this one component only?

The `mb-[278px]` feature in newer versions of Tailwind is an escape hatch for situations where there is no way around a more standardized Tailwind class. I don't think this is a feature we should use freely as it breaks the consistency we get with Tailwind classes.

2021-05-05 18:56 UTC, mikenikles commented on src/components/pricing/pricing-box.svelte
> +    <div class="footnote">{footnote}</div>
Nice work. To use them, it works the same way as you use regular Tailwind font size classes. Please see https://tailwindcss.com/docs/font-size#font-sizes.

2021-05-05 19:21 UTC, mikenikles commented on src/components/pricing/pricing-box.svelte
> +    @apply underline;
Good catch, we can keep it like that for now.

2021-05-05 19:25 UTC, mikenikles commented on src/routes/github-student-developer-pack.svelte
> +  <svelte:fragment slot="description">
Nice, now we also get syntax highlighting and Prettier auto-formats the code 👍

2021-05-05 20:03 UTC, mikenikles requested changes
Two minor change requests, then we're good to go.

2021-05-05 20:03 UTC, mikenikles commented on src/routes/github-teacher-toolbox.svelte
> +  description="Let’s Focus on Teaching Code, not Tedious Setups! With Gitpod you can create coding exams and exercises easily, help out your students via live tutoring, and benefit from a simple onbo
Given there is HTML in this string, let's also convert it to a named slot similarly to how it's done for the `PricingOffers` component.

2021-05-05 20:03 UTC, mikenikles commented on src/components/github-page/headline.svelte
> +  export let text;
Let's turn this script into `lang="ts"` and add a type here.

2021-05-05 22:31 UTC, mikenikles approved these changes

2021-05-05 22:31 UTC, merged