add the media-kit page.
gitpod-io/website pull request #447
Opened 2021-05-12 03:56 UTC by nisarhassan12

2021-05-16 19:30 UTC, nisarhassan12 commented on src/components/media-kit/logo-section.svelte
> +      For more details <a href="/assets/style-guide.pdf">see style guide</a>.
@mikenikles This link is behaving quite oddly when I click through it gives a 404 but when I visit the url http://localhost:3000/assets/style-guide.pdf directly it gives me the desried result.  

https://user-images.githubusercontent.com/46004116/118410012-c15f3280-b6a6-11eb-9f5b-4bf6fefea6d8.mp4

2021-05-17 09:41 UTC, ChristinFrohne commented
Great thanks! Some comments

- [ ] please add a link to the footer under "company"
- [ ] we need a consistent naming. Currently, the link says "media kit" but on the page, it says "press kit". Let's go with "media-kit" I'd say that sounds more generic
- [ ] having two headlines directly after each other looks a bit weird. I added an image to the mockup. If you agree, please add it to the page
- [ ] the style guide should open in a new tab
- [ ] update color for "sand light" (# F5F4F4 -see mockup)
- [ ] please contact Johannes to get a better profile image with a higher resolution 
- [ ] on mobile the buttons are misaligned 
<img width="346" alt="Bildschirmfoto 2021-05-17 um 11 38 43" src="https://user-images.githubusercontent.com/46345125/118467869-7bd15280-b704-11eb-8ab3-092a1dffd40d.png">

2021-05-17 21:43 UTC, mikenikles requested changes

2021-05-17 21:43 UTC, mikenikles commented on src/assets/scss/_buttons.scss
> +  min-width: 5rem;
**question**: This impacts all buttons with that class name. Is it a safe change that doesn't impact the look & feel of these buttons?

2021-05-17 21:43 UTC, mikenikles commented on src/components/section.svelte
> +  export let className: string;
We have to be careful when we add mandatory props like this. For all existing `<Section />` components, we now have an empty space in the `class` attribute and get the following warning in the browser console:

```
<Section> was created without expected prop 'className'
```

If `className` is optional, we can mark it as such by giving it a default value.

Remember, it is important to review and address warnings displayed in the terminal and the browser console.

2021-05-17 21:43 UTC, mikenikles commented on src/components/media-kit/logo-section.svelte
> +      For more details <a href="/assets/style-guide.pdf">see style guide</a>.
I can't reproduce that on the [PR preview URL](https://deploy-preview-447--gitpod-kumquat.netlify.app/media-kit), can you? Tested in Safari, Chrome, Brave and Firefox.

In any case, please have a look at the SvelteKit documentation with an explanation of why you likely see this and how to fix it: https://kit.svelte.dev/docs#anchor-options-rel-external

2021-05-18 10:20 UTC, nisarhassan12 commented on src/components/media-kit/logo-section.svelte
> +      For more details <a href="/assets/style-guide.pdf">see style guide</a>.
Thanks. I can't reproduce this as well on the deploy preview as well. It only happend on `localhost`.

2021-05-18 18:11 UTC, nisarhassan12 commented on src/assets/scss/_buttons.scss
> +  min-width: 5rem;
Thanks. @mikenikles I tested all the instances and it doesn't impact the look and feel of them. Now that I have made the buttons intact with the mockup it is no longer required.

2021-05-18 19:42 UTC, mikenikles approved these changes

2021-05-18 19:43 UTC, merged

2021-05-19 01:52 UTC, ghuntley commented
![](https://media1.giphy.com/media/b1o4elYH8Tqjm/giphy.gif)