add lighthouse ci.
gitpod-io/website pull request #546
Opened 2021-06-02 17:31 UTC by nisarhassan12

2021-06-03 04:10 UTC, mikenikles requested changes
Thanks for getting this started Nisar.

To get the most accurate data from a Lighthouse test, we need to run it against the Netlify deployment URL. The process should be like this:
1. Deploy the website to Netlify
2. Kick off the Lighthouse tests against the Netlify deployment URL
3. Report the Lighthouse test results

A quick online search reveals the following promising solutions:
* https://github.com/netlify-labs/netlify-plugin-lighthouse
* https://github.com/marketplace/actions/wait-for-netlify

At first glance, I get the impression that the `netlify-plugin-lighthouse` runs the Lighthouse tests against the static files while the `wait-for-netlify` GitHub Action is more aligned to what we actually need and lets us configure Lighthouse to run against the Netlify deployment URL.

Could you give the `wait-for-netlify` GitHub Action a try? Have a look at how I configured something similar on my personal website at https://github.com/mikenikles/www-mikenikles-com/blob/master/.github/workflows/services-website.yml.

2021-06-03 04:10 UTC, mikenikles commented on .github/workflows/ci.yml
> +      - run: npm run build
Our `build` script is likely not what we need here. It only builds the CSS files and generates an intermediary Svelte output.

2021-06-03 17:16 UTC, nisarhassan12 commented on .github/workflows/ci.yml
> +      - run: npm run build
Thanks for pointing this out `deploy` script is gonna be the relevant script here. I have removed this block since we are gonna run this against the netlify preview URL.

2021-06-03 17:39 UTC, nisarhassan12 commented
Thanks, @mikenikles for pointing me out in the right direction. I have looked at what you shared and made some changes and it seems to be working please re-review when you'll get time. Thanks

2021-06-03 17:57 UTC, nisarhassan12 commented on .github/workflows/ci.yml
> +          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitFor200.outputs.url }} || echo "LHCI failed!"
@mikenikles Does this line means that `lhci` would only run lighthouse against the homepage? If so then how can we run it against all the pages and maybe two pages on each docs and blog i.e the /blog/ and /blog/something/ etc? I have found the following which does not look quite good i.e we have to manually specify all the URLs and we have to change the file every time a new page is added from what I understand. 

https://github.com/GoogleChrome/lighthouse-ci/issues/124#issuecomment-560132242

2021-06-04 23:17 UTC, mikenikles commented on .github/workflows/ci.yml
> +          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitFor200.outputs.url }} || echo "LHCI failed!"
Yes, that's correct. We need to manually list the pages we want to test. If we want to test all pages, I suggest:
* We generate a `/sitemap.xml` with all pages listed
* Create a script that parses that file and auto-generates the `lhci` command

**However**, I think we can manually list the following key pages:
* Homepage, features, pricing, blog index
* One blog detail page
* One docs page

That will give us a good enough idea of how we're performing. If for example a blog detail page slows down significantly, it is likely the others are impacted too.

Instead of the `lhci` command, could you look into https://github.com/marketplace/actions/lighthouse-ci-action? It may be a bit simpler than the `npm install` and `lhci` commands.

Nice work with that PR overall ✨!

2021-06-07 22:03 UTC, nisarhassan12 commented
@mikenikles It looks as if the `wait-for-netlify` action didn't work. The Pr branch was outdated and I pulled the latest main and then merged the changes into this PRs branch which triggered a re-build on Netlify's end and the actions ran without that deploy preview being ready. It failed because it was not able to load https://deploy-preview-546--gitpod-kumquat.netlify.app/blog/devxconf-wrap URL. 

![image](https://user-images.githubusercontent.com/46004116/121092416-f45b9880-c804-11eb-9afa-3ada6a1642ef.png)

Now that the netlify deploy preview is ready I'm able to visit the URL which caused the failure. 

It could be that I might have misunderstood how `wait-for-netlify-action` works i.e it maybe only waits when the initial Pr is made ? and then on subsequent pushes, it uses that old URL without waiting for re-deploys ?

2021-06-07 22:12 UTC, nisarhassan12 commented
I re-ran the jobs and it worked as expected the failure is because of not intact with the budget https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1623103752551-56465.report.html

2021-06-07 22:28 UTC, mikenikles commented
There's [an open issue](https://github.com/JakePartusch/wait-for-netlify-action/issues/6) that sounds related. We have to make sure the Lighthouse tests run against the deployment that contains the latest commits.

2021-06-22 00:33 UTC, nisarhassan12 commented
Thanks, @mikenikles I tried as suggested in https://github.com/JakePartusch/wait-for-netlify-action/issues/6#issuecomment-667644956 it seems to be working 🎉

2021-06-22 03:27 UTC, mikenikles commented
Nice, this looks good. Do you think we can address my thoughts in https://github.com/gitpod-io/website/pull/546#discussion_r645900557?

Mainly, use the Lighthouse GitHub Action and configure more than just the root URL to test against.

2021-06-22 17:00 UTC, nisarhassan12 commented
> Mainly, use the Lighthouse GitHub Action and configure more than just the root URL to test against.

Thanks, @mikenikles Done.

2021-06-28 04:16 UTC, mikenikles commented
@nisarhassan12 awesome, this looks excellent! Any idea what causes the pricing page to fail the Lighthouse benchmark? Let's discuss and address it so we can merge this PR.

I'm super happy to see this come together as part of each PR.

2021-06-29 01:25 UTC, nisarhassan12 commented
Thanks. @mikenikles sounds good. Let's discuss this via a call when you are back at work.

2021-07-07 05:32 UTC, nisarhassan12 commented
For now, we have decided to remove the budget entries to make the CI pass we will incrementally add budget entries in smaller PRs making sure that the check passes. To track this I have opened issue https://github.com/gitpod-io/website/issues/731.

2021-07-07 05:46 UTC, merged