add the ui for the newsletter signup widget.
gitpod-io/website pull request #698
Opened 2021-06-28 15:33 UTC by nisarhassan12

Addresses part of #696

2021-06-28 22:26 UTC, mikenikles requested changes

2021-06-28 22:26 UTC, mikenikles commented on src/components/blog/newsletter-signup.svelte
> +  }
Could these class names be added to the markup below?

2021-06-28 22:26 UTC, mikenikles commented on src/components/blog/newsletter-signup.svelte
> +    // todo submit email
We shouldn't merge this PR until this is implemented, correct?

2021-06-29 00:27 UTC, nisarhassan12 commented on src/components/blog/newsletter-signup.svelte
> +    // todo submit email
Yep. I'll mark this Pr as a draft for now.

2021-06-29 00:34 UTC, nisarhassan12 commented on src/components/blog/newsletter-signup.svelte
> +  }
Thanks. Good Catch Done.

2021-06-29 06:32 UTC, ChristinFrohne commented
Thanks, @nisarhassan12 

- [ ] Why did you change the height of the "sign-in" button? It seems quite high right now and it doesn't align with the button height of the other buttons. Most of them are 46px high, but this button is 53px high. Please, check it. 

- [ ] I feel the call-out is a bit too "loud" right now. Could you decrease the font size? H3 instead of H2 and text-medium instead of text-large? Also, the email input field could be a bit less wide, I don't think anyone has such a long email address. 60% width works well. 
<img width="714" alt="Bildschirmfoto 2021-06-29 um 08 31 06" src="https://user-images.githubusercontent.com/46345125/123748376-6a0ecd80-d8b4-11eb-837b-400a7b2e59a8.png">

2021-06-29 16:17 UTC, nisarhassan12 commented on src/components/blog/newsletter-signup.svelte
> +  }
@mikenikles Sorry I have to revert this because of specificity issues adding the class names to markup does not have any impact.

2021-06-29 16:31 UTC, nisarhassan12 commented
Thanks, @ChristinFrohne I have made the requested changes:

| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/46004116/123834350-c7406880-d920-11eb-8170-6c96ea6d2812.png) | ![image](https://user-images.githubusercontent.com/46004116/123834317-bb54a680-d920-11eb-8289-8c9fbc7a11c9.png)  |

I have made the heading and text smaller as you suggested after that change to me the white container looked too big so I have reduced its width + padding which resulted in the decrease of the width for the input as well. Let me know what you think of this change ?

2021-06-30 06:32 UTC, ChristinFrohne commented
Looks great, thanks @nisarhassan12! 🎉

Handing it over to @jakobhero for the Segment integration now. 🙏

2021-06-30 19:27 UTC, mikenikles commented
Please let me know if I can help with anything. I'd also like to have a quick look before we merge it to understand the integration 🙏.

2021-06-30 20:38 UTC, mikenikles commented
Based on some quick research, we need a consent checkbox to be GDPR-compliant.

2021-06-30 20:47 UTC, mikenikles commented
🔓 I'm concerned about the current implementation due to privacy & security reasons.

Email addresses are sensitive and we should not use a client-side snippet to submit them. Anyone could take our implementation & Segment write key to add email addresses to our newsletter. FYI, the Segment docs recommend a server-side implementation for sensitive information ([link](https://segment.com/docs/guides/how-to-guides/collect-on-client-or-server/#sensitive-information))

A best practice approach is to performa a double opt-in flow where we ask users to verify their email address before we add them to the newsletter. Once they verify, we use server-side logic to submit the information to Segment.

In addition, we need a consent checkbox to be GDPR compliant based on a bit of research I did.

If the Segment write key in this PR is used anywhere else, please generate a new key so the one from this PR is invalidated.

2021-07-01 07:31 UTC, ChristinFrohne commented
Thanks @mikenikles for the legal research. I also did some research and came to the conclusion that this single opt sign-up works fine, as the data is given voluntarily, the user is informed about the impact of sharing the email and the user preformed a clear affirmative action, signifies agreement to the processing of personal data relating to him or her. 

We could consider adding a small footnote linking to the privacy policy like "You may opt-out any time. View our Privacy Policy."
Big companies like Forbes, smashing magazine, etc. do it similarly. 


"Checkboxes are necessary when you are trying to get consent for two separate things, such as a newsletter and advertising. If you don’t need to use checkboxes, it is much better to avoid them." [1]

Sources: 
1) https://www.mailerlite.com/blog/how-to-create-opt-in-forms-that-still-work-under-gdpr
2) https://www.termsfeed.com/blog/gdpr-email-newsletters/

2021-07-01 17:16 UTC, mikenikles commented
Nice find Christin 👍. Thanks for looking into that and what you found is a simpler implementation 🚀.

2021-07-02 14:38 UTC, mikenikles commented on src/components/blog/newsletter-signup.svelte
> +</style>
I see all class names applied to the markup directly, let's remove this style element.

2021-07-02 14:39 UTC, mikenikles commented on src/utils/analytics.js
> +(function () {
Let's remove this if we don't use it

2021-07-02 14:44 UTC, mikenikles commented on src/components/blog/newsletter-signup.svelte
> +        body: JSON.stringify(data.email.value),
We don't have to use `JSON.stringify` when the body is a string. This adds unnecessary "" around the email address which results in the following value stored in the spreadsheet:

![image](https://user-images.githubusercontent.com/788827/124291341-7ac47b00-db22-11eb-9728-e4bf5a047ed4.png)

2021-07-02 14:45 UTC, mikenikles commented
This works in the deployment preview now. The sheet in the spreadsheet didn't have any headers, which resulted in an error when we tried to persist the email address.

2021-07-02 15:07 UTC, nisarhassan12 commented on src/components/blog/newsletter-signup.svelte
> +</style>
Sorry, I should remove them from the markup having them on the markup does not work due to specificity issues due to conflicting styles specified via custom CSS. The following is how it looks without using the style tag which is not what we want:

![image](https://user-images.githubusercontent.com/46004116/124294231-e3d2df80-db70-11eb-8ba1-e82edf71d6bd.png)

I have remove those classes from the markup now.

2021-07-02 15:47 UTC, mikenikles approved these changes

2021-07-02 15:47 UTC, merged