[analytics] Add Segment tracking events
gitpod-io/website pull request #747
Opened 2021-07-09 16:48 UTC by atduarte

Implement Segment tracking events described in the tracking plan.

Missing:
* All `screencast_started` events
* All `feedback_submitted` events
* All `media_downloaded` events
* Events from the contact page
* Events from the media kit page
* Events from "Gitpod vs GitHub Codespaces" page

Out of scope:
* `newsletter_signup`

2021-07-09 16:50 UTC, atduarte commented on src/components/index/brand.svelte
> +      // TODO: Should we add a name (e.g. "amazon")?
@jakobhero

2021-07-11 17:06 UTC, jakobhero requested changes

2021-07-11 17:06 UTC, jakobhero commented on src/components/blog/blog-content-layout.svelte
> +              window.analytics.track("content_shared", {
I'm finding this name a little bit misleading now, please rename the event to 'content_share_clicked'.

2021-07-12 11:48 UTC, atduarte commented on src/components/index/get-started/project.svelte
> +      name: trackingName,
Added

2021-07-12 11:49 UTC, atduarte commented on src/components/blog/blog-content-layout.svelte
> +              window.analytics.track("content_shared", {
Changed

2021-07-12 15:19 UTC, jakobhero requested changes

2021-07-12 15:19 UTC, jakobhero commented on src/routes/contact.svelte
> +      subject: formData.selectedSubject.value,
We should also make an identify call here as the user passes a name and email address.

Did you omit the message body due to privacy concerns? If not, it should be included too!

2021-07-12 15:21 UTC, atduarte commented on src/components/index/get-started/project.svelte
> +      repoUrl: githubUrl,
Oops :)

2021-07-12 15:23 UTC, atduarte commented on src/components/youtube-embed.svelte
> +            name: embedId,
Only concern is that the name may change. Should we have both?

2021-07-12 15:26 UTC, atduarte commented on src/routes/contact.svelte
> +      subject: formData.selectedSubject.value,
I thought about identifying the user but was unsure as we don't validate that information and could be polluting the data. 

Yes, didn't include the message for privacy reasons.

2021-07-12 15:26 UTC, atduarte commented on src/routes/features.svelte
>          target="_blank">Learn more about sudo/Docker in Gitpod.</a
Oops, forgot to delete. Thank you

2021-07-12 16:00 UTC, jakobhero commented on src/routes/contact.svelte
> +      subject: formData.selectedSubject.value,
Fair enough, I generally find our authentication data more trustworthy than anything from a user form, but we could still track it if it's the only source of information we have, e.g. as `name_untrusted` and `email_untrusted`. That way we do not overwrite other traits.
I don't see the message as critical information for us at the moment, so I am cool with leaving it out for now.

2021-07-12 16:01 UTC, jakobhero commented on src/components/youtube-embed.svelte
> +            name: embedId,
yes, both is what i meant. the call should include `{id: embedId, name: title}` (or whatever the name of the variable containing the title is here).

2021-07-12 16:12 UTC, atduarte commented on src/routes/contact.svelte
> +      subject: formData.selectedSubject.value,
Makes sense. Added an identify before the track with those traits.

2021-07-13 08:28 UTC, jakobhero approved these changes
LGTM

2021-07-13 23:12 UTC, mikenikles commented on src/components/blog/blog-content-layout.svelte
> +              })}
🤔 Does this work? I don't see the API call to segment, but instead the page redirects to the social media site as defined in the `href` attribute.

2021-07-14 08:35 UTC, atduarte commented on src/components/blog/blog-content-layout.svelte
> +              })}
Do you have an ad blocker active? :)

2021-07-14 16:15 UTC, mikenikles commented on src/components/blog/blog-content-layout.svelte
> +              })}
I did when I reported it (forgot I installed it a few days ago to test a user report 😉). Once I removed it, the request to the Segment API is stuck in `pending` indefinitely (as in, at least 2+ minutes so far).

![image](https://user-images.githubusercontent.com/788827/125656011-09b70a98-99f1-4d5d-b6e9-4ad9b15dd958.png)

It's likely because the browser navigates away from the gitpod.io domain over to Reddit or Twitter without completing the XHR request first.

Do you see a successful API call to Segment in your dev tools' Network tab?

2021-07-14 16:31 UTC, atduarte commented on src/components/blog/blog-content-layout.svelte
> +              })}
Yes, I do. It's weird. Thought it might be because I was opening in a separate tab but works here nonetheless 🤔 
![image](https://user-images.githubusercontent.com/666176/125658519-41432e82-435a-4bd2-9941-2368ee44d078.png)

Btw an easier way to test is to use [Segment's debugger](https://app.segment.com/gitpod/sources/website_staging/debugger).

2021-07-14 16:40 UTC, mikenikles commented on src/components/blog/blog-content-layout.svelte
> +              })}
Turns out data is captured in Segment, so we're ok with this.

2021-07-14 16:58 UTC, merged