implement the segment call for email.
gitpod-io/website pull request #762
Opened 2021-07-19 11:01 UTC by nisarhassan12

2021-07-19 11:10 UTC, nisarhassan12 commented
André Duarte told me that: 

> problem of doing it in the frontend is that we don’t load segment when people have DoNotTrack activated. And currently, it also gets blocked by ad blockers

So we have to do this via a Netlify function.

2021-07-27 15:52 UTC, atduarte commented on src/functions/newsletter/_signup.ts
> +    anonymousId: nanoid(),
We should not generate a new anonymous id as we want to relate this activity to the rest of the user activity. The anonymous id is stored as a cookie.

Jakob did something similar in the server [here](https://github.com/gitpod-io/gitpod/blob/ea2780a9ce6f91919e5a24221dc4552c43afd1e6/components/server/src/auth/login-completion-handler.ts#L86).

2021-07-27 15:54 UTC, atduarte requested changes

2021-07-27 15:54 UTC, atduarte commented on src/functions/newsletter/_signup.ts
> +  analytics.track({
@jakobhero also mentioned we should have an identify() call, to associate the email to the anonymous user. We should define it as `email_untrusted` though, as we are not able to confirm that it is indeed their email.

2021-07-28 16:21 UTC, mikenikles commented on src/functions/newsletter/_signup.ts
> +    event: 'Signed Up',
@jakobhero Are you ok with that event name? If I recall we usually use the `signed-up` format 🤔.

2021-07-28 16:24 UTC, atduarte commented on src/functions/newsletter/_signup.ts
> +    event: 'Signed Up',
It should actually be `newsletter_signup` https://docs.google.com/spreadsheets/d/1m_-7uIcwA2fXVP_xv3tvLE1lV_hal8A4h9SBBOyTkck/edit#gid=0

2021-07-28 16:24 UTC, atduarte commented on src/functions/newsletter/_signup.ts
> +    email_untrusted: body,
What I meant is that a separate identify() call should be done with this property. This event should remain with `email`.

2021-07-28 16:24 UTC, mikenikles commented on src/functions/newsletter/_signup.ts
> +    anonymousId: nanoid(),
Thanks for the link, I see we use `request.cookies.ajs_anonymous_id`. When I look at my Gitpod workspace, I don't see the `ajs_anonymous_id` cookie set, neither do I when I open a workspace.

We can adjust the code to use that cookie, but in order to test I'll need to understand where it gets set. Can you provide instructions on how I can get that cookie set?

2021-07-28 16:27 UTC, atduarte commented on src/functions/newsletter/_signup.ts
> +    anonymousId: nanoid(),
Ad-blocker maybe? 
![image](https://user-images.githubusercontent.com/666176/127360517-a3d65509-05b7-4dfc-8b0a-068f9e35ed70.png)

2021-07-29 07:18 UTC, jakobhero commented on src/functions/newsletter/_signup.ts
> +    anonymousId: nanoid(),
> We can adjust the code to use that cookie, but in order to test I'll need to understand where it gets set. Can you provide instructions on how I can get that cookie set?
It should get set in the `page()` call when a user visits a gitpod.io site for the first time. For more context, see [here](https://segment.com/docs/guides/how-to-guides/collect-pageviews-serverside/).

2021-08-02 06:01 UTC, JohannesLandgraf commented
@mikenikles can we merge, anything still blocking here?

2021-08-02 14:13 UTC, atduarte commented
Looking into this (cc @mikenikles)

2021-08-02 15:35 UTC, atduarte commented
I was unable to test the netlify functions in the dev environment. 

Up for discussion: whether we want to move the Segment write keys to an env var.

2021-08-03 21:47 UTC, atduarte commented on src/functions/newsletter/index.ts
> +const signup = async (info: SignupInfo): Promise<void> => {
@mikenikles is having a separate `_signup` file a convention or it is only when there are multiple of these?

2021-08-06 16:29 UTC, closed without merging

2021-08-06 16:35 UTC, atduarte commented
Gitpod app must know whether an existing user subscribed to the newsletter in order to update their preferences.