adjust avatar links + share links.
gitpod-io/website pull request #764
Opened 2021-07-19 20:14 UTC by nisarhassan12

Fixes #691 + does a few other things:

Removes the extra `@` if the second or third author does not have a Twitter profile:

![image](https://user-images.githubusercontent.com/46004116/126221090-8349d2ce-4c82-4969-b194-97504f2f862b.png)

Set the Avatar links + share links target to `_blank`.

2021-07-26 02:07 UTC, mikenikles requested changes

2021-07-26 02:07 UTC, mikenikles commented on src/components/blog/blog-content-layout.svelte
> +  const renderTwittwrHandles = () => {
There's a spelling mistake in `renderTwittwrHandles`.

As an exercise, how about you try to rewrite this entire function as a one-liner? The following is a good start and from there, you should be able to use array functions to do the rest, possibly with a single [`reduce()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce).

```js
const renderTwitterHandles = () => author.split(", ").reduce();
```

2021-07-26 15:54 UTC, nisarhassan12 commented on src/components/blog/blog-content-layout.svelte
> +  const renderTwittwrHandles = () => {
Thanks @mikenikles I have fixed the spelling mistake and updated the implementation to use a single reduce now it is in theory a one liner with the explicit return but the formatter has made the code span multiple lines. I have also created a helper function + abstracted the `authors.split(", ")` in a variable for use in more then one place.

```ts
const hasATwitterProfile = (authorName) =>
  !!authors[authorName].socialProfiles.twitter;

const writers = author.split(", ");

const renderTwitterHandles = () =>
  writers.reduce(
    (accumlator, currentValue, currentIndex) =>
      accumlator +
      (writers[currentIndex + 1] &&
      hasATwitterProfile(writers[currentIndex + 1])
        ? `${
            hasATwitterProfile(writers[currentIndex])
              ? `@${currentValue}, `
              : ""
          }`
        : `${
            hasATwitterProfile(writers[currentIndex])
              ? `@${currentValue}`
              : ""
          }`),
    ""
  );
```

The previous implementation was quite hard to read and understand and looked quite complex but what we have got with `.reduce` is not satisfying either.

```ts
const renderTwittwrHandles = () => {
  let writers = author.split(", ");
  let result = "";
  for (let i = 0; i < writers.length; i++) {
    if (
      authors[writers[i]].socialProfiles.twitter &&
      authors[writers[i + 1]] &&
      authors[writers[i + 1]].socialProfiles.twitter
    ) {
      result += `@${authors[writers[i]].socialProfiles.twitter}, `;
    } else if (authors[writers[i]].socialProfiles.twitter) {
      result += `@${authors[writers[i]].socialProfiles.twitter}`;
    }
  }

  return result;
};
  ```

2021-07-28 16:36 UTC, mikenikles commented on src/components/blog/blog-content-layout.svelte
> +  const renderTwittwrHandles = () => {
As discussed on the call, let's use an author's full name if they don't have a Twitter handle instead of omitting them completely.

Also, to simplify the code, you can concatenate names + , and remove the trailing `, ` at the end of the function.

2021-07-29 18:33 UTC, merged