lock overflow-y when the menu or a modal is open.
gitpod-io/website pull request #766
Opened 2021-07-20 09:25 UTC by nisarhassan12

Fixes #738 

This Pr does the following 2 things:

- When the mobile menu items are shown it locks the scrolling in y directing as is commonly on the web.
- Does the same as above the modal is shown.

2021-07-20 10:16 UTC, nisarhassan12 commented
@ChristinFrohne for us locking the overflow when the menu items are shown causes things to grow which looks quite bad. One way to make it look good would be to have the menu items take up 100% of the viewport height as is the case for nav menus on Vercel, Netlify.

https://user-images.githubusercontent.com/46004116/126306902-ca42249c-77ab-4250-aeb9-d5b2dea4c7b2.mp4

2021-07-21 13:13 UTC, ChristinFrohne commented
@nisarhassan12 I just tested it and it looks good. The menu items don't take 100% height of the viewport and the background page is not scaling weirdly.

2021-07-26 01:54 UTC, mikenikles requested changes

2021-07-26 01:54 UTC, mikenikles commented on src/components/main-nav/mobile-menu/toggle.svelte
> +      html.style.overflowY = 'hidden';
Please use Tailwind CSS classes.

2021-07-27 06:41 UTC, merged