add Gitpod vs Codespaces landing page.
gitpod-io/website pull request #772
Opened 2020-09-28 12:07 UTC by nisarhassan12

Fixes gitpod-io/website#766

2020-09-30 11:56 UTC, ChristinFrohne requested changes
Thanks, it already looks great. 

- [x] please have the footnotes below the gray box and smaller

- [ ] the tooltips should appear on click, so that you have a chance to click on "learn more". The font should be regular 

- [x] the tooltips should be placed in the middle of the text (currently it's slightly above)

- [x] the browser-extension-button should link directly to the Chrome or Firefox extension. Depending on if the user is currently using a Chrome or Firefox browser, he/she should be forwarded to the correlating extension. 

We are still discussing some changes about the graphic. I'll get back to you with that feedback shortly.

2020-09-30 11:56 UTC, ChristinFrohne commented on src/pages/gitpod-vs-codespaces.tsx
> +                <th>Pricing(Hosted)</th>
add spacing

2020-09-30 11:56 UTC, ChristinFrohne commented on src/pages/gitpod-vs-codespaces.tsx
> +                <td>Free for 50h/month</td>
Change to "Free for Open-Source"

2020-09-30 11:56 UTC, ChristinFrohne commented on src/pages/gitpod-vs-codespaces.tsx
> +                <th>iPad support</th>
Please use a capital "S" for "support"

2020-09-30 12:55 UTC, jankeromnes commented
Many thanks for the excellent work @nisarhassan12!

---

<img width="600" alt="Screenshot 2020-09-30 at 14 41 16" src="https://user-images.githubusercontent.com/599268/94686362-05294580-032b-11eb-8533-132a86c2884a.png">

@ChristinFrohne Random thought, what you do think about using `+` instead of `,`? E.g.:

> Experience Gitpod, the [fast](#) + [cost-effective](#) + [open-source](#) alternative to Codespaces.

---

<img width="600" alt="Screenshot 2020-09-30 at 14 42 50" src="https://user-images.githubusercontent.com/599268/94686527-3d308880-032b-11eb-8aff-73c2becc6a84.png">

The widths in the graphic should be proportional to the values:

- [ ] Codespaces' "Loading" bar (5min) should be 5x larger than Gitpod's (1min) -- currently it seems to be only ~2.5x larger

- [ ] Codespaces' "Project Build" (10min) should be 2x larger than the "Loading" bar (5min) -- currently it also seems to be ~2.5x larger

---

<img width="400" alt="Screenshot 2020-09-30 at 14 46 53" src="https://user-images.githubusercontent.com/599268/94686934-d069be00-032b-11eb-816f-57c094ae3084.png">

There is already the "Last verified" text below with a date. So, please remove "as of September 2020" in the "(16 vCPU / 60GB RAM as of September 2020)".

Also the new values should be:

> (16 vCPU / 64GB RAM)

Because we're upgrading the nodes.

---

<img width="600" alt="Screenshot 2020-09-30 at 14 48 47" src="https://user-images.githubusercontent.com/599268/94687121-14f55980-032c-11eb-914b-65a428df29e4.png">

- [ ] Please reduce the vertical empty space between the column headers (e.g. "Gitpod") and the first element (e.g. "Free for 50h/month")

- [ ] Please left-justify the "Self-Host on X" texts (all the "Self-Host" words should be vertically alligned to the left, regardless of logo width -- also it should be "Self-Host" and not "Self Host")

---

<img width="600" alt="Screenshot 2020-09-30 at 14 51 42" src="https://user-images.githubusercontent.com/599268/94687432-892ffd00-032c-11eb-8e6d-ae53e43795d6.png">

- [ ] Please correctly format the number (`,` instead of `.`), and use the new value "Used by 250,000+ Developers & Businesses"

- [ ] Please remove the Mozilla logo, and add the GitLab logo to the left, as in the mockup

2020-09-30 13:50 UTC, ChristinFrohne commented
Great feedback, thanks @jankeromnes 

>Experience Gitpod, the fast + cost-effective + open-source alternative to Codespaces

I prefer it the way it is. The "-" in cost-effective might look like a minus sign. Also, I'd expect an equation.

2020-10-01 12:08 UTC, nisarhassan12 commented
> the browser-extension-button should link directly to the Chrome or Firefox extension. Depending on if the user is currently using a Chrome or Firefox browser, he/she should be forwarded to the correlating extension.

@ChristinFrohne Thanks for pointing this out it will hopefully make the UX a lot better. What to do in case where the browser does not have the extension available for it let say Safari, for instance, we have a lot fo users from there I think Maybe link to the Chrome extension? What do you say? Thanks

2020-10-02 10:36 UTC, ChristinFrohne commented
Thanks for the adjustments. Here some more comments:

- [ ] please have the footnote smaller and with less spacing to the box above

- [ ] link "Sources: Gitpod Pricing, Codespaces Pricing." to each pricing page. (Codespaces: https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/about-billing-for-codespaces)

- [ ] tooltip: the hover works great now. Thanks! Please give the text inside the tooltip a bit more margin to the left and the edges of the box should be slightly round

- [ ] All boxes should have slightly round corner. I think we set it to 3px. please adjust that to the two boxes comparing Gitpod and Codespaces as well

- [ ] typo: "coming soon" 

- [ ] the disclaimer should also have a smaller font size (the same as the footnotes)

- [ ] switch the section "used by" and "install browser extension", so the CTA button appears a bit sooner

Mobile view:

- [ ] have the same width for both columns
<img width="969" alt="Bildschirmfoto 2020-10-02 um 12 23 46" src="https://user-images.githubusercontent.com/46345125/94913848-472cc580-04aa-11eb-958d-ea9466762a34.png">

- [ ] adjust the spacing for the footnotes (and have them smaller) so that the main text is easier to read
<img width="671" alt="Bildschirmfoto 2020-10-02 um 12 24 35" src="https://user-images.githubusercontent.com/46345125/94913917-6297d080-04aa-11eb-9977-4667428d424c.png">

2020-10-02 14:48 UTC, nisarhassan12 commented
>  All boxes should have slightly round corner. I think we set it to 3px. please adjust that to the two boxes comparing Gitpod and Codespaces as well

Sorry, I gave this a try can we skip this for now? Is that too important?

2020-10-03 16:11 UTC, nisarhassan12 commented
@ChristinFrohne I have made some new changes and also updated the Graphics please have a look whenever you'll have time. Thanks

2020-10-06 09:11 UTC, ChristinFrohne commented
Cool, thanks!

- [ ] the link in the sub headline "resource-efficient" is not working

- [ ] please make sure that the first graphic is aligned with the "log in" button. Currently it's a bit too wide

- [ ] first graphic: there should be no white space between the two vertical lines and the horizontal bars

- [ ] the "loading" bar should be exactly half the size of the "project build" bar

- [ ] the size of the footnotes are inconsistent. Please always use the smaller size (like underneath the comparison table) and they should be left aligned with the gray box (see mockup)

- [ ] can we have the link to GCP directly in the 1? It takes too much attention in the lonely footnote, I feel.

- [ ] have less spacing after the comparison table and the CTA

- [ ] have more spacing above the headline (and a smaller footnote), so that there is a clear hierarchy (mobile view)
![Screenshot 2020-10-06 110904](https://user-images.githubusercontent.com/46345125/95182048-64bca080-07c4-11eb-8d3e-df1b0e45d42e.png)


after you addressed these comments, the PR can be merged, so I can share it with the new editors. Further changes we can address in a separate PR. Thanks!

2020-10-06 14:24 UTC, nisarhassan12 commented
>  first graphic: there should be no white space between the two vertical lines and the horizontal bars

@ChristinFrohne there is already no space or did you meant something else? 

![image](https://user-images.githubusercontent.com/46004116/95214680-94da6280-0809-11eb-9544-e1bde6106640.png)

2020-10-06 16:44 UTC, nisarhassan12 commented
>  the size of the footnotes are inconsistent. Please always use the smaller size (like underneath the comparison table) and they should be left-aligned with the grey box (see mockup)

I have made the font size smaller. FYI alll the footnotes had the same size earlier i.e the ones under the graphics and the one under the Comparison Table.

Regarding the alignment, I tried to get it as it is in the mockup but unable to do so. Should I retry or Is it ok the way it is ? Thanks.

2020-10-07 08:18 UTC, ChristinFrohne commented
The changes look good, thanks! 

Last small adjustments:

- [ ] we simplified the first graphic again. Please adjust it accordingly. Sorry about the back and forth (I updated the mockup)

- [ ] remove the headline of the second graphic and add it to the footnotes (see mockup)

- [ ] there is still too little space between the graphic/footnotes and the headlines on mobile view. Please add more space 
<img width="463" alt="Bildschirmfoto 2020-10-07 um 10 15 02" src="https://user-images.githubusercontent.com/46345125/95305505-5a62db00-0886-11eb-81b5-ef9c6e96bac6.png">


after this version is merged, it would be great if you could have a look at a better mobile view for the table. (see https://www.pipedrive.com/en/crm-comparison/copper-alternative for inspiration)

2020-10-07 08:21 UTC, ChristinFrohne commented on src/contents/gitpod-vs-codespaces.tsx
> +          Gitpod removes long init and build times by continuously pre-building workspaces for your project, allowing you to start coding or
The sentence is quite long and thereby difficult to read. Let's break it into two sentences 
"Gitpod removes long init and build times by continuously pre-building workspaces for your project. Thereby it allows you to start coding or debugging immediately, from any context, at any time. "

2020-10-07 08:21 UTC, ChristinFrohne approved these changes

2020-10-07 15:35 UTC, merged