Address Lighthouse Reports
gitpod-io/website pull request #804
Opened 2021-08-01 20:22 UTC by nisarhassan12

Addresses #135

2021-08-10 21:31 UTC, nisarhassan12 commented
@ChristinFrohne I ran the audits for all the pages of the site apart from the older blog posts that were like more than 8 months old. 

I noticed some small issues on a few pages listed here https://www.gitpod.io/docs/languages-and-frameworks which I have ignored because they were really minor. I could look into those if you say they are not straightforward to fix.

2021-08-11 09:07 UTC, nisarhassan12 commented
Thanks, @ChristinFrohne I just want you to run LightHouse on a few pages to see the improvements yourself otherwise I'm sure of the changes and improvements made here. 

There are few text changes in this PR. It would be nice if you go over them and let me know if they look good to you. You can view the text changes view going through https://github.com/gitpod-io/website/pull/804/files 
![image](https://user-images.githubusercontent.com/46004116/129001774-21b2ffa0-7e5c-4c33-959c-873d4dc07bb8.png)

2021-08-12 09:29 UTC, ChristinFrohne requested changes

2021-08-12 09:29 UTC, ChristinFrohne commented on src/contents/pricing.ts
> +    btnText: "Learn More about Self Hosted",
Let's shorten it to "More about Self-Hosted"

2021-08-12 09:29 UTC, ChristinFrohne commented on src/routes/docs/languages/javascript.md
> +You can read more about start tasks [on this page](/docs/config-start-tasks).
Shorten it to "Read more about **start tasks**"

2021-08-16 15:51 UTC, nisarhassan12 commented on src/contents/home/index.ts
> +    title: "Go Programming Language",
We can use the word Golang as is the case for the title of its website https://golang.org/ 
![image](https://user-images.githubusercontent.com/46004116/129592151-4eec224e-8fb6-49d2-861e-e3baa6cb004e.png)

2021-08-16 15:53 UTC, nisarhassan12 commented on src/routes/docs/quickstart/go.md
> +Learn how to set-up and understand the benefits of Gitpod **in less than 5 min** with our [Go Programming Language](https://github.com/gitpod-io/template-golang-cli) template.
https://github.com/gitpod-io/website/pull/804#discussion_r689657081

2021-08-17 12:14 UTC, merged