Add DevX Digest 1 onto the website
gitpod-io/website pull request #819
Opened 2021-08-05 11:43 UTC by pawlean

We released DevX Digest yesterday 🎉 and wanted to get this content on the blog too.

2021-08-05 12:19 UTC, ChristinFrohne requested changes
Looks awesome! Thanks for sticking to the [design guidelines](https://www.notion.so/Blogging-34c2e078569b4174b42784854f42549f) 🎯 🎉

**Minor comments:**

- [ ] it's best to open external links in a new tab (e.g. Twitter handles or YouTube links). EDIT: I just noticed that's a general issue for all blog posts. Could you fix that @nisarhassan12 ? 🙏

- [ ] you still need a preview text 
<img width="441" alt="Bildschirmfoto 2021-08-05 um 14 14 55" src="https://user-images.githubusercontent.com/46345125/128348582-69b1a12b-2ed2-4d14-becf-b14b0581469c.png">

2021-08-05 12:46 UTC, pawlean commented
> Looks awesome! Thanks for sticking to the [design guidelines](https://www.notion.so/Blogging-34c2e078569b4174b42784854f42549f) 🎯 🎉
> 
> **Minor comments:**
> 
> * [ ]  it's best to open external links in a new tab (e.g. Twitter handles or YouTube links). EDIT: I just noticed that's a general issue for all blog posts. Could you fix that @nisarhassan12 ? 🙏
> * [x]  you still need a preview text
> 
> <img alt="Bildschirmfoto 2021-08-05 um 14 14 55" width="441" src="https://user-images.githubusercontent.com/46345125/128348582-69b1a12b-2ed2-4d14-becf-b14b0581469c.png">

Thanks Christin, always good to get another pair of eyes. 👀  I've updated the excerpt now!

2021-08-05 20:02 UTC, mikenikles approved these changes
Excellent, I'll solicit your feedback about the code structure very soon :).

One nitpick, could you use a lower case file name for `static/images/blog/the-evolution-of-devx/Source.png` please?!

Otherwise, LGTM 👍

2021-08-05 21:33 UTC, nisarhassan12 commented
> - [ ] it's best to open external links in a new tab (e.g. Twitter handles or YouTube links). EDIT: I just noticed that's a general issue for all blog posts. Could you fix that @nisarhassan12 ? 🙏

Thanks, @ChristinFrohne for bringing this up. For the author avatars and social share buttons, they already open up a new tab I addressed those in some recent PRs. For the rest of the links within the post body I'll make a PR soon.

2021-08-09 03:54 UTC, nisarhassan12 commented
I'll take over this Pr to update the layout as asked in https://github.com/gitpod-io/website/issues/827

2021-08-09 10:04 UTC, pawlean commented
> I'll take over this Pr to update the layout as asked in #827

Cheers! Let me know if you need anything from me.

2021-08-09 12:29 UTC, ChristinFrohne reviewed
Just a few inlined comments. Feel free to merge the PR after they have been addressed. Thanks!

2021-08-09 12:29 UTC, ChristinFrohne commented on src/components/blog/digest-header.svelte
> +  <p>Short explanation</p>
please use the same font size as for the description on /changelog. -> 16px instead of 18px

2021-08-09 12:29 UTC, ChristinFrohne commented on src/components/blog/digest-header.svelte
> +  <p>Short explanation</p>
@pawlean here you should add a short explanation about the DevX Digest

2021-08-09 12:29 UTC, ChristinFrohne commented on src/components/twitter-follow-button.svelte
> +  href="https://www.twitter.com/gitpod"
@nisarhassan12 the twitter link should open in a new tab. 
@pawlean we could also consider using the DevX Conf handle. Let's discuss that and if needed adjust that in a follow-up PR

2021-08-09 12:31 UTC, nisarhassan12 commented on src/components/blog/digest-header.svelte
> +  <p>Short explanation</p>
She already did that here https://github.com/gitpod-io/website/pull/819/commits/d0f5d4b557c258036d458ca413d6fdf572e60d1f Maybe the deploy preview was not ready when you were reviewing.

2021-08-09 16:44 UTC, merged