Replace references to TypeFox with Gitpod
gitpod-io/website pull request #857
Opened 2020-12-02 08:01 UTC by AlexTugarev

2020-12-07 08:47 UTC, gtsiolis reviewed
Hey @AlexTugarev! Added two questions below. /cc @svenefftinge

2020-12-08 07:55 UTC, JohannesLandgraf commented on src/pages/privacy.tsx
> +				<a href="mailto:data@gitpod.io">data@gitpod.io</a>.
Yes data@gitpod it does - its an alias from contact@ if I remember correctly

2020-12-08 07:56 UTC, JohannesLandgraf commented on src/components/Footer.tsx
> +                <p>Copyright © <a href="https://www.gitpod.io/" target="_blank" rel="noopener" title="Gitpod">Gitpod</a></p>
I would say yes, but @meysholdt should have a look as well

2020-12-08 12:06 UTC, meysholdt requested changes
Thx for making this change. Please
* remove the phone number. We want people to send us an email and not cold-call us.
* fix the PLZ to be `24143`. The current `23143` is just wrong.

All other changes look good.

2020-12-08 12:06 UTC, meysholdt commented on src/pages/imprint.tsx
>                  <p>Phone:&nbsp;+49-431-99026870
Let's remove the phone number; We want people to send us an email, not phone us.

2020-12-08 12:06 UTC, meysholdt commented on src/pages/privacy.tsx
> +							Eysholdt, Dr. Jan K&ouml;hnlein <br /> Phone: +49-431-99026870<br /> Email: contact@gitpod.io
remove phone, like above.

2020-12-08 12:06 UTC, meysholdt commented on src/pages/terms.tsx
> +                    /> 23143 Kiel/Germany<br /> Phone: +49-431-99026870<br /> Email: contact@gitpod.io
remove phone, like above.

2020-12-08 12:06 UTC, meysholdt commented on src/pages/terms.tsx
> +                    To<br /> Gitpod GmbH represented by: Sven Efftinge, Moritz Eysholdt, Dr. Jan Köhnlein<br /> Am Germaniahafen 1<br />				23143
PLZ is `24143`

2020-12-08 12:06 UTC, meysholdt commented on src/pages/terms.tsx
> +                    /> 23143 Kiel/Germany<br /> Phone: +49-431-99026870<br /> Email: contact@gitpod.io
PLZ is `24143`

2020-12-08 12:06 UTC, meysholdt commented on src/pages/terms.tsx
> +                    1, 23143 Kiel, Germany, registered at the commercial registry of the district court of Kiel under HRB 22228, represented
PLZ is `24143`

2020-12-08 13:49 UTC, AlexTugarev commented on src/pages/imprint.tsx
>                  <p>Phone:&nbsp;+49-431-99026870
done

2020-12-08 13:49 UTC, AlexTugarev commented on src/pages/terms.tsx
> +                    /> 23143 Kiel/Germany<br /> Phone: +49-431-99026870<br /> Email: contact@gitpod.io
done

2020-12-08 13:49 UTC, AlexTugarev commented on src/pages/terms.tsx
> +                    1, 23143 Kiel, Germany, registered at the commercial registry of the district court of Kiel under HRB 22228, represented
done

2020-12-10 16:26 UTC, gtsiolis commented on src/components/Footer.tsx
> +                <p>Copyright © <a href="https://www.gitpod.io/" target="_blank" rel="noopener" title="Gitpod">Gitpod</a></p>
Footer copyright notice has been changed in https://github.com/gitpod-io/gitpod/commit/6d72a5f236754595a8231bf58eb42a049c22291a#diff-969b5d5d2ed9bd64c15778c95ed8d4a01614094657a22623ec767ded22246123R36.

There are still ~1500 instances in comments in code in case we want to change these, too. We can open a follow up issue for these if needed.

2020-12-10 16:43 UTC, AlexTugarev commented on src/components/Footer.tsx
> +                <p>Copyright © <a href="https://www.gitpod.io/" target="_blank" rel="noopener" title="Gitpod">Gitpod</a></p>
> There are still ~1500 instances in comments in code in case we want to change these, too. We can open a follow up issue for these if needed.

that's likely the copyright headers, no? we keep it as is.
/cc @svenefftinge

2020-12-10 16:43 UTC, AlexTugarev commented on src/components/Footer.tsx
> +                <p>Copyright © <a href="https://www.gitpod.io/" target="_blank" rel="noopener" title="Gitpod">Gitpod</a></p>
> Footer copyright notice has been changed in gitpod-io/gitpod@6d72a5f#diff-969b5d5d2ed9bd64c15778c95ed8d4a01614094657a22623ec767ded22246123R36.

yes, in alignment. 
@gtsiolis, I don't get the point :-(

2020-12-10 16:56 UTC, gtsiolis commented on src/components/Footer.tsx
> +                <p>Copyright © <a href="https://www.gitpod.io/" target="_blank" rel="noopener" title="Gitpod">Gitpod</a></p>
> that's likely the copyright headers, no? we keep it as is.

💯 

>  I don't get the point

@AlexTugarev just posting this here for visibility and awareness for the rest of the team. 👀

2020-12-10 17:48 UTC, svenefftinge approved these changes

2020-12-10 17:51 UTC, merged