[docs] Added Next Steps section
gitpod-io/website pull request #898
Opened 2020-12-10 13:03 UTC by JohannesLandgraf

To have a more linear reading/onboarding flow within our docs I added a Next Steps section for the Getting Started Guide.

2020-12-16 07:46 UTC, gtsiolis requested changes
LGTM @JohannesLandgraf! I have one nitpick suggestion. Other than that, looks good!

2020-12-16 07:46 UTC, gtsiolis commented on src/docs/getting-started.md
> +- [Forem](https://gitpod.io/#https://github.com/thepracticaldev/dev.to) powering [dev.to](https://dev.to/)
**nitpick**: Let's link to the new canonical URL here. Also, do we need to reference `dev.to` here? I'm fine with leaving the reference.

```suggestion
- [Forem](https://gitpod.io/#https://github.com/forem/forem) powering [dev.to](https://dev.to/)
```

2020-12-16 07:46 UTC, gtsiolis commented on src/docs/getting-started.md
> +See for yourself and try opening some of our favorite OSS projects out there:
**thought**: Consistency in copy voice and tone would be good long term. Let's leave this as is for now.

2020-12-16 07:46 UTC, gtsiolis commented on src/docs/getting-started.md
> +With Gitpod you start treating your dev environments as something ephemeral: you start them, you code, you push your code, and you forget about them. For your next task, you'll use a fresh dev enviro
**thought**: I think it would be nice to consistently use the same terms like ephemeral v. disposable. Food for thought. 🍔

2020-12-16 08:47 UTC, JohannesLandgraf commented on src/docs/getting-started.md
> +With Gitpod you start treating your dev environments as something ephemeral: you start them, you code, you push your code, and you forget about them. For your next task, you'll use a fresh dev enviro
Yes 💯 agree

2020-12-16 09:17 UTC, gtsiolis commented
Thanks @JohannesLandgraf! Alright, let's merge this! 🚀

2020-12-16 09:18 UTC, merged

2020-12-16 09:24 UTC, gtsiolis commented on src/docs/getting-started.md
> +With Gitpod you start treating your dev environments as something ephemeral: you start them, you code, you push your code, and you forget about them. For your next task, you'll use a fresh dev enviro
**thought**: This is duplicate information from the _Introduction_ section, see [diff](https://github.com/gitpod-io/website/commit/f4d1e8ccf958e82c01a9c4415869cfe807c0abb6#diff-b70dff99d4f3f9fdaef4ec2b836f03dfc2b9c813fcaf72672623d8e4d6686dfdR66). In the future, it could be best to try minimizing duplicate information and have a single source of truth for everything. This can help avoid inconsistent content structure, updating the same piece of information in multiple places, and more. /cc @JohannesLandgraf

2020-12-17 11:51 UTC, JohannesLandgraf commented on src/docs/getting-started.md
> +With Gitpod you start treating your dev environments as something ephemeral: you start them, you code, you push your code, and you forget about them. For your next task, you'll use a fresh dev enviro
Agree. But as our documentation flow is not linear several people might _land_ on the "Getting started page" and never read the introduction section. As we have to get better to convey the ephemeral nature of Gitpod I think it makes sense to highlight/repeat specific aspects as long as we are not doing that within the product (onboarding).

2020-12-17 12:17 UTC, gtsiolis commented on src/docs/getting-started.md
> +With Gitpod you start treating your dev environments as something ephemeral: you start them, you code, you push your code, and you forget about them. For your next task, you'll use a fresh dev enviro
@JohannesLandgraf Fair point! 🏀