feat: update navbar
gitpod-io/website pull request #898
Opened 2021-08-29 13:27 UTC by Cahllagerfeld

closes #892 

- [ ] Added Signup Button
- [ ] show and remove navbar-items

Things to discuss:

- [ ] Action for Sign-Up-Button
- [ ] Navbar on Mobile Sticky as well?
- [ ] transition needed?

2021-08-31 17:32 UTC, Cahllagerfeld commented
Hey @gtsiolis, 
I don't know exactly who to ask about the open points I specified in the PR-description.
I was hoping that you can answer (at least some of) them or tell me who to ask. 😄😅 
Many thanks in advance (:

2021-08-31 18:13 UTC, gtsiolis commented
Hey @Cahllagerfeld! Thanks for contributing! 💯 

Looping in @ChristinFrohne as the relevant issue author and @nisarhassan12 as both could help answering the pending questions! 🏀 

FWIW, if the pending questions involve topics that are not described in the original issue, opening one or more follow-up issues for continueing the discussion for each topic is a good way forward. However, I'll let @ChristinFrohne and @nisarhassan12 take it from there. 🏓

2021-08-31 18:20 UTC, Cahllagerfeld commented
thank you so much for your quick reply!!

2021-08-31 19:06 UTC, nisarhassan12 commented
@Cahllagerfeld Sorry for not getting back to you earlier regarding the questions. 

> Navbar on Mobile Sticky as well?
Yep. As is the case with the Vercel Navigation. 

> transition needed?
Yep.

> Action for Sign-Up-Button

Just add a link to the get started section i.e with `href="/#get-started"`

>  I feel very uncomfortable with pinging people directly 😅😬

Always feel free to ping me anytime 🙂. Let me know in case you need help with anything or have further questions. Thanks

2021-08-31 19:09 UTC, Cahllagerfeld commented
Thank you for the answers :D I'll have a look at the things tomorrow (:

2021-09-01 05:57 UTC, Cahllagerfeld commented
The header looks fine on mobile now and is sticky when scrolling:
![grafik](https://user-images.githubusercontent.com/43843195/131619309-975ea1d2-a775-4f32-b452-b1e22008095a.png)

The only thing that I currently dont know how to solve is the following issue: 
![grafik](https://user-images.githubusercontent.com/43843195/131619386-a9e27606-6605-413a-8e80-bbeca06b2710.png)
The header is fixed, because of that the opened Navbar sticks to the top and isn't visible if scrolled down too far.

Do you have any idea how to resolve this issue, that the navbar is always visible and not fixed at the top when opening the navbar?

2021-09-01 08:44 UTC, nisarhassan12 commented
> Do you have any idea how to resolve this issue, that the navbar is always visible and not fixed at the top when opening the navbar?

Thanks @Cahllagerfeld I'm looking into it will push a fix.

2021-09-01 08:54 UTC, Cahllagerfeld commented
Awesome!!
In case you are busy or you have an idea, let me know (: I can have a look at it later as well

2021-09-02 05:35 UTC, Cahllagerfeld commented
The changes you added look insane! o.O

2021-09-02 05:39 UTC, Cahllagerfeld reviewed
Just one small thing :D

2021-09-02 05:39 UTC, Cahllagerfeld commented on src/components/index/get-started/index.svelte
> +<Section id="get-started" class="pt-20">
I came over this thing as well, but I decided then to add the `pt-20` to all sections, because if adding this only to the `get-started` the spacing between this section and the one above is bigger tham the spacing betweeen the other sections isnt it?

2021-09-02 05:59 UTC, nisarhassan12 commented on src/components/index/get-started/index.svelte
> +<Section id="get-started" class="pt-20">
You're right. It is in fact the case on the other hand If we update it globally for all the sections via doing `:global(Section)` it only updates the spacing for the section components and we have many other elements in place like headers, articles and so on. If we go the route of updating the spacing for the `Section` components I think we should have to update/adjust the spacing in other places as well. 

To fix the issue you specified I have added a negative margin to the above section i.e -mt-20 in https://github.com/gitpod-io/website/pull/898/commits/d13b8be4ba5196e51b2c58d898594b0072f86c06

2021-09-02 06:12 UTC, nisarhassan12 commented
Sorry @Cahllagerfeld It was your PR it should have been like I reviewed and specified all the things that needed to be addressed/fixed in review comments with pointers. 

I saw too many things needing adjustments and we want to get this PR live soon so I sort of fully took over your PR without asking you. Sorry for that.

2021-09-02 06:14 UTC, Cahllagerfeld commented
> 
> 
> Sorry @Cahllagerfeld It was your PR it should have been like I reviewed and specified all the things that needed to be addressed/fixed in review comments with pointers.
> 
> I saw too many things needing adjustments and we want to get this PR live soon so I sort of fully took over your PR without asking you. Sorry for that.

Dont worry 😄

2021-09-02 10:32 UTC, nisarhassan12 commented
I almost forgot one thing and that is that the Strike Through animation no longer works because the nav itself is an observer target that never leaves the screen now. @Cahllagerfeld Is this something you would be interested in helping out with ? If you don't have time. I'll push a fix at night.

2021-09-02 18:22 UTC, Cahllagerfeld commented
Sorry for not responding :( Unfortunately I didnt find enough time to work on a fix for this today. I hope its fine when you push the fixes tonight.

2021-09-03 09:37 UTC, ChristinFrohne requested changes
Awesome change. Thanks a lot @Cahllagerfeld  and @nisarhassan12  🧡 🎉

Once the new onboarding flow is live, we can reconsider here as well linking the "sign up" button to /login followed by /new (see[ former discussion](https://github.com/gitpod-io/website/issues/907#issuecomment-910301281), cc @gtsiolis )

- [x] when clicking on the Gitpod logo, the page should be scrolling up to the start (similar to how it's done at Vercel) 
- [ ] on mobile: the logo size in the nav bar and the height of the nav bar can be reduced a bit
- [ ] the opacity/blur change doesn't work well yet on Firefox. On Chrome it's awesome!

|Chrome|Firefox|
|-|-|
|<img width="524" alt="Bildschirmfoto 2021-09-03 um 11 30 54" src="https://user-images.githubusercontent.com/46345125/131984005-6b55a746-e943-4156-8b4b-4c9b22635262.png">|<img width="638" alt="Bildschirmfoto 2021-09-03 um 11 30 58" src="https://user-images.githubusercontent.com/46345125/131984026-39224c5f-cc2f-4095-a477-601a77ece388.png">|

2021-09-05 07:51 UTC, Cahllagerfeld commented
The not-blurred navbar seems to be a firefox-related problem
![grafik](https://user-images.githubusercontent.com/43843195/132119575-4cb925f5-8c50-42a8-9f70-b6a5360c6774.png)

it seems like this css-feature is disabled in firefox by default..

I was able to get it running when calling `about:config` in firefox and then enabling `backdrop-filter` manually.

In my opinion thats not a viable way though, at least for firefox tho

2021-09-06 19:38 UTC, nisarhassan12 commented
> - [x]  when clicking on the Gitpod logo, the page should be scrolling up to the start (similar to how it's done at Vercel)

Done ✔️ @ChristinFrohne I personally don't like the fact that clicking on the Logo does not takes you to the home page just the top of the page which you're currently on making it a bit harder to navigate back to the home. I would personally avoid following what Vercel is doing here in this regard.  What do you say if we make the click on the Gitpod logo take the user at the top of the home page ?

2021-09-07 07:58 UTC, ChristinFrohne commented
>What do you say if we make the click on the Gitpod logo take the user at the top of the home page ?

I agree, let's do that!

The size of the nav bar on mobile is good now, but the logo is still quite large. Could you reduce the size a bit and thereby give it some more white space? 
<img width="456" alt="Bildschirmfoto 2021-09-07 um 09 55 19" src="https://user-images.githubusercontent.com/46345125/132306800-c208974f-01db-453e-a3e7-1387c9ad7ab4.png">


Afterward it's ready to be merged 🎉

2021-09-08 15:16 UTC, merged

2021-09-08 21:33 UTC, mikenikles commented on src/components/main-nav/nav-item.svelte
> +  export let navItem;
@Cahllagerfeld @nisarhassan12 it looks like we lost the Typescript type here. There's a pre-push hook that should fail and stop anyone from pushing code with missing types.

Other than manually skipping this, I can't explain why anyone was able to push the code without type. I'll fix it in a PR I've got open at the moment.

2021-09-13 05:03 UTC, nisarhassan12 commented on src/components/main-nav/nav-item.svelte
> +  export let navItem;
Thanks. @mikenikles it was accidentally done by me When I tried the push button in the bottom left it gave me a misleading permission error rather than telling me that it is actually the pre-push hook that is failing it showed me the following. I thought it might be because @Cahllagerfeld has revoked Gitpod some write access and because of that, I can no longer push to his fork via Gitpod so I manually made the changes via the GitHub edit option and made the commit directly. 

![Screen Shot 2021-09-13 at 9 41 30 AM](https://user-images.githubusercontent.com/46004116/133025122-8013bde4-4005-4553-a464-501052227891.png)

![Screen Shot 2021-09-13 at 9 43 10 AM](https://user-images.githubusercontent.com/46004116/133025190-a227f909-9fe4-411a-963e-47e12ddd052a.png)

2021-09-13 05:57 UTC, Cahllagerfeld commented on src/components/main-nav/nav-item.svelte
> +  export let navItem;
I didn't do it itentionally :o At the moment I cant reach the Gitpod-Dashboard to check, there seems to be a problem with the websocket connection `wss://gitpod.io/api/gitpod`. If the page is reachable again, I can check.

2021-09-13 06:02 UTC, Cahllagerfeld commented on src/components/main-nav/nav-item.svelte
> +  export let navItem;
It was a network issue in my network...
Here are the permissions I granted
![grafik](https://user-images.githubusercontent.com/43843195/133031568-3919ee2d-ea9a-4d52-a0a5-a86c64b8d223.png)

2021-09-13 08:38 UTC, nisarhassan12 commented on src/components/main-nav/nav-item.svelte
> +  export let navItem;
@Cahllagerfeld Thanks. Sorry If I was not able to explain myself in https://github.com/gitpod-io/website/pull/898#discussion_r707006367 It was not your fault I meant it was not caused by you revoking some access or permissions but instead Gitpod showed a misleading popup when the actual issue was that the pre-push hook failed when I tried the push button in the Gitpod UI. 

![image](https://user-images.githubusercontent.com/46004116/133051823-c9edd7fe-eaf2-4b05-985a-53eaebe17fa5.png)